---
title: "R Notebook"
output: html_notebook
---

Some new interpolation tutorials to consider:
https://search.r-project.org/CRAN/refmans/rioja/html/interp.dataset.html
https://github.com/hdugan/NTLlakeloads

```{r}
#Upload packages
library(tidyverse)
library(here)
library(readxl)
library(patchwork)
library(lubridate)
library(MBA)
library(mgcv)
library(FNN)
library(zoo)
library(reshape2)
library(rioja)
library(egg)
library(palr)
library(ggsci)
library(oce)
library(ggpubr)
library(RColorBrewer)

```

```{r}
#QC'd Buoy fluorescence data
#Put buoy QC pipline into Claude for suggestions.

#2022
b22 <- read.csv(here("outputs", "buoy_corr_dm_2022.csv"))
#2024
b24 <- read.csv(here("outputs", "buoy_corr_dm_2024.csv"))

#Buoy salinity data
buoy_ts <- read.csv(here("files", "buoy_ts_all.csv"))

#Corrected CTD fluorescence data
f <- read_csv(here("outputs", "corrected_flu_2025-05-09.csv"))

#Downloading discrete chlorophyll samples - This could be done using the API
cd <- read_csv(here("files", "2024-12-05_HakaiData_chlorophyll.csv"))

#I think these are discrete depth bottle profiles from two dates where the flourometer data failed.

#cm = chlorophylly march 
cm <- read_csv(here("files", "chl_2022-03-09.csv")) 
#cs = chlorophyll september
cs <- read_csv(here("files", "chl_2022-09-09.csv")) 

#I think here I am downloading all of the wind data from the lookout?
wind <- read_csv(here("files", "2025-07-28.1hourSamples.all_2.csv"))

#This is a daily wind anomaly file that I calculated elsewhere. Don't think I need
# wind_anom <- read.csv(here("outputs", "wind_anom_day_2025-04-25.csv"))

#CHEMTAX outputs
chem <- read_csv(here("files", "chemtax_kc10_2024.csv"))

#This is daily mean and lagged data? Why do I have a separate wind file??? Something is funny here as it is very different than the values from the other file.
weath <- read_csv(here("outputs", "enviro_weather_2025-04-14.csv"))

#This is upwelling data.
up <- read_csv(here("files_big", "up_2025-04-24.csv"))


#CHEMTAX outputs
ctd <- read_csv(here("files", "8_binAvg-1752268755732.csv"))

```

```{r}
#Pulling out discharge model outputs for each watershed type and pivoting to long format for plotting
q <- weath %>% 
  select(date, Q_GM, Q_SM, Q_RA) %>% 
  pivot_longer(c(Q_GM:Q_RA), names_to = "Watershed_group", values_to = "Q") %>% 
  drop_na() %>% 
  group_by(date) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  mutate(year = year(date))
```

```{r}
#Pulling out the median nightly buoy fluorescence value from my QC process

#2022
b22 <- b22 %>% 
  select(date_corr, fl_med_day) %>% 
  distinct()

#2024
b24 <- b24 %>% 
  select(date_corr, fl_med_day) %>% 
  distinct()

buoy <- rbind(b22, b24)
```

```{r}
#Pulling out buoy salinity data without flags for 2022 and 2024 and calculating daily mean
buoy_ts <- buoy_ts %>% 
  mutate(measurementTime = mdy_hm(measurementTime),
         date = date(measurementTime)) %>% 
  filter(year %in% c(2022, 2024)) %>% 
  group_by(date) %>% 
  summarise(mean_sal = mean(WaterSalinity[WaterSalinity_UQL == 2], na.rm = TRUE),
            mean_temp = mean(WaterTemp[WaterTemp_UQL == 2], na.rm = TRUE),
            .groups = "drop")
```

```{r}
#Setting the date format for the daily mean wind data and then pulling out each year separated.
wind <- wind %>% 
  mutate(measurementTime2 = mdy_hm(measurementTime),
         date = date(measurementTime2),
         year = year(date))
```

```{r}
#Pulling out the Bulk chlorophyll data for 2022, setting the 0m depth to 1m to join with the CTD fluorometer data and then changing an issue sample with the size-fractionated sum concentration
cd <- cd %>% 
  filter(filter_type == "Bulk GF/F" & line_out_depth == 0) %>% 
  select(date, chla) %>% 
  mutate(chla = case_when(date == "2022-05-05" ~ 1.41,
                          TRUE ~ as.numeric(chla)))
```

```{r}
#There were two saturated CTD casts in 2022 and here, I am prepping to interpolate from discrete sample profiles - this is OK here as they are mixed conditions lacking strong peaks.

#Wrangling the March 2022 discrete chlorophyll fluorescence profile
cm <- cm %>% 
  filter(filter_type == "Bulk GF/F") %>% 
  select(date, pres = line_out_depth, chla) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))
#Wrangling the September 2022 discrete chlorophyll fluorescence profile
cs <- cs %>% 
  filter(filter_type == "Bulk GF/F") %>% 
  select(date, pres = line_out_depth, chla) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))

#Combining the MArch and September discrete chlorophyll profile
c_interp <- rbind(cm, cs)

#Converting discrete chlorophyll profiles to wide format.
c_interp <- c_interp %>% 
  pivot_wider(names_from = "date", values_from = "chla")
```


```{r}
#Performing the interpolation.

# Select chlorophyll data and depths
spec <- c_interp %>%
  select(`2022-03-09`, `2022-09-09`)

depth <- c_interp$pres

# Interpolate to 1m intervals covering full depth range
x.new <- seq(1, max(depth), by = 1)  # Goes to 325m now
sp.interp <- interp.dataset(y = spec, x = depth, xout = x.new,
                           method = "loess", span = 0.8)

# Create interpolated dataframe
interp <- as.data.frame(sp.interp) %>% 
  mutate(pres = x.new) %>% 
  pivot_longer(cols = 1:2, names_to = "date", values_to = "f_npq") %>% 
  mutate(date = as.Date(date),
         year = year(date),
         f_npq = round(f_npq, 2)) %>% 
  select(date, year, pres, f_npq)
```

```{r}
#Wrangling the buoy fluorometer data and joining 2022 and 2024 with both
buoy <- buoy %>% 
  mutate(date = lubridate::ymd(date_corr),
         year = lubridate::year(date),
         yday = lubridate::yday(date)) %>% 
  left_join(cd) %>% 
  left_join(buoy_ts)
```

```{r}
#Working with chemtax data to make it easy to plot

#Making the date column a date format
chem <- chem %>% 
  mutate(date = lubridate::mdy(Date)) %>%
  select(date, cyan = Cyanobacteria, hapt = Hapto, 
         GA = `Prasinophytes-3`, cryp = Cryptophytes,
         dino = `Dinoflagellates-1`, raph = Raphido,
         dict = Dictyo, diat = `Diatoms-1`) %>% #rename groups
  pivot_longer(c(cyan:diat), names_to = "group",
               values_to = "contribution") %>%  #pivot longer
  group_by(date, group) %>% 
  summarise(contribution = mean(contribution)) %>% #Calculating daily mean for duplicates.
  ungroup() %>% 
  group_by(date) %>% 
  mutate(tchla = sum(contribution)) %>% #Calculating TChla concentrations for each day
  ungroup()


#checking to see if there are any duplicates - there were replicates taken for DFO comparisons. None found because I already averaged these for the manuscript.
chem_dup <- chem%>%
  distinct(date, tchla) %>% 
  group_by(date) %>% 
  mutate(dup = n()) %>% 
  ungroup() %>% 
  filter(dup > 1)

#Good to move forward
```
```{r}
ctd_less <- ctd %>% 
  mutate(date = date(`Measurement time`),
         month = month(date),
         year = year(date)) %>% 
  select(cast_pk = `Cast PK`,
         ctd_num = `CTD serial number`,
         station = Station,
         lat = Latitude...11,
         long = Longitude...22,
         date,
         month,
         year,
         date_time = `Measurement time`,
         pres = `Pressure (dbar)`,
         f = `Fluorometry Chlorophyll (ug/L)`,
         t = `Turbidity (FTU)`,
         do =`Dissolved O2 (mL/L)`,
         temp = `Temperature (deg C)`,
         s = `Salinity (PSU)`) %>% 
  mutate(
    # Calculate absolute salinity (g/kg) from practical salinity
    SA = gsw_SA_from_SP(s, pres, long, lat),
    
    # Calculate conservative temperature (°C)
    CT = gsw_CT_from_t(SA, temp, pres),
    
    # Calculate in-situ density (kg/m³)
    density = gsw_rho(SA, CT, pres),
    
    # Calculate potential density referenced to surface (sigma-theta)
    sigma_theta = gsw_sigma0(SA, CT),
    
    # Calculate potential density referenced to 1000 dbar (sigma-1)
    sigma_1 = gsw_sigma1(SA, CT)) %>% 
  group_by(cast_pk) %>%
  mutate(
    # Density stratification
    surface_density = density[which.min(pres)],
    density_30m = density[which.min(abs(pres - 30))],
    density_diff_30m = density_30m - surface_density,
    
    # Temperature stratification
    surface_temp = temp[which.min(pres)],
    temp_30m = temp[which.min(abs(pres - 30))],
    temp_diff_30m = temp_30m - surface_temp  # 30m - surface
  ) %>%
  ungroup()
```

```{r}
# Ordering watershed discharge types for plotting 
riv_loc <- c("Q_GM",
             "Q_SM",
             "Q_RA",
             "Q_tot")

#Setting the order in the discharge dataframe.
q <- arrange(mutate(q, 
                      Watershed_group = factor(Watershed_group,
                                               levels = riv_loc)))

#Setting plotting order phytoplankton groups

#Order phytoplankton groups roughly from smallest to largest - create order list
order_chem <- c("cyan", "hapt", "GA", "cryp",
                   "dino", "raph", "dict", "diat")

#Chemtax full data - Specify order of phyto groups for figures
chem <- arrange(mutate(chem,
                       group = factor(group,
                                      levels = order_chem)))

#Brign over color palette from SOPO
```

```{r}
#Creating the 2022 wind speed cubed plot - what if i added wind direction or vector here?
f_wind_22 <- wind %>%
  group_by(date) %>% 
  summarise(ws = mean(WindSpd_Avg),
            wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  ggplot() +
  geom_point(aes(x = date, y = ws^3, color = wd),
            size = 2) +
  scale_color_viridis_c(option = "turbo") +
  ylim(0, 6000) +
  scale_x_date(limits = as_date(c("2022-01-01",
                                          "2022-12-31")),
                   expand = c(0, 0),
                   date_breaks = "months",
                   date_labels = "%b") +
  labs(y = bquote(Wind~"("*m^3*s^-3*")"),
       color = "Dir (°)") +
  theme_bw() +
  theme(text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

print(f_wind_22)
```
```{r}
#Creating the 2022 wind speed cubed plot - what if i added wind direction or vector here?
wind_calc <- wind %>% 
  select(measurementTime = measurementTime2,
         ws = WindSpd_Avg, wd = WindDir_Avg) %>% 
  mutate(
    # Convert to meteorological convention (direction wind is coming FROM)
    # u = eastward component, v = northward component
    u = -ws * sin(wd * pi/180),  # Negative because wd is "from" direction
    v = -ws * cos(wd * pi/180),
    # Calculate SE component for each hourly observation
    se_component = (u - v) / sqrt(2),
    date = date(measurementTime),
    year = year(measurementTime)
  )


f_se_22 <- wind_calc %>%
  filter(year == 2022) %>% 
  group_by(date) %>% 
  summarise(se_mean = mean(se_component),
            wd_mean = mean(wd)) %>% 
  ungroup() %>% 
  ggplot() +
  geom_line(aes(x = date, y = se_mean),
            size = 1) +
  geom_point(aes(x = date, y = se_mean,
                 color = wd_mean), size = 2) +
  scale_color_viridis_c(option = "turbo") +
  # ylim(0, 6000) +
  scale_x_date(limits = as_date(c("2022-01-01",
                                          "2022-12-31")),
                   expand = c(0, 0),
                   date_breaks = "months",
                   date_labels = "%b") +
  labs(y = bquote(Wind~"("*m^3*s^-3*")"),
       color = "Dir (°)") +
  theme_bw() +
  theme(text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

print(f_se_22)
```




```{r}
#Creating the 2022 wind speed cubed plot - what if i added wind direction or vector here?
f_wind_24 <- wind %>%
  filter(year == 2024) %>%
  group_by(date) %>% 
  summarise(ws = mean(WindSpd_Avg),
            wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  ggplot() +
  geom_line(aes(x = date, y = ws^3), size = 2) +
  geom_point(aes(x = date, y = ws^3, color = wd),
            size = 3) +
  scale_color_viridis_c(option = "turbo") +
  ylim(0, 6000) +
  labs(y = bquote(Wind~"("*m^3*s^-3*")"),
       color = "Dir (°)") +
  scale_x_date(limits = as_date(c("2024-01-01", "2024-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

print(f_wind_24)
```

```{r}
#Creating the 2022 freshwater discharge plot.
f_q_22 <- q %>% 
  filter(year == 2022) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_uchicago() +
  scale_x_date(limits = as.Date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "none",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
        # axis.text.y = element_blank())

print(f_q_22)
```

```{r}
#Creating the 2024 freshwater discharge plot
f_q_24 <- q %>% 
  filter(year == 2024) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_uchicago() +
  scale_x_date(limits = as.Date(c("2024-01-01", "2024-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        # axis.text.y = element_blank()
        )
        # axis.text.y = element_blank())

print(f_q_24)
```

```{r}
#Setting up the joined buoy surface discrete chlorophyll 2m nightly median fluorescence and 2m daily mean salinity/temperature for plotting - pivoting long.

buoy_long <- buoy %>%
  select(date_corr, chla, fl_med_day, mean_sal, mean_temp) %>% 
  pivot_longer(c(chla, fl_med_day, mean_sal, mean_temp),
              names_to = "par", values_to = "val") %>% 
  mutate(date = date(date_corr),
         year = year(date))  
```

```{r}
#Creating buoy figure for 2022 - discrete surface chlorophyll, daily fluorescence/temp/sal
f_buoy_22 <- buoy_long %>% 
  filter(year == 2022) %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  geom_line(data = filter(buoy_long,
                          par == "fl_med_day"),
            size = 2) +
  geom_line(data = filter(buoy_long,
                          par == "mean_sal"),
            size = 2) +
  geom_line(data = filter(buoy_long,
                          par == "mean_temp"),
            size = 2) +
  geom_point(data = filter(buoy_long,
                          par == "chla"),
            size = 4, pch = 8, stroke = 2) +
  ggsci::scale_color_jama(labels = c(expression(Chl[Discrete]),
                                         expression(Chl[BUOY]),
                                         expression(Salinity[BUOY]),
                                     expression(Temp[BUOY]))) +
  scale_x_date(limits = as_date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
                       paste("Salinity,"~"Temp")))) +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "right",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

print(f_buoy_22)
```

```{r}
#Creating buoy figure for 2022 - discrete surface chlorophyll, daily fluorescence/temp/sal
f_buoy_24 <- buoy_long %>% 
  filter(year == 2024) %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  geom_line(data = filter(buoy_long,
                          par == "fl_med_day"),
            size = 2) +
  geom_line(data = filter(buoy_long,
                          par == "mean_sal"),
            size = 2) +
  geom_line(data = filter(buoy_long,
                          par == "mean_temp"),
            size = 2) +
  geom_point(data = filter(buoy_long,
                          par == "chla"),
            size = 4, pch = 8, stroke = 2) +
  ggsci::scale_color_jama(labels = c(expression(Chl[Discrete]),
                                         expression(Chl[BUOY]),
                                         expression(Salinity[BUOY]),
                                     expression(Temp[BUOY]))) +
  scale_x_date(limits = as_date(c("2024-01-01", "2024-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
                       paste("Salinity,"~"Temp")))) +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "right",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

print(f_buoy_24)
```

```{r}
#Adding in 2022 interpolated CTD fluorescence profiles to fill gap of bad data

ctd_fl <- f %>% 
  mutate(year = year(date)) %>% 
  filter(year %in% c(2022, 2024)) %>% 
  select(date, year, pres, f_npq)

ctd_fl <- rbind(ctd_fl, interp)
```

```{r}
#Setting color palette

# Option 3: Viridis-inspired but with dark blue start
fluor_palette_v3 <- colorRampPalette(c(
  "#08306b",  # Deep navy blue
  "#1f4e7a",  # Dark blue
  "#2e6b89",  # Medium blue
  "#4d8fc7",  # Bright blue
  "#2fb3d4",  # Vivid cyan-blue (bloom threshold)
  "#00a693",  # Bright teal
  "#4daf4a",  # Vibrant green
  "#8cc152",  # Lime green
  "#ffd23f",  # Bright yellow
  "#ff8c42",  # Vivid orange
  "#e74c3c"   # Bold red-orange
))

# Generate color vectors (50 colors for smooth gradients)
colors_v3 <- fluor_palette_v3(50)

# Function to create breaks that emphasize bloom threshold
create_fluor_breaks <- function(max_val = 50, bloom_threshold = 5) {
  # More breaks in the 0-10 range to capture bloom dynamics
  c(0, 1, 2, 3, 4, bloom_threshold, 7, 10, 15, 20, 30, 40, max_val)
}
```

```{r}
#Creating CTD profile plot for each year.

f_ctd_fl_22 <- ctd_fl %>% 
  filter(pres < 51 & year == 2022) %>% 
  ggplot(aes(x = date)) +
  geom_tile(aes(y = pres, fill = f_npq)) +

  geom_hline(yintercept = 5,
             linetype = "dashed", size = 1, color = "white") +
  scale_y_reverse(breaks = seq(0, 50, by = 10)) +

    scale_fill_gradientn(colors = colors_v3,
                       values = scales::rescale(c(0, 2, 5, 10, 20, 50))) +
  labs(fill = bquote(CTD[FLU]~"(mg" ~ m^-3*")"),
       y = "Depth") +
  scale_x_date(limits = as_date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        legend.position = "right",
        legend.key.height = unit(1.8, "cm"),
        legend.title = element_text(size = 30, angle = 270),
        legend.title.align = 0.5,
        legend.direction = "vertical",
        axis.text.x = element_blank()
        ) +
    guides(fill = guide_colourbar(title.position = "right"))

print(f_ctd_fl_22)
```

```{r}
#Creating CTD profile plot for each year.

f_ctd_fl_24 <- ctd_fl %>% 
  filter(pres < 51 & year == 2024) %>% 
  ggplot(aes(x = date)) +
  geom_tile(aes(y = pres, fill = f_npq)) +

  geom_hline(yintercept = 5,
             linetype = "dashed", size = 1, color = "white") +
  scale_y_reverse(breaks = seq(0, 50, by = 10)) +

    scale_fill_gradientn(colors = colors_v3,
                       values = scales::rescale(c(0, 2, 5, 10, 20, 50))) +
  labs(fill = bquote(CTD[FLU]~"(mg" ~ m^-3*")"),
       y = "Depth") +
  scale_x_date(limits = as_date(c("2024-01-01", "2024-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        legend.position = "right",
        legend.key.height = unit(1.8, "cm"),
        legend.title = element_text(size = 30, angle = 270),
        legend.title.align = 0.5,
        legend.direction = "vertical",
        axis.text.x = element_blank()
        ) +
    guides(fill = guide_colourbar(title.position = "right"))

print(f_ctd_fl_24)
```
```{r}
f_chem_22 <- chem %>%
  ggplot() +
  geom_bar(aes(date, contribution, fill = fct_rev(group)),
           position = "stack", stat = "identity",
           alpha = 1, color = "black", size = 1) +
  ggsci::scale_fill_npg() +
  scale_x_date(limits = as.Date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Phyto. (mg" ~ m^-3*")"),
       fill = "Group") +
  theme(
        legend.position = "right",
        legend.key.height = unit(0.5, "cm"),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())

print(f_chem_22)
```
```{r}
f_chem_24 <- chem %>%
  ggplot() +
  geom_bar(aes(date, contribution, fill = fct_rev(group)),
           position = "stack", stat = "identity",
           alpha = 1, color = "black", size = 1) +
  ggsci::scale_fill_npg() +
  scale_x_date(limits = as.Date(c("2024-01-01", "2024-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Phyto. (mg" ~ m^-3*")"),
       fill = "Group") +
  theme(
        legend.position = "right",
        legend.key.height = unit(0.5, "cm"),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())

print(f_chem_24)
```
```{r}
f_22_panel <- ggarrange(f_wind_22, f_buoy_22, f_ctd_fl_22, f_chem_22,
                        ncol = 1, align = "hv")

ggsave(here("figures", "panel_kc10_2022_buoy_discrete.png"), f_22_panel,
        width = 16, height = 16, dpi = 300)

f_22_panel_se <- ggarrange(f_se_22, f_buoy_22, f_ctd_fl_22, f_chem_22,
                        ncol = 1, align = "hv")

ggsave(here("figures", "panel_kc10_2022_buoy_discrete.png"), f_22_panel,
        width = 16, height = 16, dpi = 300)

ggsave(here("figures", "panel_kc10_2022_buoy_discrete_se.png"), f_22_panel_se,
        width = 16, height = 16, dpi = 300)

f_24_panel <- ggarrange(f_wind_24, f_buoy_24, f_ctd_fl_24, f_chem_24,
                        ncol = 1, align = "hv")

ggsave(here("figures", "panel_kc10_2024_buoy_discrete.png"), f_24_panel,
        width = 16, height = 16, dpi = 300)
```

```{r}
test <- f %>% 
  left_join(ctd_less)

test %>% 
  filter(pres < 31) %>% 
  ggplot(aes(x = f_npq, y = temp, color = density_30m)) +
  geom_point() +
  scale_color_viridis_c(option = "turbo") 
```

```{r}
f_int <- f %>% 
  mutate(month = month(date)) %>% 
  filter(month == 7) %>% 
  filter(pres <= 30) %>% 
  group_by(date) %>% 
  summarise(int = sum(f_npq)) %>% 
  ungroup() %>% 
  mutate(year = year(date),
         month = month(date)) %>% 
  group_by(year, month) %>% 
  summarise(int_mm = mean(int)) %>% 
  ungroup()

ctd_compare <- ctd_less %>% 
  filter(station == "KC10") %>% 
  select(date, surface_density, surface_temp, density_diff_30m, temp_diff_30m) %>% 
  distinct() %>% 
  pivot_longer(c(surface_density:temp_diff_30m), names_to = "par",
               values_to = "val") %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(month == 7) %>% 
  group_by(year, par) %>% 
  summarise(mean = mean(val, )) %>% 
  ungroup() 

wind_compare <- wind %>% 
  select(date, ws = WindSpd_Avg, wd = WindDir_Avg) %>% 
  pivot_longer(c(ws:wd), names_to = "par",
               values_to = "val") %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(month == 7) %>% 
  group_by(year, par) %>% 
  summarise(mean = mean(val, na.rm = T)) %>% 
  ungroup() 

# Create lagged wind variables
wind_lagged <- wind %>%
  select(date, ws = WindSpd_Avg, wd = WindDir_Avg) %>% 
  pivot_longer(c(ws:wd), names_to = "par",
               values_to = "val") %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(month == 7) %>% 
  group_by(year, par) %>% 
  mutate(
    lag1_mean = lag(val, 1),  # 1 month lag
    lag2_mean = lag(val, 2),  # 2 month lag
    lead1_mean = lead(val, 1) # 1 month lead
  ) %>%
  ungroup()

q_compare <- weath %>% 
  select(date, Q_Total) %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(month == 7) %>% 
  group_by(year) %>% 
  summarise(mean = mean(Q_Total, na.rm = T)) %>% 
  ungroup()

f_int %>% 
  ggplot(aes(x = as.factor(year), y = int_mm)) +
  geom_col()

wind_compare %>% 
  filter(year >= 2015) %>% 
  filter(par == "wd") %>% 
  ggplot(aes(x = as.factor(year), y = mean)) +
  geom_col()

f_int_join <- f_int %>% 
  left_join(wind_compare)

q_compare %>% 
  filter(year >= 2015) %>% 
  ggplot(aes(x = as.factor(year), y = mean)) +
  geom_col()

f_int_join %>% 
  ggplot(aes(x = mean, y = int_mm)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, alpha = 0.2) +
  scale_color_npg() +
  stat_cor(method = "pearson", 
           label.x.npc = "left", 
           label.y.npc = "top",
           size = 4) +
  facet_wrap(~par, scales = "free")
```

```{r}
wind_calc <- wind %>% 
  select(measurementTime = measurementTime2,
         ws = WindSpd_Avg, wd = WindDir_Avg) %>% 
  mutate(
    # Convert to meteorological convention (direction wind is coming FROM)
    # u = eastward component, v = northward component
    u = -ws * sin(wd * pi/180),  # Negative because wd is "from" direction
    v = -ws * cos(wd * pi/180),
    # Calculate SE component for each hourly observation
    se_component = (u - v) / sqrt(2)
  )

# Calculate mean wind for the month prior to each sampling date
wind_lag_vectors <- f %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(month %in% c(4)) %>%
  
  # filter(year != 2019) %>% 
  filter(pres <= 30) %>% 
  group_by(date) %>% 
  summarise(int = sum(f_npq)) %>% 
  ungroup()

wind_lag_vectors <- wind_lag_vectors %>%
  rowwise() %>%
  do({
    sample_date <- .$date
    start_date <- sample_date - days(19)
    end_date <- sample_date - days(1)
    
    period_wind <- wind_calc %>%
      filter(measurementTime >= start_date & measurementTime <= end_date)
    
    if(nrow(period_wind) > 0) {
      data.frame(
        date = sample_date,
        int = .$int,
        mean_u_lag = mean(period_wind$u, na.rm = TRUE),
        mean_v_lag = mean(period_wind$v, na.rm = TRUE),
        mean_se_lag = mean(period_wind$se_component, na.rm = TRUE),
        mean_ws_lag = mean(period_wind$ws, na.rm = TRUE),
        n_obs = nrow(period_wind)
      ) 
    } else {
      data.frame(
        date = sample_date,
        int = .$int,
        mean_u_lag = NA,
        mean_v_lag = NA,
        mean_se_lag = NA,
        mean_ws_lag = NA,
        n_obs = 0
      )
    }
  }) %>%
  ungroup() %>% 
    mutate(
    # Calculate resultant wind speed from mean u and v components
    resultant_ws = sqrt(mean_u_lag^2 + mean_v_lag^2)
  ) 
```


```{r}
# Create a consistent color palette for years 2014-2025
# Based on Set1 but with problematic colors removed/modified

# Get Set1 colors and modify them
set1_colors <- brewer.pal(9, "Set1")

# Create a custom palette excluding white/yellow and adding darker alternatives
custom_colors <- c(
  set1_colors[1],  # Red
  set1_colors[2],  # Blue  
  set1_colors[3],  # Green
  set1_colors[4],  # Purple
  set1_colors[5],  # Orange
  set1_colors[7],  # Brown
  set1_colors[8],  # Pink
  set1_colors[9],  # Grey
  "#2F4F4F",       # Dark slate gray (replacing light colors)
  "#8B4513",       # Saddle brown
  "#483D8B",       # Dark slate blue
  "#8B008B"        # Dark magenta
)

# Create named vector for years 2014-2025
year_colors <- setNames(custom_colors[1:12], 2014:2025)

# Function to get consistent colors for any subset of years
get_year_colors <- function(years_present) {
  return(year_colors[as.character(years_present)])
}

# Example usage in your plot:
wind_lag_vectors %>%
  mutate(year = year(date)) %>%
  select(int, mean_se_lag, mean_ws_lag, resultant_ws, year) %>%
  pivot_longer(cols = -c(int, year), names_to = "wind_param", values_to = "wind_value") %>%
  filter(!is.na(wind_value)) %>%
  ggplot(aes(x = wind_value, y = int)) +
  geom_point(aes(color = as.factor(year)), size = 3) +
  geom_smooth(method = "lm", se = TRUE, alpha = 0.2, color = "black", linewidth = 0.8) +
  stat_cor(method = "pearson", 
           label.x.npc = "left", 
           label.y.npc = "top",
           size = 5,
           label.sep = ", ") +
  # Use the custom color palette - fixed to match factor levels
  scale_color_manual(values = year_colors) +
  facet_wrap(~wind_param, scales = "free", 
             labeller = labeller(wind_param = c(
               "mean_u_lag" = "Eastward wind",
               "mean_v_lag" = "Northward wind", 
               "mean_ws_lag" = "Wind speed",
               "resultant_ws" = "Resultant speed",
               "mean_se_lag" = "NW-SE component"))) +
  theme_bw() +
  theme(
    panel.grid.minor = element_blank(),
    text = element_text(size = 18),
    strip.text = element_text(size = 16, face = "bold"),
    axis.text = element_text(color = "black"),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  labs(x = bquote("Wind component/speed"~(m~s^-1)), 
       y = bquote("Integrated fluorescence"~(mg~m^-2)),
       title = "Wind-Integrated Chlorophyll Correlations",
       subtitle = "April - Prior 2 day mean lookout wind") +
  guides(color = guide_legend(nrow = 1, override.aes = list(size = 3)))

# Alternative: If you want to dynamically adjust based on years present in each month
create_month_plot <- function(data, month_name) {
  data %>%
    mutate(year = year(date)) %>%
    select(int, mean_se_lag, mean_ws_lag, resultant_ws, year) %>%
    pivot_longer(cols = -c(int, year), names_to = "wind_param", values_to = "wind_value") %>%
    filter(!is.na(wind_value)) %>%
    ggplot(aes(x = wind_value, y = int)) +
    geom_point(aes(color = as.factor(year)), size = 3) +
    geom_smooth(method = "lm", se = TRUE, alpha = 0.2, color = "black", linewidth = 0.8) +
    stat_cor(method = "pearson", 
             label.x.npc = "left", 
             label.y.npc = "top",
             size = 5,
             label.sep = ", ") +
    scale_color_manual(values = year_colors) +
    facet_wrap(~wind_param, scales = "free", 
               labeller = labeller(wind_param = c(
                 "mean_u_lag" = "Eastward wind",
                 "mean_v_lag" = "Northward wind", 
                 "mean_ws_lag" = "Wind speed",
                 "resultant_ws" = "Resultant speed",
                 "mean_se_lag" = "NW-SE component"))) +
    theme_bw() +
    theme(
      panel.grid.minor = element_blank(),
      text = element_text(size = 18),
      strip.text = element_text(size = 16, face = "bold"),
      axis.text = element_text(color = "black"),
      legend.position = "bottom",
      legend.title = element_blank()
    ) +
    labs(x = bquote("Wind component/speed"~(m~s^-1)), 
         y = bquote("Integrated fluorescence"~(mg~m^-2)),
         title = "Wind-Integrated Chlorophyll Correlations",
         subtitle = "July - Prior 3 day mean lookout wind") +
    guides(color = guide_legend(nrow = 1, override.aes = list(size = 3)))
}

# Display the color palette for reference
# data.frame(
#   year = 2014:2025,
#   color = year_colors
# ) %>%
#   ggplot(aes(x = year, y = 1, fill = factor(year))) +
#   geom_col() +
#   scale_fill_manual(values = year_colors) +
#   theme_minimal() +
#   labs(title = "Custom Year Color Palette", 
#        subtitle = "Consistent colors for 2014-2025") +
#   theme(legend.position = "none",
#         axis.text.y = element_blank(),
#         axis.title.y = element_blank())

# ggsave(here("figures", "scatters_august_2_day.png"), 
#         width = 12, height = 5, dpi = 300)
```

```{r}
# Function to calculate wind metrics for a specific lag period
calculate_wind_lag <- function(f_data, wind_calc, lag_days) {
  f_data %>% 
    mutate(month = month(date),
           year = year(date)) %>% 
    filter(month %in% c(8)) %>% 
    # filter(!year %in% c(2020, 2021)) %>% 
    filter(pres <= 30) %>% 
    group_by(date) %>% 
    summarise(int = sum(f_npq), .groups = 'drop') %>% 
    rowwise() %>%
    do({
      sample_date <- .$date
      start_date <- sample_date - days(lag_days)
      end_date <- sample_date - days(1)
      
      period_wind <- wind_calc %>%
        filter(measurementTime >= start_date & measurementTime <= end_date)
      
      if(nrow(period_wind) > 0) {
        # Calculate mean u and v components first
        mean_u <- mean(period_wind$u, na.rm = TRUE)
        mean_v <- mean(period_wind$v, na.rm = TRUE)
        mean_se <- mean(period_wind$se_component, na.rm = TRUE)
        mean_ws <- mean(period_wind$ws, na.rm = TRUE)
        
        # Calculate resultant speed from mean u and v components
        resultant_speed <- sqrt(mean_u^2 + mean_v^2)
        
        data.frame(
          date = sample_date,
          int = .$int,
          mean_se_lag = mean_se,
          mean_ws_lag = mean_ws,
          mean_resultant_lag = resultant_speed,
          n_obs = nrow(period_wind),
          lag_days = lag_days
        )
      } else {
        data.frame(
          date = sample_date,
          int = .$int,
          mean_se_lag = NA,
          mean_ws_lag = NA,
          mean_resultant_lag = NA,
          n_obs = 0,
          lag_days = lag_days
        )
      }
    }) %>%
    ungroup()
}

# Function to test multiple lag periods
test_lag_periods <- function(f_data, wind_calc, lag_range = 1:30) {
  
  results <- map_dfr(lag_range, function(lag) {
    wind_data <- calculate_wind_lag(f_data, wind_calc, lag)
    
    # Remove rows with missing wind data
    wind_data_clean <- wind_data %>% filter(!is.na(mean_se_lag))
    
    if(nrow(wind_data_clean) < 5) {
      return(data.frame(
        lag_days = lag,
        se_component_r = NA,
        se_component_p = NA,
        wind_speed_r = NA,
        wind_speed_p = NA,
        resultant_speed_r = NA,
        resultant_speed_p = NA,
        n_samples = nrow(wind_data_clean)
      ))
    }
    
    # Calculate correlations
    se_cor <- cor.test(wind_data_clean$mean_se_lag, wind_data_clean$int)
    ws_cor <- cor.test(wind_data_clean$mean_ws_lag, wind_data_clean$int)
    resultant_cor <- cor.test(wind_data_clean$mean_resultant_lag, wind_data_clean$int)
    
    data.frame(
      lag_days = lag,
      se_component_r = se_cor$estimate,
      se_component_p = se_cor$p.value,
      wind_speed_r = ws_cor$estimate,
      wind_speed_p = ws_cor$p.value,
      resultant_speed_r = resultant_cor$estimate,
      resultant_speed_p = resultant_cor$p.value,
      n_samples = nrow(wind_data_clean)
    )
  })
  
  return(results)
}

# Run the analysis for lags 1-30 days
lag_results <- test_lag_periods(f, wind_calc, lag_range = 1:30)

# Display results sorted by strongest SE component correlation
lag_results %>%
  arrange(desc(abs(se_component_r))) %>%
  filter(!is.na(se_component_r)) %>%
  mutate(
    se_sig = ifelse(se_component_p < 0.05, "***", ""),
    ws_sig = ifelse(wind_speed_p < 0.05, "***", ""),
    resultant_sig = ifelse(resultant_speed_p < 0.05, "***", "")
  ) %>%
  select(lag_days, se_component_r, se_sig, wind_speed_r, ws_sig, resultant_speed_r, resultant_sig, n_samples) %>%
  head(10)

# Plot correlation strength vs lag period
library(ggplot2)
library(tidyr)

# Reshape for plotting and add significance info
lag_plot_data <- lag_results %>%
  select(lag_days, se_component_r, se_component_p, wind_speed_r, wind_speed_p, resultant_speed_r, resultant_speed_p) %>%
  pivot_longer(cols = -lag_days, 
               names_to = c("wind_metric", "stat_type"), 
               names_sep = "_(?=r$|p$)",
               values_to = "value") %>%
  pivot_wider(names_from = stat_type, values_from = value) %>%
  mutate(
    wind_metric = case_when(
      wind_metric == "se_component" ~ "SE component",
      wind_metric == "wind_speed" ~ "Wind speed",
      wind_metric == "resultant_speed" ~ "Resultant speed"
    ),
    significant = p < 0.05,
    correlation = r
  )

# Create the plot with significance indicators
ggplot(lag_plot_data, aes(x = lag_days, y = correlation, color = wind_metric)) +
  geom_line(size = 2) +
  geom_point(aes(shape = significant, size = significant), size = 5) +
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
  scale_shape_manual(values = c("FALSE" = 1, "TRUE" = 16), 
                     name = "Significant\n(p < 0.05)",
                     labels = c("No", "Yes")) +
  scale_size_manual(values = c("FALSE" = 2, "TRUE" = 3),
                    guide = "none") +
  labs(
    x = "Lag period (days)",
    y = "Correlation coefficient (r)",
    title = "Wind-Chlorophyll Correlations vs Lag Period",
    subtitle = "August data",
    color = "Wind metric"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom",
        text = element_text(size = 24)) +
  scale_x_continuous(breaks = seq(0, 30, 5)) +
  guides(color = guide_legend(order = 1),
         shape = guide_legend(order = 2))

# Find optimal lags for each metric
optimal_lags <- lag_results %>%
  filter(!is.na(se_component_r)) %>%
  summarise(
    se_component_optimal = lag_days[which.max(abs(se_component_r))],
    se_component_max_r = se_component_r[which.max(abs(se_component_r))],
    wind_speed_optimal = lag_days[which.max(abs(wind_speed_r))],
    wind_speed_max_r = wind_speed_r[which.max(abs(wind_speed_r))],
    resultant_optimal = lag_days[which.max(abs(resultant_speed_r))],
    resultant_max_r = resultant_speed_r[which.max(abs(resultant_speed_r))]
  )

ggsave(here("figures", "lag_august.png"),
        width = 13, height = 8, dpi = 300)

print("Optimal lag periods:")
print(optimal_lags)
```

```{r}
# Function to find optimal lag and correlation for each month-variable combination
analyze_monthly_correlations <- function(f_data, wind_calc, months = 1:12, lag_range = 1:30) {
  
  results <- map_dfr(months, function(m) {
    
    # Modify the calculate_wind_lag function for specific month
    monthly_results <- map_dfr(lag_range, function(lag) {
      wind_data <- f_data %>% 
        mutate(month = month(date)) %>% 
        filter(month == m) %>% 
        filter(pres <= 30) %>% 
        group_by(date) %>% 
        summarise(int = sum(f_npq), .groups = 'drop') %>% 
        rowwise() %>%
        do({
          sample_date <- .$date
          start_date <- sample_date - days(lag)
          end_date <- sample_date - days(1)
          
          period_wind <- wind_calc %>%
            filter(measurementTime >= start_date & measurementTime <= end_date)
          
          if(nrow(period_wind) > 0) {
            # Calculate mean u and v components first
            mean_u <- mean(period_wind$u, na.rm = TRUE)
            mean_v <- mean(period_wind$v, na.rm = TRUE)
            mean_se <- mean(period_wind$se_component, na.rm = TRUE)
            mean_ws <- mean(period_wind$ws, na.rm = TRUE)
            
            # Calculate resultant speed from mean u and v components
            resultant_speed <- sqrt(mean_u^2 + mean_v^2)
            
            data.frame(
              date = sample_date,
              int = .$int,
              mean_u_lag = mean_u,
              mean_v_lag = mean_v,
              mean_se_lag = mean_se,
              mean_ws_lag = mean_ws,
              mean_resultant_lag = resultant_speed,
              n_obs = nrow(period_wind)
            )
          } else {
            data.frame(
              date = sample_date,
              int = .$int,
              mean_u_lag = NA,
              mean_v_lag = NA,
              mean_se_lag = NA,
              mean_ws_lag = NA,
              mean_resultant_lag = NA,
              n_obs = 0
            )
          }
        }) %>%
        ungroup()
      
      # Remove rows with missing wind data
      wind_data_clean <- wind_data %>% filter(!is.na(mean_u_lag))
      
      if(nrow(wind_data_clean) < 5) {
        return(data.frame(
          month = m,
          lag_days = lag,
          eastward_r = NA,
          eastward_p = NA,
          northward_r = NA,
          northward_p = NA,
          se_component_r = NA,
          se_component_p = NA,
          wind_speed_r = NA,
          wind_speed_p = NA,
          resultant_speed_r = NA,
          resultant_speed_p = NA,
          n_samples = nrow(wind_data_clean)
        ))
      }
      
      # Calculate correlations
      east_cor <- cor.test(wind_data_clean$mean_u_lag, wind_data_clean$int)
      north_cor <- cor.test(wind_data_clean$mean_v_lag, wind_data_clean$int)
      se_cor <- cor.test(wind_data_clean$mean_se_lag, wind_data_clean$int)
      ws_cor <- cor.test(wind_data_clean$mean_ws_lag, wind_data_clean$int)
      resultant_cor <- cor.test(wind_data_clean$mean_resultant_lag, wind_data_clean$int)
      
      data.frame(
        month = m,
        lag_days = lag,
        eastward_r = east_cor$estimate,
        eastward_p = east_cor$p.value,
        northward_r = north_cor$estimate,
        northward_p = north_cor$p.value,
        se_component_r = se_cor$estimate,
        se_component_p = se_cor$p.value,
        wind_speed_r = ws_cor$estimate,
        wind_speed_p = ws_cor$p.value,
        resultant_speed_r = resultant_cor$estimate,
        resultant_speed_p = resultant_cor$p.value,
        n_samples = nrow(wind_data_clean)
      )
    })
    
    return(monthly_results)
  })
  
  return(results)
}

# Run analysis for all months
monthly_results <- analyze_monthly_correlations(f, wind_calc, months = 1:12, lag_range = 1:30)

# Find optimal lag for each month-variable combination
optimal_monthly <- monthly_results %>%
  filter(!is.na(eastward_r)) %>%
  group_by(month) %>%
  summarise(
    eastward_optimal_lag = lag_days[which.max(abs(eastward_r))],
    eastward_max_r = eastward_r[which.max(abs(eastward_r))],
    eastward_p = eastward_p[which.max(abs(eastward_r))],
    
    northward_optimal_lag = lag_days[which.max(abs(northward_r))],
    northward_max_r = northward_r[which.max(abs(northward_r))],
    northward_p = northward_p[which.max(abs(northward_r))],
    
    se_optimal_lag = lag_days[which.max(abs(se_component_r))],
    se_max_r = se_component_r[which.max(abs(se_component_r))],
    se_p = se_component_p[which.max(abs(se_component_r))],
    
    ws_optimal_lag = lag_days[which.max(abs(wind_speed_r))],
    ws_max_r = wind_speed_r[which.max(abs(wind_speed_r))],
    ws_p = wind_speed_p[which.max(abs(wind_speed_r))],
    
    resultant_optimal_lag = lag_days[which.max(abs(resultant_speed_r))],
    resultant_max_r = resultant_speed_r[which.max(abs(resultant_speed_r))],
    resultant_p = resultant_speed_p[which.max(abs(resultant_speed_r))],
    .groups = 'drop'
  )

# Reshape for heatmap plotting
heatmap_data <- optimal_monthly %>%
  pivot_longer(
    cols = c(eastward_optimal_lag:eastward_p, northward_optimal_lag:northward_p, 
             se_optimal_lag:se_p, ws_optimal_lag:ws_p, resultant_optimal_lag:resultant_p),
    names_to = c("variable", "metric"),
    names_pattern = "(.*)_(optimal_lag|max_r|p)$",
    values_to = "value"
  ) %>%
  pivot_wider(names_from = metric, values_from = value) %>%
  mutate(
    variable = case_when(
      variable == "eastward" ~ "Eastward (E-W)",
      variable == "northward" ~ "Northward (N-S)",
      variable == "se" ~ "Southeastward (SE-NW)",
      variable == "ws" ~ "Wind Speed", 
      variable == "resultant" ~ "Resultant Speed"
    ),
    # Set factor levels to control x-axis order
    variable = factor(variable, levels = c("Eastward (E-W)", "Northward (N-S)", "Southeastward (SE-NW)", "Wind Speed", "Resultant Speed")),
    month_name = month.abb[month],
    significant = p < 0.05,
    abs_correlation = abs(max_r),
    # Set non-significant correlations to NA for white coloring
    max_r_sig = ifelse(significant, max_r, NA),
    optimal_lag_sig = ifelse(significant, optimal_lag, NA),
    # Add significance stars
    sig_stars = case_when(
      p < 0.001 ~ "***",
      p < 0.01 ~ "**", 
      p < 0.05 ~ "*",
      TRUE ~ ""
    )
  )

# Create the heatmap
library(ggplot2)

# Plot 1: Correlation strength heatmap with significance stars
p1 <- ggplot(heatmap_data, aes(x = variable, y = factor(month_name, levels = month.abb[1:12]))) +
  geom_tile(aes(fill = max_r_sig), color = "gray", size = 0.5) +
  geom_text(aes(label = ifelse(significant, paste0(round(max_r, 2), sig_stars), "")), 
            color = "white", fontface = "bold", size = 6) +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", 
                       midpoint = 0, name = "Correlation coefficient (r)",
                       limits = c(-1, 1), na.value = "white",
                       guide = guide_colorbar(title.position = "top", 
                                            title.hjust = 0.5,
                                            barwidth = 25, 
                                            barheight = 1)) +
  labs(
    # title = "Wind-Chlorophyll Correlations by Month",
    # subtitle = "Only significant correlations (p < 0.05) are colored",
    x = "Wind Variable",
    y = "Month"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    text = element_text(size = 27, face = "bold"), 
    panel.grid = element_blank(),
    legend.position = "top",
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    axis.title.x = element_blank()
  )

# Plot 2: Optimal lag periods
p2 <- ggplot(heatmap_data, aes(x = variable, y = factor(month_name, levels = month.abb[1:12]))) +
  geom_tile(aes(fill = optimal_lag_sig), color = "gray", size = 0.5) +
  geom_text(aes(label = ifelse(significant, paste0(round(optimal_lag), "d"), "")), 
            color = "white", fontface = "bold", size = 6) +
  scale_fill_viridis_c(name = "Optimal backward mean period (days)", na.value = "white",
                       guide = guide_colorbar(title.position = "top", 
                                            title.hjust = 0.5,
                                            barwidth = 25, 
                                            barheight = 1)) +
  labs(
    # title = "Optimal Lag Periods by Month",
    # subtitle = "Only significant correlations shown",
    x = "Wind Variable",
    y = "Month"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    text = element_text(size = 27, face = "bold"), 
    panel.grid = element_blank(),
    legend.position = "top",
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    axis.text.y = element_blank(),
    axis.title.y = element_blank(),
    axis.title.x = element_blank()
  )

# Create sample size data (take one variable since n_samples is the same across variables)
sample_size_data <- heatmap_data %>%
  filter(variable == "Eastward (E-W)") %>%
  select(month, month_name) %>%
  left_join(
    monthly_results %>%
      filter(!is.na(eastward_r)) %>%
      group_by(month) %>%
      slice(1) %>%
      select(month, n_samples),
    by = "month"
  )

# Plot 3: Sample sizes
p3 <- ggplot(sample_size_data, aes(x = 1, y = factor(month_name, levels = month.abb[1:12]))) +
  geom_tile(aes(fill = n_samples), color = "gray", size = 0.5) +
  geom_text(aes(label = n_samples), color = "white", fontface = "bold", size = 6) +
  scale_fill_viridis_c(name = "Sample size (n)", na.value = "white",
                       guide = guide_colorbar(title.position = "top", 
                                            title.hjust = 0.5,
                                            barwidth = 25, 
                                            barheight = 1)) +
  labs(
    x = "Sample Size",
    y = "Month"
  ) +
  theme_bw() +
  theme(
    text = element_text(size = 27, face = "bold"), 
    panel.grid = element_blank(),
    legend.position = "top",
    axis.text.y = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.title.x = element_blank()
  )

# Display both plots
print(p1)
print(p2)
print(p3)

fig <- p1 + p2
# + p3

ggsave(here("figures", "heatmap.png"), fig,
        width = 15, height = 16, dpi = 300)
```


```{r}
wind_calc_dm <- wind_calc %>% 
  mutate(date = date(measurementTime)) %>% 
  group_by(date) %>% 
  summarise(se = mean(se_component)) %>% 
  ungroup() 

b_join <- buoy %>%
  select(date, year, fl_med_day) %>% 
  mutate(month = month(date)) %>% 
  left_join(wind_calc_dm)
```
```{r}
# Create 19-day backwards averaged SE wind component
b22_analysis <- b_join %>%
  arrange(date) %>%  # Ensure chronological order
  mutate(
    # 19-day backwards rolling average of SE wind
    se_19day_back = zoo::rollmean(se, k = 19, fill = NA, align = "right"),
    # Extract month for filtering
    month = lubridate::month(date)
  ) %>%
  # Filter to April data to match your CTD analysis
  filter(month %in% c(4)) %>%
  # Remove rows with missing data
  drop_na(fl_med_day, se_19day_back)

# Calculate correlation
correlation_result <- cor.test(b22_analysis$fl_med_day, b22_analysis$se_19day_back)

# Print correlation results
cat("Correlation between daily fluorescence and 19-day backwards SE wind (April only):\n")
cat("r =", round(correlation_result$estimate, 3), "\n")
cat("p-value =", round(correlation_result$p.value, 4), "\n")
cat("n =", nrow(b22_analysis), "observations\n")

# Create scatter plot
april_plot <- ggplot(b22_analysis,
                     aes(x = se_19day_back,
                         y = fl_med_day,
                         color = as.factor(year))) +
  geom_point(alpha = 0.6, size = 2) +
  geom_smooth(method = "lm", se = TRUE, color = "#d73027") +
  labs(
    x = "19-day Backwards Averaged SE Wind Component (m/s)",
    y = "Daily Median Fluorescence",
    title = "Daily Buoy Fluorescence vs SE Wind (April)",
    subtitle = paste("r =", round(correlation_result$estimate, 3), 
                     ", p =", round(correlation_result$p.value, 4))
  ) +
  theme_bw() +
  theme(
    text = element_text(size = 12),
    plot.title = element_text(size = 14, face = "bold")
  )

print(april_plot)
```


```{r}
# Optional: Test different averaging windows to see if 19 days is optimal
test_windows <- c(5, 10, 15, 19, 25, 30)

window_results <- map_dfr(test_windows, function(window) {
  temp_data <- b_join %>%
    arrange(date) %>%
    mutate(
      se_back = zoo::rollmean(se, k = window, fill = NA, align = "right"),
      month = lubridate::month(date)
    ) %>%
    filter(month %in% c(7)) %>%
    drop_na(fl_med_day, se_back)
  
  if(nrow(temp_data) > 10) {  # Need sufficient data
    cor_result <- cor.test(temp_data$fl_med_day, temp_data$se_back)
    tibble(
      window_days = window,
      correlation = cor_result$estimate,
      p_value = cor_result$p.value,
      n_obs = nrow(temp_data)
    )
  }
}) %>%
  arrange(desc(abs(correlation)))

cat("\nCorrelations for different backwards averaging windows:\n")
print(window_results)

# Plot window sensitivity
window_plot <- ggplot(window_results, aes(x = window_days, y = correlation)) +
  geom_line(size = 1) +
  geom_point(size = 3) +
  geom_point(data = filter(window_results, window_days == 19), 
             color = "#d73027", size = 4) +
  labs(
    x = "Backwards Averaging Window (days)",
    y = "Correlation Coefficient",
    title = "Sensitivity to SE Wind Averaging Window",
    subtitle = "Red point = 19-day window from CTD analysis"
  ) +
  theme_bw()

print(window_plot)
```















```{r}
wind_calc %>% 
  mutate(date = date(measurementTime),
         year = year(date),
         month = month(date),
         yday = yday(date),
         se_component = (u - v) / sqrt(2)) %>% 
  filter(month == 4) %>% 
  filter(year %in% c(2015, 2021)) %>% 
  ggplot() +
  geom_point(aes(x = yday, y = ws, color = wd)) +
  geom_line((aes(x = yday, y = se_component))) +
  scale_color_viridis_c(option = "turbo") +
  facet_grid(.~year)
```
```{r}
library(dplyr)
library(ggplot2)
library(lubridate)
library(viridis)

# Prepare sampling dates first to determine date range
sampling_dates <- f %>%
  mutate(year = year(date),
         month = month(date)) %>%
  filter(month == 4, year %in% c(2014, 2015, 2018, 2021, 2022))

# Create expanded date ranges: 30 days before sampling + rest of sampling month
date_ranges <- sampling_dates %>%
  mutate(
    start_date = date - days(30),
    end_date = ceiling_date(date, "month") - days(1)  # Last day of sampling month
  ) %>%
  select(year, date, start_date, end_date)

# Prepare wind data with expanded date range
wind_plot_data <- wind_calc %>% 
  mutate(wind_date = date(measurementTime),
         year = year(wind_date),
         se_component = (u - v) / sqrt(2)) %>%
  # Filter for years of interest first
  filter(year %in% c(2014, 2015, 2018, 2021, 2022)) %>%
  # Join with date ranges
  left_join(date_ranges %>% select(year, sampling_date = date, start_date, end_date), 
            by = "year", 
            relationship = "many-to-many") %>%
  # Filter using the renamed columns
  filter(wind_date >= start_date & wind_date <= end_date) %>%
  # Convert to daily averages
  group_by(wind_date, year) %>%
  summarise(
    ws = mean(ws, na.rm = TRUE),
    wd = mean(wd, na.rm = TRUE),
    se_component = mean(se_component, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  # Add month-day for x-axis
  mutate(month_day = format(wind_date, "%m-%d")) %>%
  rename(date = wind_date)

# Prepare sampling date markers with 19-day backward period
sampling_markers <- sampling_dates %>%
  mutate(
    period_start = date - days(18),  # 19 days including sampling day
    period_end = date,
    month_day = format(date, "%m-%d"),
    period_start_md = format(period_start, "%m-%d"),
    period_end_md = format(period_end, "%m-%d")
  )

# Create the enhanced plot
ggplot() +
  # Add grey boxes for 19-day backward periods
  geom_rect(data = sampling_markers,
            aes(xmin = period_start_md, 
                xmax = period_end_md,
                ymin = -Inf, 
                ymax = Inf),
            fill = "grey80", 
            alpha = 0.6) +
  
  # Wind speed points colored by direction
  geom_point(data = wind_plot_data,
             aes(x = month_day, y = ws, color = wd),
             size = 1.8, alpha = 0.8) +
  
  # SE component line
  geom_line(data = wind_plot_data,
            aes(x = month_day, y = se_component, group = year),
            color = "black", 
            linewidth = 0.9,
            alpha = 0.9) +
  
  # Vertical lines for exact sampling dates
  geom_vline(data = sampling_markers,
             aes(xintercept = month_day),
             color = "red", 
             linewidth = 1.2,
             alpha = 0.8) +
  
  # Color scale for wind direction
  scale_color_viridis_c(option = "turbo", 
                        name = "Wind Direction\n(degrees)",
                        guide = guide_colorbar(barwidth = 1, 
                                              barheight = 8)) +
  
  # X-axis with better date formatting
  scale_x_discrete(name = "Date (Month-Day)",
                   breaks = function(x) {
                     # Show every 5th date for readability
                     indices <- seq(1, length(x), by = 5)
                     return(x[indices])
                   }) +
  
  scale_y_continuous(name = bquote("Wind Speed"~(m~s^-1)~"/ SE Component"),
                     expand = expansion(mult = c(0.05, 0.05))) +
  
  # Faceting by year
  facet_wrap(~ year, 
             labeller = label_both,
             scales = "free_x") +
  
  # Theme
  theme_bw() +
  theme(
    panel.grid.minor.x = element_line(color = "grey95", size = 0.3),
    panel.grid.major = element_line(color = "grey90", size = 0.5),
    text = element_text(size = 12),
    strip.text = element_text(size = 14, face = "bold"),
    axis.text = element_text(color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
    legend.position = "right",
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12, color = "grey30")
  ) +
  
  # Labels and title
  labs(title = "Extended Wind Patterns Around April Sampling",
       subtitle = "30 days before sampling + remainder of sampling month\nSE Component (black line) vs Wind Speed (colored points) - Daily averages",
       caption = paste("Grey boxes: 19-day backward averaging periods | Red lines: Sampling dates"))

ggsave(here("figures", "lag_period_test.png"),
        width = 16, height = 8, dpi = 300)
```
```{r}
# Prepare sampling dates first to determine date range
sampling_dates <- f %>%
  mutate(year = year(date),
         month = month(date)) %>%
  filter(month == 4, year %in% c(2014, 2015, 2018, 2021, 2022))

# Create expanded date ranges: 30 days before sampling + rest of sampling month
date_ranges <- sampling_dates %>%
  mutate(
    start_date = date - days(30),
    end_date = ceiling_date(date, "month") - days(1)  # Last day of sampling month
  ) %>%
  select(year, date, start_date, end_date)

# Prepare wind data with expanded date range
wind_plot_data <- wind_calc %>% 
  mutate(wind_date = date(measurementTime),
         year = year(wind_date),
         se_component = (u - v) / sqrt(2)) %>%
  # Filter for years of interest first
  filter(year %in% c(2014, 2015, 2018, 2021, 2022)) %>%
  # Join with date ranges
  left_join(date_ranges %>% select(year, sampling_date = date, start_date, end_date), 
            by = "year", 
            relationship = "many-to-many") %>%
  # Filter using the renamed columns
  filter(wind_date >= start_date & wind_date <= end_date) %>%
  # Convert to daily averages
  group_by(wind_date, year) %>%
  summarise(
    ws = mean(ws, na.rm = TRUE),
    wd = mean(wd, na.rm = TRUE),
    se_component = mean(se_component, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  # Add month-day for x-axis
  mutate(month_day = format(wind_date, "%m-%d")) %>%
  rename(date = wind_date)

# Calculate 19-day SE-NW component averages for each sampling period
se_averages <- sampling_dates %>%
  mutate(
    period_start = date - days(18),  # 19 days including sampling day
    period_end = date
  ) %>%
  left_join(
    wind_plot_data %>% select(date, year, se_component),
    by = "year",
    relationship = "many-to-many"
  ) %>%
  filter(date.y >= period_start & date.y <= period_end) %>%
  group_by(year, date.x) %>%
  summarise(
    se_avg_19day = mean(se_component, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  rename(date = date.x) %>%
  left_join(sampling_dates, by = c("year", "date"))

# Prepare sampling date markers with 19-day backward period and averages
sampling_markers <- se_averages %>%
  mutate(
    period_start = date - days(18),  # 19 days including sampling day
    period_end = date,
    month_day = format(date, "%m-%d"),
    period_start_md = format(period_start, "%m-%d"),
    period_end_md = format(period_end, "%m-%d"),
    # Format the average for display
    se_avg_label = paste0("19-day SE avg:\n", round(se_avg_19day, 2), " m/s")
  )

# Create the enhanced plot
ggplot() +
  # Add grey boxes for 19-day backward periods
  geom_rect(data = sampling_markers,
            aes(xmin = period_start_md, 
                xmax = period_end_md,
                ymin = -Inf, 
                ymax = Inf),
            fill = "grey80", 
            alpha = 0.6) +
  
  # Wind speed points colored by direction
  geom_point(data = wind_plot_data,
             aes(x = month_day, y = ws, color = wd),
             size = 1.8, alpha = 0.8) +
  
  # SE component line
  geom_line(data = wind_plot_data,
            aes(x = month_day, y = se_component, group = year),
            color = "black", 
            linewidth = 0.9,
            alpha = 0.9) +
  
  # Vertical lines for exact sampling dates
  geom_vline(data = sampling_markers,
             aes(xintercept = month_day),
             color = "red", 
             linewidth = 1.2,
             alpha = 0.8) +
  
  # Add SE average text labels in grey boxes
  geom_text(data = sampling_markers,
            aes(x = period_start_md, 
                y = Inf,
                label = se_avg_label),
            hjust = 0, 
            vjust = 1.1,
            size = 3.5,
            color = "darkblue",
            fontface = "bold",
            background = "white") +
  
  # Color scale for wind direction
  scale_color_viridis_c(option = "turbo", 
                        name = "Wind Direction\n(degrees)",
                        guide = guide_colorbar(barwidth = 1, 
                                              barheight = 8)) +
  
  # X-axis with better date formatting
  scale_x_discrete(name = "Date (Month-Day)",
                   breaks = function(x) {
                     # Show every 5th date for readability
                     indices <- seq(1, length(x), by = 5)
                     return(x[indices])
                   }) +
  
  scale_y_continuous(name = bquote("Wind Speed"~(m~s^-1)~"/ SE Component"),
                     expand = expansion(mult = c(0.1, 0.05))) +  # Extra space at top for labels
  
  # Faceting by year
  facet_wrap(~ year, 
             labeller = label_both,
             scales = "free_x") +
  
  # Theme
  theme_bw() +
  theme(
    panel.grid.minor.x = element_line(color = "grey95", size = 0.3),
    panel.grid.major = element_line(color = "grey90", size = 0.5),
    text = element_text(size = 12),
    strip.text = element_text(size = 14, face = "bold"),
    axis.text = element_text(color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
    legend.position = "right",
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12, color = "grey30")
  ) +
  
  # Labels and title
  labs(title = "Extended Wind Patterns Around April Sampling",
       subtitle = "30 days before sampling + remainder of sampling month\nSE Component (black line) vs Wind Speed (colored points) - Daily averages",
       caption = paste("Grey boxes: 19-day backward averaging periods with SE-NW component averages | Red lines: Sampling dates"))

ggsave(here("figures", "lag_period_test_with_averages.png"),
        width = 16, height = 8, dpi = 300)
```
```{r}
# Prepare sampling dates first to determine date range
sampling_dates <- f %>%
  mutate(year = year(date),
         month = month(date)) %>%
  filter(month == 4, year %in% c(2014, 2015, 2018, 2021, 2022, 2024))

# Create expanded date ranges: 30 days before sampling + rest of sampling month
date_ranges <- sampling_dates %>%
  mutate(
    start_date = date - days(30),
    end_date = ceiling_date(date, "month") - days(1)  # Last day of sampling month
  ) %>%
  select(year, date, start_date, end_date)

# Prepare wind data with expanded date range
wind_plot_data <- wind_calc %>% 
  mutate(wind_date = date(measurementTime),
         year = year(wind_date),
         se_component = (u - v) / sqrt(2)) %>%
  # Filter for years of interest first
  filter(year %in% c(2014, 2015, 2018, 2021, 2022, 2024)) %>%
  # Join with date ranges
  left_join(date_ranges %>% select(year, sampling_date = date, start_date, end_date), 
            by = "year", 
            relationship = "many-to-many") %>%
  # Filter using the renamed columns
  filter(wind_date >= start_date & wind_date <= end_date) %>%
  # Convert to daily averages
  group_by(wind_date, year) %>%
  summarise(
    ws = mean(ws, na.rm = TRUE),
    wd = mean(wd, na.rm = TRUE),
    se_component = mean(se_component, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  # Add month-day for x-axis
  mutate(month_day = format(wind_date, "%m-%d")) %>%
  rename(date = wind_date)

# Calculate 19-day SE-NW component averages for each sampling period
se_averages <- sampling_dates %>%
  mutate(
    period_start = date - days(18),  # 19 days including sampling day
    period_end = date
  ) %>%
  left_join(
    wind_plot_data %>% select(date, year, se_component),
    by = "year",
    relationship = "many-to-many"
  ) %>%
  filter(date.y >= period_start & date.y <= period_end) %>%
  group_by(year, date.x) %>%
  summarise(
    se_avg_19day = mean(se_component, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  rename(date = date.x) %>%
  left_join(sampling_dates, by = c("year", "date"))

# Handle overlapping periods and prepare sampling markers
sampling_markers <- se_averages %>%
  mutate(
    period_start = date - days(18),
    period_end = date,
    month_day = format(date, "%m-%d"),
    period_start_md = format(period_start, "%m-%d"),
    period_end_md = format(period_end, "%m-%d")
  ) %>%
  # Check for overlapping periods within each year and average if needed
  group_by(year) %>%
  arrange(date) %>%
  mutate(
    # Create groups for overlapping periods
    overlap_group = cumsum(c(TRUE, diff(as.numeric(date)) > 18))
  ) %>%
  group_by(year, overlap_group) %>%
  summarise(
    # For overlapping periods, use the mean date and average the SE values
    date = if(n() > 1) as.Date(mean(as.numeric(date)), origin = "1970-01-01") else first(date),
    period_start = min(date) - days(18),
    period_end = max(date),
    se_avg_19day = mean(se_avg_19day, na.rm = TRUE),
    # Use earliest start and latest end for the box
    period_start_md = format(min(date) - days(18), "%m-%d"),
    period_end_md = format(max(date), "%m-%d"),
    month_day = format(if(n() > 1) as.Date(mean(as.numeric(date)), origin = "1970-01-01") else first(date), "%m-%d"),
    n_samples = n(),
    .groups = "drop"
  ) %>%
  mutate(
    # Format the average for display, noting if multiple samples were averaged
    se_avg_label = if_else(n_samples > 1,
                          paste0("19-day SE avg:\n", round(se_avg_19day, 2), " m/s\n(", n_samples, " samples)"),
                          paste0("19-day SE avg:\n", round(se_avg_19day, 2), " m/s")),
    # Add vertical offset for label positioning to prevent overlap
    label_offset = (row_number() - 1) * 0.15  # Stagger labels vertically
  )

# Create the enhanced plot
ggplot() +
  # Add grey boxes for 19-day backward periods
  geom_rect(data = sampling_markers,
            aes(xmin = period_start_md, 
                xmax = period_end_md,
                ymin = -Inf, 
                ymax = Inf),
            fill = "grey80", 
            alpha = 0.6) +
  
  # Wind speed points colored by direction
  geom_point(data = wind_plot_data,
             aes(x = month_day, y = ws, color = wd),
             size = 1.8, alpha = 0.8) +
  
  # SE component line
  geom_line(data = wind_plot_data,
            aes(x = month_day, y = se_component, group = year),
            color = "black", 
            linewidth = 0.9,
            alpha = 0.9) +
  
  # Vertical lines for exact sampling dates
  geom_vline(data = sampling_markers,
             aes(xintercept = month_day),
             color = "red", 
             linewidth = 1.2,
             alpha = 0.8) +
  
  geom_hline(yintercept =  0) +
  
  # Add SE average text labels in grey boxes
  geom_text(data = sampling_markers,
            aes(x = period_start_md, 
                y = Inf,
                label = se_avg_label),
            hjust = 0, 
            vjust = 1.1,
            size = 3.5,
            color = "darkblue",
            fontface = "bold",
            background = "white") +
  
  # Color scale for wind direction
  scale_color_viridis_c(option = "turbo", 
                        name = "Wind Direction\n(degrees)",
                        guide = guide_colorbar(barwidth = 1, 
                                              barheight = 8)) +
  
  # X-axis with better date formatting
  scale_x_discrete(name = "Date (Month-Day)",
                   breaks = function(x) {
                     # Show every 5th date for readability
                     indices <- seq(1, length(x), by = 5)
                     return(x[indices])
                   }) +
  
  scale_y_continuous(name = bquote("Wind Speed"~(m~s^-1)~"/ SE Component"),
                     expand = expansion(mult = c(0.1, 0.05))) +  # Extra space at top for labels
  
  # Faceting by year
  facet_wrap(~ year, 
             labeller = label_both,
             scales = "free_x") +
  
  # Theme
  theme_bw() +
  theme(
    panel.grid.minor.x = element_line(color = "grey95", size = 0.3),
    panel.grid.major = element_line(color = "grey90", size = 0.5),
    text = element_text(size = 12),
    strip.text = element_text(size = 14, face = "bold"),
    axis.text = element_text(color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
    legend.position = "right",
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12, color = "grey30")
  ) +
  
  # Labels and title
  labs(title = "Extended Wind Patterns Around April Sampling",
       subtitle = "30 days before sampling + remainder of sampling month\nSE Component (black line) vs Wind Speed (colored points) - Daily averages",
       caption = paste("Grey boxes: 19-day backward averaging periods with SE-NW component averages | Red lines: Sampling dates"))

ggsave(here("figures", "lag_period_test_with_averages2.png"),
        width = 16, height = 8, dpi = 300)
```
```{r}
# Prepare sampling dates first to determine date range
sampling_dates <- f %>%
  mutate(year = year(date),
         month = month(date)) %>%
  filter(month == 4, year %in% c(2014, 2015, 2018, 2021, 2022, 2024))

# Create expanded date ranges: 30 days before sampling + rest of sampling month
date_ranges <- sampling_dates %>%
  mutate(
    start_date = date - days(30),
    end_date = ceiling_date(date, "month") - days(1)  # Last day of sampling month
  ) %>%
  select(year, date, start_date, end_date)

# Prepare wind data with expanded date range
wind_plot_data <- wind_calc %>% 
  mutate(wind_date = date(measurementTime),
         year = year(wind_date),
         se_component = (u - v) / sqrt(2)) %>%
  # Filter for years of interest first
  filter(year %in% c(2014, 2015, 2018, 2021, 2022, 2024)) %>%
  # Join with date ranges
  left_join(date_ranges %>% select(year, sampling_date = date, start_date, end_date), 
            by = "year", 
            relationship = "many-to-many") %>%
  # Filter using the renamed columns
  filter(wind_date >= start_date & wind_date <= end_date) %>%
  # Convert to daily averages
  group_by(wind_date, year) %>%
  summarise(
    ws = mean(ws, na.rm = TRUE),
    wd = mean(wd, na.rm = TRUE),
    se_component = mean(se_component, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  # Add month-day for x-axis
  mutate(month_day = format(wind_date, "%m-%d")) %>%
  rename(date = wind_date)

# Calculate 19-day SE-NW component averages for each sampling period
se_averages <- sampling_dates %>%
  mutate(
    period_start = date - days(18),  # 19 days including sampling day
    period_end = date
  ) %>%
  left_join(
    wind_plot_data %>% select(date, year, se_component),
    by = "year",
    relationship = "many-to-many"
  ) %>%
  filter(date.y >= period_start & date.y <= period_end) %>%
  group_by(year, date.x) %>%
  summarise(
    se_avg_19day = mean(se_component, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  rename(date = date.x) %>%
  left_join(sampling_dates, by = c("year", "date"))

# Handle overlapping periods and prepare sampling markers
sampling_markers <- se_averages %>%
  mutate(
    period_start = date - days(18),
    period_end = date,
    month_day = format(date, "%m-%d"),
    period_start_md = format(period_start, "%m-%d"),
    period_end_md = format(period_end, "%m-%d")
  ) %>%
  # Check for overlapping periods within each year and average if needed
  group_by(year) %>%
  arrange(date) %>%
  mutate(
    # Create groups for overlapping periods
    overlap_group = cumsum(c(TRUE, diff(as.numeric(date)) > 18))
  ) %>%
  group_by(year, overlap_group) %>%
  summarise(
    # For overlapping periods, use the mean date and average the SE values
    date = if(n() > 1) as.Date(mean(as.numeric(date)), origin = "1970-01-01") else first(date),
    period_start = min(date) - days(18),
    period_end = max(date),
    se_avg_19day = mean(se_avg_19day, na.rm = TRUE),
    # Use earliest start and latest end for the box
    period_start_md = format(min(date) - days(18), "%m-%d"),
    period_end_md = format(max(date), "%m-%d"),
    month_day = format(if(n() > 1) as.Date(mean(as.numeric(date)), origin = "1970-01-01") else first(date), "%m-%d"),
    n_samples = n(),
    .groups = "drop"
  ) %>%
  mutate(
    # Format the average for display, noting if multiple samples were averaged
    se_avg_label = if_else(n_samples > 1,
                          paste0("19-day SE avg:\n", round(se_avg_19day, 2), " m/s\n(", n_samples, " samples)"),
                          paste0("19-day SE avg:\n", round(se_avg_19day, 2), " m/s")),
    # Add vertical offset for label positioning to prevent overlap
    label_offset = (row_number() - 1) * 0.15  # Stagger labels vertically
  )

# Create the enhanced plot
ggplot() +
  # Add grey boxes for 19-day backward periods
  geom_rect(data = sampling_markers,
            aes(xmin = period_start_md, 
                xmax = period_end_md,
                ymin = -Inf, 
                ymax = Inf),
            fill = "grey80", 
            alpha = 0.6) +
  
  # SE component line
  geom_line(data = wind_plot_data,
            aes(x = month_day, y = se_component, group = year),
            color = "black", 
            linewidth = 0.9,
            alpha = 0.9) +
  
  # SE component points colored by wind speed
  geom_point(data = wind_plot_data,
             aes(x = month_day, y = se_component, color = ws),
             size = 2.2, alpha = 0.8) +
  
  # Vertical lines for exact sampling dates
  geom_vline(data = sampling_markers,
             aes(xintercept = month_day),
             color = "red", 
             linewidth = 1.2,
             alpha = 0.8) +
  
  geom_hline(yintercept = 0) +
  
  # Add SE average text labels in grey boxes with offset positioning
  geom_text(data = sampling_markers,
            aes(x = period_start_md, 
                y = Inf,
                label = se_avg_label),
            hjust = 0, 
            vjust = 1.1 + sampling_markers$label_offset,  # Use offset to prevent overlap
            size = 3.5,
            color = "darkblue",
            fontface = "bold") +
  
  # Color scale for wind speed
  scale_color_viridis_c(option = "plasma", 
                        name = "Wind Speed\n(m/s)",
                        guide = guide_colorbar(barwidth = 1, 
                                              barheight = 8)) +
  
  # X-axis with better date formatting
  scale_x_discrete(name = "Date (Month-Day)",
                   breaks = function(x) {
                     # Show every 5th date for readability
                     indices <- seq(1, length(x), by = 5)
                     return(x[indices])
                   }) +
  
  scale_y_continuous(name = "SE-NW Wind Component (m/s)",
                     expand = expansion(mult = c(0.1, 0.05))) +  # Extra space at top for labels
  
  # Faceting by year
  facet_wrap(~ year, 
             labeller = label_both,
             scales = "free_x") +
  
  # Theme
  theme_bw() +
  theme(
    panel.grid.minor.x = element_line(color = "grey95", size = 0.3),
    panel.grid.major = element_line(color = "grey90", size = 0.5),
    text = element_text(size = 12),
    strip.text = element_text(size = 14, face = "bold"),
    axis.text = element_text(color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
    legend.position = "right",
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12, color = "grey30")
  ) +
  
  # Labels and title
  labs(title = "SE-NW Wind Component Around April Sampling",
       subtitle = "30 days before sampling + remainder of sampling month\nSE Component line with points colored by wind speed - Daily averages",
       caption = paste("Grey boxes: 19-day backward averaging periods with SE-NW component averages | Red lines: Sampling dates"))

ggsave(here("figures", "lag_period_test_with_averages3.png"),
        width = 16, height = 8, dpi = 300)
```


```{r}
# Alternative version using hourly data instead of daily averages
create_hourly_plot <- function(years_to_plot = c(2015, 2021)) {
  
  # Get sampling dates and ranges
  samp_dates <- f %>%
    mutate(year = year(date), month = month(date)) %>%
    filter(month == 4, year %in% years_to_plot)
  
  date_ranges <- samp_dates %>%
    mutate(
      start_date = date - days(30),
      end_date = ceiling_date(date, "month") - days(1)
    ) %>%
    select(year, date, start_date, end_date)
  
  # Hourly wind data
  wind_hourly <- wind_calc %>% 
    mutate(wind_date = date(measurementTime),
           datetime = measurementTime,
           year = year(wind_date),
           se_component = (u - v) / sqrt(2)) %>%
    filter(year %in% years_to_plot) %>%
    left_join(date_ranges %>% select(year, sampling_date = date, start_date, end_date), 
              by = "year", 
              relationship = "many-to-many") %>%
    filter(wind_date >= start_date & wind_date <= end_date) %>%
    select(-sampling_date, -start_date, -end_date) %>%
    rename(date = wind_date)
  
  # Sampling markers
  samp_markers <- samp_dates %>%
    mutate(
      period_start = date - days(18),
      period_end = date,
      month_day = format(date, "%m-%d")
    )
  
  ggplot() +
    # Grey boxes for 19-day periods
    geom_rect(data = samp_markers,
              aes(xmin = as.POSIXct(period_start), 
                  xmax = as.POSIXct(period_end),
                  ymin = -Inf, ymax = Inf),
              fill = "grey80", alpha = 0.6) +
    
    # Hourly wind data
    geom_point(data = wind_hourly,
               aes(x = datetime, y = ws, color = wd),
               size = 0.8, alpha = 0.6) +
    
    geom_line(data = wind_hourly,
              aes(x = datetime, y = se_component, group = year),
              color = "black", linewidth = 0.5, alpha = 0.8) +
    
    # Sampling dates
    geom_vline(data = samp_markers,
               aes(xintercept = as.POSIXct(date)),
               color = "red", linewidth = 1.2) +
    
    geom_hline(yintercept = 0, color = "black", linewidth = 1) +
    
    scale_color_viridis_c(option = "turbo", name = "Wind Direction\n(degrees)") +
    scale_x_datetime(name = "Date", date_labels = "%m-%d", date_breaks = "5 days") +
    scale_y_continuous(name = bquote("Wind Speed"~(m~s^-1)~"/ SE Component")) +
    
    facet_grid(. ~ year, labeller = label_both, scales = "free_x") +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      strip.text = element_text(size = 14, face = "bold"),
      text = element_text(size = 12),
      legend.position = "right"
    ) +
    labs(title = "Hourly Wind Patterns Around April Sampling",
         subtitle = "30 days before + remainder of sampling month",
         caption = "Grey boxes: 19-day backward averaging periods | Red lines: Sampling dates")
}

# Usage:
# Main plot uses daily averages (shown above)
# For hourly data: 
create_hourly_plot(c(2017, 2021))
```





```{r}
wind_calc %>% 
  mutate(month = month(measurementTime),
         year = year(measurementTime)) %>% 
  filter(month == 4) %>% 
  ggplot(aes(x = as.factor(year), y = se_component)) +
  geom_boxplot()
```



















```{r}
wind_calc_dm <- wind_calc %>% 
  mutate(date = date(measurementTime)) %>% 
  group_by(date) %>% 
  summarise(u_dm = mean(u),
            v_dm = mean(v)) %>% 
  ungroup()

buoy_join <- buoy %>% 
  left_join(wind_calc_dm) %>% 
  mutate(year = year(date),
         month = month(date))

buoy_join %>%
  filter(year == 2022) %>% 
  filter(month == 4) %>% 
  ggplot(aes(x = fl_med_day, y = lag(u_dm, 19))) +
  geom_point()
  
```














```{r}
# Eastward wind specific thresholds and variability
eastward_metrics <- f %>% 
  mutate(month = month(date)) %>% 
  filter(month == 4) %>%
  filter(pres <= 30) %>% 
  group_by(date) %>% 
  summarise(int = sum(f_npq)) %>% 
  ungroup() %>%
  rowwise() %>%
  do({
    sample_date <- .$date
    start_date <- sample_date - days(19)
    end_date <- sample_date - days(1)
    
    period_wind <- wind_calc %>%
      filter(measurementTime >= start_date & measurementTime <= end_date) %>%
      mutate(mean_se <- mean(period_wind$se_component, na.rm = TRUE))
    
    if(nrow(period_wind) > 0) {
      data.frame(
        date = sample_date,
        int = .$int,
        # Eastward wind thresholds
        strong_eastward_hours = sum(period_wind$mean_se > 3, na.rm = TRUE),  # Hours with u > 1 m/s
        max_eastward = max(period_wind$mean_se, na.rm = TRUE),
        # Eastward wind events (consecutive periods)
        eastward_event_intensity = mean(period_wind$mean_se[period_wind$mean_se > 0], na.rm = TRUE),
        # Mixed metric
        eastward_power = mean(pmax(period_wind$mean_se, 0)^3, na.rm = TRUE)  # Cube only positive u
      )
    }
  })
```


```{r}
# Calculate SE wind component specifically
wind_data <- wind %>%
  select(measurementTime = measurementTime2,
         ws = WindSpd_Avg,
         wd = WindDir_Avg) %>% 
  mutate(
    # SE wind component (southeast = 135°)
    se_component = -ws * cos((wd - 135) * pi/180)
  )

# Recalculate lag analysis with SE component
se_wind_lag <- f %>% 
  mutate(month = month(date)) %>% 
  filter(month == 4) %>% 
  filter(pres <= 30) %>% 
  group_by(date) %>% 
  summarise(int = sum(f_npq)) %>%
  rowwise() %>%
  do({
    sample_date <- .$date
    start_date <- sample_date - days(19)
    end_date <- sample_date - days(0)
    
    period_wind <- wind_data %>%
      filter(measurementTime >= start_date & measurementTime <= end_date)
    
    if(nrow(period_wind) > 0) {
      data.frame(
        date = sample_date,
        int = .$int,
        mean_se_component = mean(period_wind$se_component, na.rm = TRUE),
        se_hours = sum(period_wind$se_component > 1, na.rm = TRUE)  # Hours of strong SE winds
      )
    }
  })
```

```{r}
se_wind_lag %>%
 mutate(year = year(date)) %>%
 select(int, mean_se_component, se_hours, year) %>%
 pivot_longer(cols = -c(int, year), names_to = "se_wind_param", values_to = "se_wind_value") %>%
 filter(!is.na(se_wind_value)) %>%
 ggplot(aes(x = se_wind_value, y = int)) +
 geom_point(aes(color = as.factor(year)), size = 2.5, alpha = 0.8) +
 geom_smooth(method = "lm", se = TRUE, alpha = 0.2, color = "black", linewidth = 0.8) +
 stat_cor(method = "pearson", 
          label.x.npc = "left", 
          label.y.npc = "top",
          size = 3.5,
          label.sep = ", ") +
 scale_color_brewer(type = "qual", palette = "Set1") +
 facet_wrap(~se_wind_param, scales = "free", 
            labeller = labeller(se_wind_param = c(
              "mean_se_component" = "Mean SE wind component",
              "se_hours" = "Hours of strong SE winds"))) +
 theme_minimal() +
 theme(
   panel.grid.minor = element_blank(),
   strip.text = element_text(size = 11, face = "bold"),
   axis.text = element_text(color = "black"),
   legend.position = "bottom",
   legend.title = element_blank()
 ) +
 labs(x = bquote("SE wind metrics"~(m~s^-1)), 
      y = bquote("Integrated fluorescence"~(mg~m^-2))) +
 guides(color = guide_legend(nrow = 1, override.aes = list(size = 3)))
```



```{r}
# Calculate discharge metrics similar to wind
discharge_lag <- f %>% 
  mutate(month = month(date)) %>% 
  filter(month == 4) %>% 
  filter(pres <= 30) %>% 
  group_by(date) %>% 
  summarise(int = sum(f_npq)) %>% 
  ungroup() %>%
  rowwise() %>%
  do({
    sample_date <- .$date
    start_date <- sample_date - days(15)
    end_date <- sample_date - days(1)
    
    period_discharge <- weath %>%
      select(date, discharge = Q_Total) %>% 
      filter(date >= start_date & date <= end_date)
    
    if(nrow(period_discharge) > 0) {
      data.frame(
        date = sample_date,
        int = .$int,
        mean_discharge_lag = mean(period_discharge$discharge, na.rm = TRUE),
        max_discharge_lag = max(period_discharge$discharge, na.rm = TRUE),
        discharge_variability = sd(period_discharge$discharge, na.rm = TRUE),
        high_flow_days = sum(period_discharge$discharge > quantile(weath$Q_Total, 0.75, na.rm = TRUE), na.rm = TRUE),
        # Freshet-specific metrics
        peak_flow = max(period_discharge$discharge, na.rm = TRUE),
        flow_trend = coef(lm(discharge ~ seq_along(discharge), data = period_discharge))[2]  # increasing/decreasing
      )
    }
  })
```

```{r}
discharge_lag %>%
 mutate(year = year(date)) %>%
 select(int, mean_discharge_lag, max_discharge_lag, discharge_variability, high_flow_days, peak_flow, year) %>%
 pivot_longer(cols = -c(int, year), names_to = "discharge_param", values_to = "discharge_value") %>%
 filter(!is.na(discharge_value)) %>%
 ggplot(aes(x = discharge_value, y = int)) +
 geom_point(aes(color = as.factor(year)), size = 2.5, alpha = 0.8) +
 geom_smooth(method = "lm", se = TRUE, alpha = 0.2, color = "black", linewidth = 0.8) +
 stat_cor(method = "pearson", 
          label.x.npc = "left", 
          label.y.npc = "top",
          size = 3.5,
          label.sep = ", ") +
 scale_color_brewer(type = "qual", palette = "Set1") +
 facet_wrap(~discharge_param, scales = "free", 
            labeller = labeller(discharge_param = c(
              "mean_discharge_lag" = "Mean discharge",
              "max_discharge_lag" = "Max discharge",
              "discharge_variability" = "Discharge variability",
              "high_flow_days" = "High flow days",
              "peak_flow" = "Peak flow"))) +
 theme_minimal() +
 theme(
   panel.grid.minor = element_blank(),
   strip.text = element_text(size = 11, face = "bold"),
   axis.text = element_text(color = "black"),
   legend.position = "bottom",
   legend.title = element_blank()
 ) +
 labs(x = "Discharge metrics (30 days prior)", 
      y = bquote("Integrated fluorescence"~(mg~m^-2))) +
 guides(color = guide_legend(nrow = 1, override.aes = list(size = 3)))
```

```{r}
# Calculate temperature metrics similar to your wind analysis
temp_lag <- f %>% 
  mutate(month = month(date)) %>% 
  filter(month == 4) %>% 
  filter(pres <= 30) %>% 
  group_by(date) %>% 
  summarise(int = sum(f_npq)) %>% 
  ungroup() %>%
  rowwise() %>%
  do({
    sample_date <- .$date
    start_date <- sample_date - days(15)
    end_date <- sample_date - days(1)
    
    period_temp <- wind %>%  # assuming you have air temp data
      select(measurementTime = measurementTime2,
             air_temp = AirTemp_Avg) %>% 
      filter(measurementTime >= start_date & measurementTime <= end_date)
    
    if(nrow(period_temp) > 0) {
      data.frame(
        date = sample_date,
        int = .$int,
        mean_temp_lag = mean(period_temp$air_temp, na.rm = TRUE),
        temp_variability = sd(period_temp$air_temp, na.rm = TRUE),
        heating_days = sum(period_temp$air_temp > 18, na.rm = TRUE),  # adjust threshold
        temp_trend = coef(lm(air_temp ~ seq_along(air_temp), data = period_temp))[2]  # warming/cooling trend
      )
    }
  })

# Combined wind-temperature analysis
combined_data <- wind_lag_vectors %>%
  left_join(temp_lag, by = c("date", "int"))

# Plot relationships
combined_data %>%
  select(int, mean_u_lag, mean_temp_lag, temp_variability, heating_days) %>%
  pivot_longer(cols = -int, names_to = "parameter", values_to = "value") %>%
  filter(!is.na(value)) %>%
  ggplot(aes(x = value, y = int)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = TRUE) +
  stat_cor() +
  facet_wrap(~parameter, scales = "free")
```
```{r}
# Join all your environmental drivers
full_environmental <- wind_lag_vectors %>%
  left_join(discharge_lag, by = c("date", "int")) %>%
  left_join(temp_lag, by = c("date", "int"))  # if you add temperature

# Multiple regression to see relative importance
model <- lm(int ~ mean_u_lag + mean_discharge_lag + mean_temp_lag, data = full_environmental)
summary(model)

# Plot all relationships
full_environmental %>%
  select(int, mean_u_lag, mean_discharge_lag, max_discharge_lag, high_flow_days) %>%
  pivot_longer(cols = -int, names_to = "parameter", values_to = "value") %>%
  filter(!is.na(value)) %>%
  ggplot(aes(x = value, y = int)) +
  geom_point(, size = 2) +
  geom_smooth(method = "lm", se = TRUE) +
  stat_cor() +
  facet_wrap(~parameter, scales = "free")
```





```{r}
# Join all your environmental drivers
full_environmental <- wind_lag_vectors %>%
  left_join(discharge_lag, by = c("date", "int"))
  # left_join(temp_lag, by = c("date", "int"))  # if you add temperature

# Multiple regression to see relative importance
model <- lm(int ~ mean_u_lag + mean_discharge_lag, data = full_environmental)
summary(model)

# Plot all relationships
full_environmental %>%
  select(int, mean_u_lag, mean_discharge_lag, max_discharge_lag, high_flow_days) %>%
  pivot_longer(cols = -int, names_to = "parameter", values_to = "value") %>%
  filter(!is.na(value)) %>%
  ggplot(aes(x = value, y = int)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = TRUE) +
  stat_cor() +
  facet_wrap(~parameter, scales = "free")
```




```{r}
#Let's create some salinity, temperature and nutrient panels similar to panel 3 starting with 2022

#Ok, now it would be interesting to pull out 
ctd_july_2024 <- ctd_less %>% 
  filter(year == 2024 & month == 7) %>% 
  group_by(cast_pk) %>% 
  mutate(max_pres = max(pres), groups = "drop") %>%
  filter(max_pres >= 50) %>% 
  distinct(station, date, ctd_num)
```


```{r}
# Create the presentation-ready CTD profiles plot
profiles_2024 <- ctd_less %>% 
  filter(cast_pk %in% ctd_july_2024$cast_pk) %>% 
  filter(pres <= 20) %>% 
  ggplot(aes(x = f, y = pres, color = temp)) +
  geom_line(
    orientation = "y",
    linewidth = 2,
    alpha = 0.8
  ) +
  geom_point(
    size = 3,
    alpha = 0.9
  ) +
  scale_y_reverse(
    name = "Pressure (dbar)",
    expand = expansion(mult = c(0.02, 0.05))
  ) +
  scale_x_continuous(
    name = "Fluorescence (µg/L)",
    expand = expansion(mult = c(0.02, 0.05))
  ) +
  scale_color_viridis_c(
    option = "turbo",
    name = "Temperature\n(°C)",
    guide = guide_colorbar(
      barwidth = 1,
      barheight = 8,
      title.position = "top",
      title.hjust = 0.5
    )
  ) +
  facet_wrap(
    ~station,
    ncol = 4,
    # scales = "free_x"
  ) +
  labs(
    title = "CTD Profiles by Station",
    subtitle = "Temperature-colored fluorescence profiles, July 2024 (0-20 dbar)",
    caption = "Each line represents a single cast; warmer colors indicate higher temperatures"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    # Improve title formatting
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 14, hjust = 0.5, color = "gray40"),
    plot.caption = element_text(size = 12, color = "gray50", hjust = 0.5),
    
    # Improve facet labels
    strip.text = element_text(size = 13, face = "bold", color = "gray20"),
    strip.background = element_rect(fill = "gray95", color = NA),
    
    # Improve axis labels
    axis.title = element_text(size = 16, face = "bold"),
    axis.text = element_text(size = 14),
    
    # Improve legend
    legend.title = element_text(size = 13, face = "bold"),
    legend.text = element_text(size = 12),
    legend.position = "right",
    legend.margin = margin(l = 10),
    
    # Clean grid
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "gray95", linewidth = 0.5),
    
    # Clean background
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    
    # Add some spacing between facets
    panel.spacing = unit(0.8, "lines")
  )

ggsave(
  here("figures", "ctd_profiles_july2024.png"),
  profiles_2024,
  width = 12,
  height = 14,
  dpi = 300,
  bg = "white"
)
```

```{r}
station_colors <- c(
  "BUR1" = "#E31A1C",    # Red
  "FC1" = "#1F78B4",     # Blue
  "FZH01" = "#33A02C",   # Green
  "FZH04" = "#FF7F00",   # Orange
  "FZH08" = "#6A3D9A",   # Purple
  "FZH13" = "#A6CEE3",   # Light blue
  "KC10" = "#B2DF8A",    # Light green
  "KFPS07" = "#FB9A99",  # Pink
  "PRUTH" = "#FDBF6F",   # Light orange
  "QCS07" = "#CAB2D6",   # Light purple
  "QSD01" = "#FFFF99",   # Yellow
  "RVRS01" = "#B15928",  # Brown
  "UBC7" = "#000000"     # Black
)
```

```{r}
# Create the presentation-ready plot
scatter_f_temp_july_2024 <- ctd_less %>% 
  filter(cast_pk %in% ctd_july_2024$cast_pk) %>% 
  filter(pres <= 30) %>% 
  ggplot(aes(x = f, y = temp, color = station)) +
  # Add points with black outline for KC10 station
  geom_point(
    data = . %>% filter(station == "KC10"),
    size = 3.5, 
    color = "black", 
    shape = 21,
    stroke = 1.5
  ) +
  geom_point(
    data = . %>% filter(station == "KC10"),
    size = 3, 
    shape = 21,
    stroke = 0
  ) +
  # Add all other points
  geom_point(
    # data = . %>% filter(station != "KC10"),
    size = 3,
    alpha = 0.8
  ) +
  # Use your custom color palette
  scale_color_manual(values = station_colors) +
  # Improve labels and formatting
  labs(
    title = "Temperature vs Fluorescence by Station",
    subtitle = "July 2024 CTD Data (≤30 dbar)",
    x = "Fluorescence (µg/L)",
    y = "Temperature (°C)",
    color = "Station",
  ) +
  # Use a clean theme
  theme_minimal(base_size = 14) +
  theme(
    # Improve title formatting
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 14, hjust = 0.5, color = "gray40"),
    plot.caption = element_text(size = 10, color = "gray50"),
    
    # Improve legend
    legend.title = element_text(size = 14, face = "bold"),
    legend.text = element_text(size = 12),
    legend.position = "right",
    legend.key.size = unit(1.2, "lines"),
    
    # Improve axis labels
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 12),
    
    # Add subtle grid
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "gray95", size = 0.5),
    
    # Clean background
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA)
  ) +
  # Add some padding around the plot
  scale_x_continuous(expand = expansion(mult = 0.05)) +
  scale_y_continuous(expand = expansion(mult = 0.05))

print(scatter_f_temp_july_2024)

ggsave(
  here("figures", "scatter_f_temp_july_2024.png"),
  scatter_f_temp_july_2024,
  width = 8,
  height = 6,
  dpi = 300,
  bg = "white"
)
```


```{r}
ctd_2022_dates <- ctd_less %>% 
  filter(year == 2022 & month %in% c(7)) %>% 
  distinct(date, station)

ctd_2022 <- ctd_less %>% 
  filter(month == 7) %>% 
  # filter(date >= "2022-07-27" & date < "2022-08-01") %>%
  filter(!cast_pk == 19273) %>% 
  group_by(cast_pk) %>% 
  mutate(max_pres = max(pres), groups = "drop") %>%
  filter(max_pres >= 50) %>% 
  distinct(station, date, ctd_num)
```

```{r}
test <- ctd_less %>% 
  filter(cast_pk %in% ctd_2022$cast_pk) %>% 
  filter(pres <= 30)

ctd_less %>% 
  filter(cast_pk %in% ctd_2022$cast_pk) %>% 
  filter(pres <= 30) %>% 
  ggplot(aes(x = f, y = temp, color = pres)) +
  # Add points with black outline for KC10 station
  geom_point(
    data = . %>% filter(station == "KC10"),
    size = 3, 
    shape = 21,
    stroke = 0
  ) +
  # Add all other points
  geom_point(
    # data = . %>% filter(station != "KC10"),
    size = 3,
    alpha = 0.8,
  ) +
    geom_point(
    data = . %>% filter(station == "KC10"),
    size = 3.5, 
    color = "black", 
    shape = 21,
    stroke = 1.5
  ) +
  # Use your custom color palette
  # scale_color_manual(values = station_colors) +
  scale_color_viridis_c() +
  # Improve labels and formatting
  labs(
    title = "Temperature vs Fluorescence by Station",
    subtitle = "July 2022 CTD Data (≤30 dbar)",
    x = "Fluorescence (µg/L)",
    y = "Temperature (°C)",
    color = "Station",
    caption = "Data from surface to 30m depth"
  ) +
  # Use a clean theme
  theme_minimal(base_size = 14) +
  theme(
    # Improve title formatting
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 14, hjust = 0.5, color = "gray40"),
    plot.caption = element_text(size = 10, color = "gray50"),
    
    # Improve legend
    legend.title = element_text(size = 14, face = "bold"),
    legend.text = element_text(size = 12),
    legend.position = "right",
    legend.key.size = unit(1.2, "lines"),
    
    # Improve axis labels
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 12),
    
    # Add subtle grid
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "gray95", size = 0.5),
    
    # Clean background
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA)
  ) +
  # Add some padding around the plot
  scale_x_continuous(expand = expansion(mult = 0.05)) +
  scale_y_continuous(expand = expansion(mult = 0.05))


```

```{r}
#Are these huge concentrations real????
ctd_less %>% 
  filter(cast_pk == "27207") %>% 
  filter(pres <= 50) %>% 
  ggplot(aes(x = f, y = pres, color = station)) +
  geom_line(orientation = "y", size = 3) +
  scale_y_reverse()
```

