---
title: "R Notebook"
output: html_notebook
---

Some new interpolation tutorials to consider:
https://search.r-project.org/CRAN/refmans/rioja/html/interp.dataset.html
https://github.com/hdugan/NTLlakeloads

```{r}
#Upload packages
library(tidyverse)
library(here)
library(readxl)
library(patchwork)
library(lubridate)
library(MBA)
library(mgcv)
library(FNN)
library(zoo)
library(reshape2)
library(rioja)
library(egg)
library(palr)
library(ggsci)

```

```{r}
# 2024 corrected buoy data
b22 <- read.csv(here("outputs", "buoy_corr_dm_2022.csv"))
b24 <- read.csv(here("outputs", "buoy_corr_dm_2024.csv"))

bsal <- read.csv(here("files", "buoy_ts_all.csv"))

#Corrected CTD data
f <- read_csv(here("outputs", "corrected_flu_2025-05-09.csv"))

fm <- read_csv(here("files", "flu_2022-03-09.csv"))


#Downloading discrete chlorophyll samples
cd <- read_csv(here("files", "2024-12-05_HakaiData_chlorophyll.csv"))

cm <- read_csv(here("files", "chl_2022-03-09.csv")) 
cs <- read_csv(here("files", "chl_2022-09-09.csv")) 
  
wind <- read_csv(here("files", "wind_all.csv"))

wind_anom <- read.csv(here("outputs", "wind_anom_day_2025-04-25.csv"))

#CHEMTAX
chem <- read_csv(here("files", "chemtax_kc10_2024.csv"))

weath <- read_csv(here("outputs", "enviro_weather_2025-04-14.csv"))

up <- read_csv(here("files_big", "up_2025-04-24.csv"))

```

```{r}
f %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(pres < 51 & station == "KC10" & year > 2016) %>% 
  ggplot(aes(x = f_npq, y = pres)) +
  geom_line(orientation = "y") +
  scale_y_reverse() +
  facet_wrap(~id)

ggsave(here("figures", "profiles.png"),
        width = 24, height = 24, dpi = 300)
```






```{r}
q <- weath %>% 
  select(date, Q_GM, Q_SM, Q_RA) %>% 
  pivot_longer(c(Q_GM:Q_RA), names_to = "Watershed_group", values_to = "Q") %>% 
  drop_na() %>% 
  group_by(date) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  mutate(year = year(date))
```



```{r}
b22 <- b22 %>% 
  select(date_corr, fl_med_day) %>% 
  distinct()

b24 <- b24 %>% 
  select(date_corr, fl_med_day) %>% 
  distinct()

bsal2 <- bsal %>% 
  mutate(measurementTime = mdy_hm(measurementTime),
         date = date(measurementTime)) %>% 
  filter(WaterSalinity_UQL == 2 & (year == 2022 | year == 2024)) %>% 
  group_by(date) %>% 
  summarise(mean_sal = mean(WaterSalinity)) %>% 
  ungroup()

btemp <- bsal %>% 
  mutate(measurementTime = mdy_hm(measurementTime),
         date = date(measurementTime)) %>% 
  filter(WaterTemp_UQL == 2 & (year == 2022 | year == 2024)) %>% 
  group_by(date) %>% 
  summarise(mean_temp = mean(WaterTemp)) %>% 
  ungroup()

bsal2 <- bsal2 %>% 
  left_join(btemp)

f22 <- f %>% 
  mutate(year = year(date)) %>% 
  filter(year == 2022)

wind <- wind %>% 
  mutate(date = mdy(date))

wind22 <- wind %>% 
  filter(year == 2022)

wind24 <- wind %>% 
  filter(year == 2024)
```

```{r}
cd <- cd %>% 
  filter(filter_type == "Bulk GF/F" & line_out_depth == 0) %>% 
  select(date, chla) %>% 
  mutate(chla = case_when(date == "2022-05-05" ~ 1.41,
                          TRUE ~ as.numeric(chla)))

cm <- cm %>% 
  filter(filter_type == "Bulk GF/F") %>% 
  select(date, pres = line_out_depth, chla) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))

cs <- cs %>% 
  filter(filter_type == "Bulk GF/F") %>% 
  select(date, pres = line_out_depth, chla) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))

c2 <- rbind(cm, cs)

c2_wide <- c2 %>% 
  pivot_wider(names_from = "date", values_from = "chla")
```

```{r}
# fm <- fm %>% 
#   select(pres = `Pressure (dbar)`, flu = `Fluorometry Chlorophyll (ug/L)`)
# 
# fmc <- fm %>% 
#   left_join(cm) 
```
```{r}
#lets just interpolate the chlorophyll bottle data rather than "fix" the fluorometer
spec <- c2_wide %>% 
  select(2:3)

# spec <- as.data.frame(chl_mm_wide$chl_dm)
depth <- c2_wide$pres

# interpolate new dataset to every 0.5 cm
# using default method (linear)
x.new <- seq(1, 101, by = 1)
sp.interp <- interp.dataset(y = spec, x = depth, xout = x.new,
                               method = "loess", span = 0.5)

interp <- as.data.frame(sp.interp)

interp <- interp %>% 
  mutate(pres = x.new) %>% 
  pivot_longer(cols = (1:2), names_to = "date", values_to = "f_npq") %>% 
  # mutate(date = date(date)) %>% 
  mutate_at(vars(f_npq), funs(round(., 2))) %>% 
  # mutate(date = as.Date("2022-03-09")) %>% 
  select(date, pres, f_npq) %>% 
  mutate(date = date(date))
```



```{r}
b22 <- b22 %>% 
  mutate(date = lubridate::ymd(date_corr),
         year = lubridate::year(date),
         yday = lubridate::yday(date)) 

b22 <- b22 %>% 
  left_join(cd) %>% 
  left_join(bsal2)

b24 <- b24 %>% 
  mutate(date = lubridate::ymd(date_corr),
         year = lubridate::year(date),
         yday = lubridate::yday(date)) 

b24 <- b24 %>% 
  left_join(cd) %>% 
  left_join(bsal2)
```



```{r}
#Working with chemtax data to make it easy to plot

#Making the date column a date format
chem <- chem %>% 
  mutate(date2 = lubridate::mdy(Date)) 

#Selecting appropriate columns and renaming to easy to work with names
chem <- chem %>%
  select(date = date2, cyan = Cyanobacteria, hapt = Hapto, 
         GA = `Prasinophytes-3`, cryp = Cryptophytes,
         dino = `Dinoflagellates-1`, raph = Raphido,
         dict = Dictyo, diat = `Diatoms-1`)

#Pivoting to long/tidy for plotting in ggplot
chem <- chem %>% 
  pivot_longer(c(cyan:diat), names_to = "group", values_to = "contribution")

#Calculating TChla for each sample
chem_tchla <- chem %>% 
  group_by(date, group) %>% 
  summarise(contribution = mean(contribution)) %>% 
  ungroup() %>% 
  group_by(date) %>% 
  mutate(tchla = sum(contribution)) %>% 
  ungroup()


#checking to see if there are any duplicates - there were replicates taken for DFO comparisons. None found because I already averaged these for the manuscript.
chem_dup <- chem_tchla %>%
  distinct(date, tchla) %>% 
  group_by(date) %>% 
  mutate(dup = n()) %>% 
  ungroup() %>% 
  filter(dup > 1)

#Good to move forward
```



```{r}
# f1 <- wind24 %>% 
#   ggplot(aes(x = date, y = WindSpd_Med^3, color = as.factor(year))) +
#   geom_line(size = 2) +
#   ggsci::scale_color_futurama() +
#   scale_x_date(limits = as_date(c("2024-01-01", "2024-12-31")),
#                expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
#   labs(y = bquote(Wind~"("*m^-3*")")) +
#   theme_bw() +
#   theme(legend.position = "none",
#         text = element_text(size = 35), #35
#         axis.text = element_text(color = "black"),
#         axis.title.x = element_blank(),
#         axis.text.x = element_blank())
```


```{r}
# f1 <- 
  
f1_22 <-   ggplot() + 
  geom_line(data = wind22, aes(x = date, y = WindSpd_Med^3),
            size = 2) +
  ylim(0, 6000) +
  labs(y = bquote(Wind~"("*m^-3*s^-3*")")) +
  scale_x_date(limits = as_date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```

```{r}
# f1 <- 
  
f1_24 <-   ggplot() + 
  geom_line(data = wind24, aes(x = date, y = WindSpd_Med^3),
            size = 2) +
  ylim(0, 6000) +
  labs(y = bquote(Wind~"("*m^-3*s^-3*")")) +
  scale_x_date(limits = as_date(c("2024-01-01", "2024-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank())
```

```{r}
# Order locations from fjord to shelf
riv_loc <- c("Q_GM",
             "Q_SM",
             "Q_RA",
             "Q_tot")

q <- arrange(mutate(q, 
                      Watershed_group = factor(Watershed_group,
                                               levels = riv_loc)))
```

```{r}
fd_22 <- q %>% 
  filter(year == 2022) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_uchicago() +
  scale_x_date(limits = as.Date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "none",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
        # axis.text.y = element_blank())
```

```{r}
fd_24 <- q %>% 
  filter(year == 2024) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_uchicago() +
  scale_x_date(limits = as.Date(c("2024-01-01", "2024-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank())
        # axis.text.y = element_blank())
```

```{r}
b22_long <- b22 %>%
  select(date_corr, chla, fl_med_day, mean_sal, mean_temp) %>% 
  pivot_longer(c(chla, fl_med_day, mean_sal, mean_temp),
              names_to = "par", values_to = "val") %>% 
  mutate(date = date(date_corr))
```

```{r}

b24_long <- b24 %>%
  select(date_corr, chla, fl_med_day, mean_sal, mean_temp) %>% 
  pivot_longer(c(chla, fl_med_day, mean_sal, mean_temp),
              names_to = "par", values_to = "val") %>% 
  mutate(date = date(date_corr))

```

```{r}
f2_22 <-
  b22_long %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  annotate("rect", xmin = date("2024-03-05"), xmax = date("2024-04-30"),
           ymin = 0, ymax = Inf, fill = 'darkgreen', alpha = 0.2) +
  geom_line(data = filter(b22_long,
                          par == "fl_med_day"),
            size = 2) +
  geom_line(data = filter(b22_long,
                          par == "mean_sal"),
            size = 2) +
  geom_line(data = filter(b22_long,
                          par == "mean_temp"),
            size = 2) +
  geom_point(data = filter(b22_long,
                          par == "chla"),
            size = 4, pch = 8, stroke = 2) +
  ggsci::scale_color_jama(labels = c(expression(Chl[Discrete]),
                                         expression(Chl[BUOY]),
                                         expression(Salinity[BUOY]),
                                     expression(Temp[BUOY]))) +
  scale_x_date(limits = as_date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
                       paste("Salinity,"~"Temp")))) +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
```

```{r}
b22_long %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  annotate("rect", xmin = date("2024-03-05"), xmax = date("2024-04-30"),
           ymin = 0, ymax = Inf, fill = 'darkgreen', alpha = 0.2) +
  geom_line(data = filter(b22_long,
                          par == "fl_med_day"),
            size = 2) +
  geom_line(data = filter(b22_long,
                          par == "mean_sal"),
            size = 2) +
  geom_line(data = filter(b22_long,
                          par == "mean_temp"),
            size = 2) +
  geom_point(data = filter(b22_long,
                          par == "chla"),
            size = 4, pch = 8, stroke = 2) +
  ggsci::scale_color_jama(labels = c(expression(Chl[Discrete]),
                                         expression(Chl[BUOY]),
                                         expression(Salinity[BUOY]),
                                     expression(Temp[BUOY]))) +
  scale_x_date(limits = as_date(c("2022-01-01", "2023-01-01")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
                       paste("Salinity,"~"Temp")))) +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
```



```{r}
f2_24 <-
  b24_long %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  annotate("rect", xmin = date("2024-03-05"), xmax = date("2024-04-30"),
           ymin = 0, ymax = Inf, fill = 'darkgreen', alpha = 0.2) +
  geom_line(data = filter(b24_long,
                          par == "fl_med_day"),
            size = 2) +
  geom_line(data = filter(b24_long,
                          par == "mean_sal"),
            size = 2) +
  geom_line(data = filter(b24_long,
                          par == "mean_temp"),
            size = 2) +
  geom_point(data = filter(b24_long,
                          par == "chla"),
            size = 4, pch = 8, stroke = 2) +
  ggsci::scale_color_jama(labels = c(expression(Chl[Discrete]),
                                         expression(Chl[BUOY]),
                                         expression(Salinity[BUOY]),
                                     expression(Temp[BUOY]))) +
  scale_x_date(limits = as_date(c("2024-01-01", "2024-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
                       paste("Salinity,"~"Temp")))) +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "right",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank())
```

```{r}
wfb <- ggarrange(f1_22, f1_24, fd_22, fd_24, f2_22, f2_24, ncol = 2)

  

ggsave(here("figures", "panel_kc10_w_f_b.png"), wfb,
        width = 24, height = 12, dpi = 300)
```



```{r}

#Setting plotting order phytoplankton groups

#Order phytoplankton groups roughly from smallest to largest - create order list
order_chem <- c("cyan", "hapt", "GA", "cryp",
                   "dino", "raph", "dict", "diat")

#Chemtax full data - Specify order of phyto groups for figures
chem_tchla <- arrange(mutate(chem_tchla,
                                group = factor(group,
                                levels = order_chem)))


```

```{r}
# f5 <- 
  
chem_tchla %>%
  ggplot() +
  geom_bar(aes(date, contribution, fill = fct_rev(group)),
           position = "stack", stat = "identity",
           alpha = 1, color = "black", size = 1) +
  ggsci::scale_fill_npg() +
  scale_x_date(limits = as.Date(c("2019-01-01", "2024-12-31")),
               expand = c(0, 0),
               date_breaks = "years", date_labels = "%Y") +
  theme_bw() +
  labs(y = bquote("Phyto. (mg" ~ m^-3*")"),
       fill = "Group") +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
        # axis.text.y = element_blank())

ggsave(here("figures", "chemtax_19-24.png"),
        width = 16, height = 6, dpi = 300)
```
```{r}
test <- weath %>% 
  select(date, Q_Total) %>% 
  filter(!is.na(Q_Total)) %>% 
  mutate(yday = yday(date),
         year = year(date)) %>% 
  group_by(yday) %>% 
  mutate(mean = mean(Q_Total)) %>% 
  ungroup()

test %>% 
  filter(year == 2020) %>% 
  ggplot() +
  geom_line(aes(x = yday, y = mean)) +
  geom_line(aes(x = yday, y = Q_Total, color = as.factor(year)))

```




```{r}
#Now plot 2024 CTD profiles
# f2 <- 
  
# f4 <- 
  
# f3 <-  
# https://cran.r-project.org/web/packages/palr/vignettes/nasa_chla.html
maxrange <- c(0.01, 35)
pal <- chl_pal(palette = TRUE)
sb <- which(pal$breaks >= maxrange[1] & pal$breaks <= maxrange[2])


f22_plot <- f22 %>% 
  select(date, pres, f_npq)

f22_plot <- rbind(f22_plot, interp)

  
f3 <-
  f22_plot %>% 
  filter(pres < 51) %>% 
  mutate(day = 15,
         year = year(date),
         month = month(date)) %>% 
  unite(date_2, c(year, month, day), sep = "-", remove = F) %>% 
  mutate(date_2 = date(date_2)) %>% 
  ggplot(aes(x = date)) +
  geom_tile(aes(y = pres, fill = f_npq)) +
  # geom_vline(xintercept = as_date("2024-03-18"),
  #            linetype = "solid", size = 1, color = "white") +
  geom_hline(yintercept = 5,
             linetype = "dashed", size = 1, color = "white") +
  # annotate("text", x = as.Date("2024-01-15"), y = 5,
  #          label = "c)",
  #          size = 10) +
  # annotate("text", x = as.Date("2024-11-19"), y = 9,
  #          label = "5m",
  #          size = 10,
  #          color = "white") +
  scale_y_reverse(breaks = seq(0, 50, by = 10)) +
  # cmocean::scale_fill_cmocean(name = "delta",
  #                             limits = c(0, 20),
  #                             oob = scales::squish) +
  scale_fill_viridis_c(limits = c(0, 30),
                       oob = scales::squish) +
  #   scale_fill_gradientn(
  #   colours = oce::oceColors9A(120),
  #   breaks = c(0, 10, 20, 30),
  #   limits = c(0, 35),
  # ) +
  # scale_fill_gradient2(low = "blue",
  #                      mid = "green",
  #                      high = "red",
  #                      midpoint = 5) +
  labs(fill = bquote(CTD[FLU]~"(mg" ~ m^-3*")"),
       y = "Depth") +
  scale_x_date(limits = as_date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        legend.position = "right",
        legend.key.height = unit(1.8, "cm"),
        legend.title = element_text(size = 30, angle = 270),
        legend.title.align = 0.5,
        legend.direction = "vertical",
        axis.text.x = element_blank()
        ) +
    guides(fill = guide_colourbar(title.position = "right"))

  # theme(text = element_text(size = 35), #35
  #       axis.text = element_text(color = "black"),
  #       axis.title.x = element_blank(),
  #       legend.position = "top",
  #       legend.box = "horizontal") +
  # guides(fill = guide_colourbar(title.position = "top", title.hjust = 0.5,
  #                               barwidth = 50, barheight = 1,
  #                               frame.colour = "black", ticks.colour = "black"))
```


```{r}

#Setting plotting order phytoplankton groups

#Order phytoplankton groups roughly from smallest to largest - create order list
order_chem <- c("cyan", "hapt", "GA", "cryp",
                   "dino", "raph", "dict", "diat")

#Chemtax full data - Specify order of phyto groups for figures
chem_tchla <- arrange(mutate(chem_tchla,
                                group = factor(group,
                                levels = order_chem)))


```

```{r}
# f5 <- 
  
f4 <- chem_tchla %>%
  ggplot() +
  # annotate("rect", xmin = date("2024-03-05"), xmax = date("2024-04-30"),
  #          ymin = 0, ymax = Inf, fill = 'darkgreen', alpha = 0.2) +
  geom_bar(aes(date, contribution, fill = fct_rev(group)),
           position = "stack", stat = "identity",
           alpha = 1, color = "black", size = 1) +
  # geom_vline(xintercept = as_date("2024-03-18"),
  #            linetype = "solid", size = 1, color = "black") +
  # annotate("text", x = as.Date("2024-01-15"), y = 5.4,
  #          label = "d)",
  #          size = 10) +
  # annotate("text", x = as.Date("2024-12-15"), y = 5.4,
  #          label = "5m",
  #          size = 10) +
  ggsci::scale_fill_npg() +
  # lims(y = c(0, 5)) +
  scale_x_date(limits = as.Date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Phyto. (mg" ~ m^-3*")"),
       fill = "Group") +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
        # axis.text.y = element_blank())
```

```{r}
# test2 <- ggarrange(f1, f2, f3, f4, ncol = 1)
# 
#   
# 
# ggsave(here("figures", "panel_kc10_2022_CHEMTAX_2.png"), test2,
#         width = 16, height = 16, dpi = 300)
```
```{r}
wind_22_24 <- wind %>% 
  filter(year == 2022 | year == 2024) %>% 
  mutate(yday = yday(date))

  ggplot() + 
  geom_line(data = wind_22_24, aes(x = yday, y = WindSpd_Med^3,
                               color = as.factor(year)),
            size = 2) +
  ggsci::scale_color_aaas() +
  labs(y = bquote(Wind~"("*m^-3*s^-3*")"),
       color = NULL) +
  facet_grid(year~.) +
  # scale_x_date(limits = as_date(c("2022-01-01", "2022-12-31")),
  #              expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        legend.position = "none")

ggsave(here("figures", "panel_kc10_2022_2024_wind.png"), 
        width = 16, height = 10, dpi = 300)  
```
```{r}
# Order locations from fjord to shelf
riv_loc <- c("Q_GM",
             "Q_SM",
             "Q_RA",
             "Q_tot")

q <- arrange(mutate(q, 
                      Watershed_group = factor(Watershed_group,
                                               levels = riv_loc)))
```

```{r}
f5 <- q %>% 
  filter(year == 2022) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_uchicago() +
  scale_x_date(limits = as.Date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
        # axis.text.y = element_blank())
```

```{r}
# test3 <- ggarrange(f1, f2, f5, ncol = 1)
# 
#   
# 
# ggsave(here("figures", "panel_kc10_2022_CHEMTAX_2_FW.png"), test3,
#         width = 16, height = 12, dpi = 300)
```
```{r}
q_22 <- q %>% 
  filter(year == 2022)

#2022-07-12 to 15 discharge peaks
#2022-07-24 to 26 buoy salinity minimum
#so 9ish day lag?
#is this consistent?


```




```{r}

f6 <- q %>% 
  filter(year == 2024) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_uchicago() +
  scale_x_date(limits = as.Date(c("2024-01-01", "2024-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
        # axis.text.y = element_blank())

```

```{r}
test4 <- ggarrange(f5, f6, ncol = 1)

  

ggsave(here("figures", "panel_kc10_2022_2024_Q.png"), test4,
        width = 16, height = 8, dpi = 300)
```

```{r}
b_all <- rbind(b22, b24)

bf1 <- b_all %>% 
  left_join(weath) %>%
  mutate(month = month(date)) %>% 
  filter(year == 2022) %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = lag(Q_Total/10^3, 9), y = mean_sal)) +
  geom_point(aes(color = as.factor(month)), size = 4) +
  geom_smooth(method = "lm") +
  facet_grid(year~.) +
  ggpubr::stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),
                   p.accuracy = 0.001, size = 9, label.y.npc = 0.1) +
  ggpubr::stat_regline_equation(size = 9, label.y.npc = 0.16) +
  ylim(15, 32) +
  xlim(0, 5) +
  labs(x = bquote(Q[TOTAL-9] ~ "("*10^3~m^3*~s^-1*")"),
       y = bquote(Salinity[BUOY]),
       color = "Month") +
  scale_color_viridis_d(option = "turbo") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "right",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

bf2 <- b_all %>% 
  left_join(weath) %>% 
  filter(year == 2024) %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = lag(Q_Total/10^3, 6), y = mean_sal)) +
  geom_point(aes(color = as.factor(month)), size = 4) +
  geom_smooth(method = "lm") +
  facet_grid(year~.) +
  ggpubr::stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),
                   p.accuracy = 0.001, size = 9, label.y.npc = 0.1) +
  ggpubr::stat_regline_equation(size = 9, label.y.npc = 0.16) +
  ylim(15, 32) +
  xlim(0, 5) +
  labs(x = bquote(Q[TOTAL-6] ~ "("*10^3~m^3*~s^-1*")"),
       y = bquote(Salinity[BUOY]),
       color = "Month") +
  scale_color_viridis_d(option = "turbo") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "right",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

bfig <- bf1/bf2 + plot_layout(guides = "collect")

ggsave(here("figures", "discharge_buoy_sal.png"), bfig,
        width = 8, height = 12, dpi = 300)
```

```{r}
b_all <- b_all %>% 
  group_by(year) %>% 
  mutate(csum = cumsum(fl_med_day)) %>% 
  mutate(max = max(csum)) %>% 
  ungroup()
```

```{r}
dates <- as.data.frame(seq(as.Date("2024-01-01"),as.Date("2024-12-04"),1))

b24_cor1 <- b24 %>% 
  filter(date <= "2024-03-19" | date >= "2024-03-25")

b24_cor2 <- dates %>% 
  rename(date = `seq(as.Date("2024-01-01"), as.Date("2024-12-04"), 1)`) %>% 
  left_join(b24_cor1) %>% 
  select(date, fl_med_day)

b24_cor3 <- data.frame(date = seq(b24_cor2$date[1], b24_cor2$date[nrow(b24_cor2)], by = 1)) %>%
  full_join(b24_cor2, by = "date") %>%
  mutate(fl_fill = na.approx(fl_med_day))

b22_cm <- b22 %>% 
  mutate(med = median(fl_med_day),
         fl_med = fl_med_day - med,
         csum = cumsum(fl_med)) %>% 
  select(date, fl = fl_med_day, csum)

b24_cm <- b24_cor3 %>% 
  mutate(med = median(fl_fill),
         fl_med = fl_fill - med,
         csum = cumsum(fl_med)) %>% 
  select(date, fl = fl_fill, csum)

cm <- rbind(b22_cm, b24_cm)


csf_1 <- cm %>% 
  mutate(yday = yday(date),
         year = year(date),
         date2 = as.Date(yday, origin = "2024-01-01")) %>% 
  ggplot(aes(x = date2, y = fl)) +
  geom_line(aes(color = as.factor(year)), size = 2) +
  scale_x_date(date_breaks = "months", date_labels = "%b") +
  scale_color_simpsons()+
  scale_color_jama() +
  ylab(bquote("Flu"[BUOY]~"(mg" ~ m^-2*")")) +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())

csf_2 <- cm %>% 
  mutate(yday = yday(date),
         year = year(date),
         date2 = as.Date(yday, origin = "2024-01-01")) %>% 
  ggplot(aes(x = date2, y = csum)) +
  geom_line(aes(color = as.factor(year)), size = 2) +
  scale_x_date(date_breaks = "months", date_labels = "%b") +
  scale_color_jama() +
  ylab(bquote("Int. Flu"[BUOY]~"(mg" ~ m^-2*")")) +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = c(0.9, 0.13),
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())

csfig <- csf_1/csf_2 

ggsave(here("figures", "cum_sum.png"), csfig,
        width = 16, height = 10, dpi = 300)
```



```{r}
fs1 <- b22 %>% 
  left_join(weath) %>% 
  mutate(month = month(date)) %>%
  ggplot(aes(x = mean_sal, y = fl_med_day)) +
  geom_point(aes(color = as.factor(month)), size = 4) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote(Salinity[BUOY]),
       y = bquote(flu[Buoy]~"("*mg~m^-3*")"),
       color = "Month") +
  xlim(15, 32) +
  ylim(0, 22) +
  ggtitle("2022") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "right",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

fs2 <- b24 %>%
  left_join(weath) %>% 
  mutate(month = month(date)) %>%
  ggplot(aes(x = mean_sal, y = fl_med_day)) +
  geom_point(aes(color = as.factor(month)), size = 4) +
  scale_color_viridis_d(option = "turbo") +
  xlim(15, 32) +
  ylim(0, 22) +
  labs(x = bquote(Salinity[BUOY]),
       y = bquote(FLu[Buoy]~"("*mg~m^-3*")"),
       color = "Month") +
  ggtitle("2024") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "right",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

fsfig <- fs1/fs2 + plot_layout(guides = "collect")

ggsave(here("figures", "buoy_sal_flu.png"), fsfig,
        width = 8, height = 12, dpi = 300)
```
```{r}
ft1 <- b22 %>% 
  left_join(weath) %>% 
  mutate(month = month(date)) %>%
  ggplot(aes(x = mean_temp, y = fl_med_day)) +
  geom_point(aes(color = as.factor(month)), size = 4) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote(Temp[BUOY]),
       y = bquote(flu[Buoy]~"("*mg~m^-3*")"),
       color = "Month") +
  xlim(4, 17) +
  ylim(0, 22) +
  ggtitle("2022") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "right",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

ft2 <- b24 %>%
  left_join(weath) %>% 
  mutate(month = month(date)) %>%
  ggplot(aes(x = mean_temp, y = fl_med_day)) +
  geom_point(aes(color = as.factor(month)), size = 4) +
  scale_color_viridis_d(option = "turbo") +
  xlim(4, 17) +
  ylim(0, 22) +
  labs(x = bquote(Temp[BUOY]),
       y = bquote(FLu[Buoy]~"("*mg~m^-3*")"),
       color = "Month") +
  ggtitle("2024") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "right",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

ftfig <- ft1/ft2 + plot_layout(guides = "collect")

ggsave(here("figures", "buoy_temp_flu.png"), ftfig,
        width = 8, height = 12, dpi = 300)
```
```{r}
fw1 <- b22 %>% 
  left_join(weath) %>% 
  mutate(month = month(date)) %>%
  ggplot(aes(x = wind_b1_3, y = fl_med_day)) +
  geom_point(aes(color = as.factor(month)), size = 4) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote(WS[LO-3-AVG]~"("*m~s^-1*")"),
       y = bquote(flu[Buoy]~"("*mg~m^-3*")"),
       color = "Month") +
  xlim(0, 15) +
  ylim(0, 22) +
  ggtitle("2022") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "right",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

fw2 <- b24 %>%
  left_join(weath) %>% 
  mutate(month = month(date)) %>%
  ggplot(aes(x = wind_b1_3, y = fl_med_day)) +
  geom_point(aes(color = as.factor(month)), size = 4) +
  scale_color_viridis_d(option = "turbo") +
  xlim(0, 15) +
  ylim(0, 22) +
  labs(x = bquote(WS[LO-3-AVG]~"("*m~s^-1*")"),
       y = bquote(FLu[Buoy]~"("*mg~m^-3*")"),
       color = "Month") +
  ggtitle("2024") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "right",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

fwfig <- fw1/fw2 + plot_layout(guides = "collect")

ggsave(here("figures", "buoy_wind_flu.png"), fwfig,
        width = 8, height = 12, dpi = 300)
```

```{r}
up_dm <- up %>% 
  mutate(date = date(time),
         upwelling_index = as.numeric(upwelling_index)) %>% 
  group_by(date) %>% 
  summarise(up_dm = mean(upwelling_index)) %>% 
  ungroup()

b22 <- b22 %>% 
  left_join(up_dm)

b24 <- b24 %>% 
  left_join(up_dm)

b24 %>% 
  mutate(month = month(date)) %>%
  ggplot(aes(x = up_dm, y = mean_sal)) +
  geom_point(aes(color = as.factor(month)), size = 4) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote(WS[LO-3-AVG]~"("*m~s^-1*")"),
       y = bquote(flu[Buoy]~"("*mg~m^-3*")"),
       color = "Month") +
  # xlim(0, 15) +
  # ylim(0, 22) +
  ggtitle("2022") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "right",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```

```{r}
b22 <- b22 %>% 
  left_join(weath) %>% 
  select(date, f = fl_med_day, t = mean_temp, s = mean_sal, ws = w_dm, wd = w_dm)

b22 <- b22 %>% 
  mutate(doy = yday(date))
```


```{r}
# GAM Analysis for Daily Fluorescence Time Series
# Dataset: b22 with daily means of ws, wd, t, s, f

library(mgcv)
library(gratia)
library(dplyr)
library(ggplot2)
library(lubridate)

# ============================================================================
# 1. DATA PREPARATION
# ============================================================================

# Assuming your data has a date column - adjust as needed
# b22$date <- as.Date(b22$date)  # uncomment if needed

# Create time variables for temporal patterns
b22 <- b22 %>%
  mutate(
    # Day of year for seasonal patterns
    doy = yday(date),
    
    # Convert wind to u,v components (more appropriate for GAM)
    wind_u = ws * cos(wd * pi/180),
    wind_v = ws * sin(wd * pi/180),
    
    # Create lagged variables (ecological responses often delayed)
    ws_lag1 = lag(ws, 1),
    ws_lag2 = lag(ws, 2),
    ws_lag3 = lag(ws, 3),
    t_lag1 = lag(t, 1),
    s_lag1 = lag(s, 1),
    
    # Derived variables
    temp_change = t - lag(t, 1),          # daily temperature change
    sal_change = s - lag(s, 1),           # daily salinity change
    density_proxy = s/t,                  # rough density proxy
    
    # Log transform fluorescence (often skewed)
    log_f = log(f + 0.01),               # small constant to handle zeros
    
    # Time index for temporal correlation
    time_index = row_number()
  )

# Check for missing values
summary(b22)

# ============================================================================
# 2. EXPLORATORY ANALYSIS
# ============================================================================

# Quick visualization of relationships
par(mfrow=c(2,3))
plot(b22$ws, b22$f, main="Wind Speed vs Fluorescence")
plot(b22$t, b22$f, main="Temperature vs Fluorescence")
plot(b22$s, b22$f, main="Salinity vs Fluorescence")
plot(b22$wind_u, b22$f, main="U-wind vs Fluorescence")
plot(b22$wind_v, b22$f, main="V-wind vs Fluorescence")
plot(b22$doy, b22$f, main="Seasonal Pattern")

# Time series plot
ggplot(b22, aes(x=date)) +
  geom_line(aes(y=f, color="Fluorescence")) +
  geom_line(aes(y=ws*max(f)/max(ws), color="Wind Speed")) +
  scale_y_continuous(sec.axis = sec_axis(~.*max(b22$ws)/max(b22$f), name="Wind Speed")) +
  labs(title="Fluorescence and Wind Speed Time Series") +
  theme_minimal()
```


```{r}
# ============================================================================
# 3. GAM MODELS
# ============================================================================

# Model 1: Basic model with current conditions
# For single year: reduce seasonal complexity
m1 <- gam(f ~ 
          s(ws, k=10) + 
          s(t, k=10) + 
          s(s, k=10) +
          s(doy, bs="cc", k=6),   # reduced k for single year seasonality
        data = b22,
        family = Gamma(link="log"),
        na.action = na.exclude)

# Alternative: Simple seasonal terms instead of splines
m1_alt <- gam(f ~ 
              s(ws, k=10) + 
              s(t, k=10) + 
              s(s, k=10) +
              sin(2*pi*doy/365) + cos(2*pi*doy/365) +  # simple harmonic
              sin(4*pi*doy/365) + cos(4*pi*doy/365),   # semi-annual
            data = b22,
            family = Gamma(link="log"),
            na.action = na.exclude)

# Model 2: Using wind components instead of speed/direction
# Reduced seasonal complexity for single year
m2 <- gam(f ~ 
          s(wind_u, k=10) + 
          s(wind_v, k=10) + 
          s(t, k=10) + 
          s(s, k=10) +
          s(doy, bs="cc", k=6),
        data = b22,
        family = Gamma(link="log"),
        na.action = na.exclude)

# Model 3: Include lagged effects
# For single year, focus on shorter lags
m3 <- gam(f ~ 
          s(ws, k=10) + 
          s(ws_lag1, k=8) + 
          s(ws_lag2, k=6) +    # reduced complexity for lags
          s(t, k=10) + 
          s(t_lag1, k=8) +
          s(s, k=10) +
          s(doy, bs="cc", k=6),
        data = b22,
        family = Gamma(link="log"),
        na.action = na.exclude)

# Model 4: Include interactions
# Be conservative with interactions for single year
m4 <- gam(f ~ 
          s(ws, k=10) + 
          s(t, k=10) + 
          s(s, k=10) +
          s(t, s, k=15) +           # reduced interaction complexity
          s(doy, bs="cc", k=6),
        data = b22,
        family = Gamma(link="log"),
        na.action = na.exclude)

# Model 5: Include rate of change variables
m5 <- gam(f ~ 
          s(ws, k=10) + 
          s(t, k=10) + 
          s(s, k=10) +
          s(temp_change, k=6) +    # reduced k for derivatives
          s(sal_change, k=6) +
          s(doy, bs="cc", k=6),
        data = b22,
        family = Gamma(link="log"),
        na.action = na.exclude)

# For single year data, consider these alternatives:

# Option 1: No seasonal term if environmental drivers capture seasonality
m_no_season <- gam(f ~ 
                   s(ws, k=10) + 
                   s(t, k=10) + 
                   s(s, k=10),
                 data = b22,
                 family = Gamma(link="log"),
                 na.action = na.exclude)

# Option 2: Seasonal-varying coefficients (simplified version)
# Note: Fixed the tensor product syntax
m_seasonal_varying <- gam(f ~ 
                          s(ws, k=10) + 
                          s(t, k=10) + 
                          s(s, k=10) +
                          te(doy, ws, k=c(4,6)) +  # tensor product interaction
                          te(doy, t, k=c(4,6)),    # tensor product interaction
                        data = b22,
                        family = Gamma(link="log"),
                        na.action = na.exclude)

# Check if seasonal patterns are confounded with environmental drivers
cor_matrix <- cor(b22[,c("t", "s", "ws", "doy")], use="pairwise.complete.obs")
print("Correlation matrix (check for seasonal confounding):")
print(round(cor_matrix, 3))
```


```{r}
# ============================================================================
# 4. MODEL COMPARISON
# ============================================================================

# Compare models (including single-year alternatives)
model_list <- list(m1, m2, m3, m4, m5, m_no_season, m1_alt, m_seasonal_varying)
model_names <- c("Basic", "Wind_UV", "Lagged", "Interactions", "Rate_Change", 
                 "No_Season", "Alt_Season", "Seasonal_Varying")

# Calculate AIC and deviance explained safely
aic_values <- sapply(model_list, function(x) {
  tryCatch(AIC(x), error = function(e) NA)
})

dev_expl_values <- sapply(model_list, function(x) {
  tryCatch(summary(x)$dev.expl, error = function(e) NA)
})

model_comparison <- data.frame(
  Model = model_names,
  AIC = aic_values,
  Deviance_Explained = dev_expl_values
)

print(model_comparison)
```


```{r}
# Select best model (lowest AIC, excluding failed models)
valid_models <- !is.na(model_comparison$AIC)
if(any(valid_models)) {
  best_idx <- which.min(model_comparison$AIC[valid_models])
  best_model_idx <- which(valid_models)[best_idx]
  best_model <- model_list[[best_model_idx]]
  
  print("=== SINGLE YEAR DATA DIAGNOSTICS ===")
  print(paste("Best model:", model_comparison$Model[best_model_idx]))
  print(paste("Sample size:", nrow(b22[complete.cases(b22[,c("f","ws","t","s")]),])))
  print(paste("Effective degrees of freedom:", round(sum(best_model$edf), 1)))
  print(paste("Ratio of observations to EDF:", 
              round(nrow(b22[complete.cases(b22[,c("f","ws","t","s")]),]) / sum(best_model$edf), 1)))
} else {
  print("No valid models found - check your data")
  best_model <- m1  # fallback to basic model
}
```


```{r}
# ============================================================================
# 5. MODEL DIAGNOSTICS
# ============================================================================

# Check model assumptions
gam.check(best_model)

# Plot residuals
par(mfrow=c(2,2))
plot(best_model)

# Check for temporal autocorrelation in residuals
residuals <- residuals(best_model)
acf(residuals, na.action=na.pass, main="Residual Autocorrelation")
```


```{r}
# ============================================================================
# 6. VISUALIZATION OF RESULTS
# ============================================================================

# Plot smooth functions using gratia
draw(best_model)

# Individual effect plots
p1 <- draw(best_model, select="s(ws)")
p2 <- draw(best_model, select="s(t)")
p3 <- draw(best_model, select="s(s)")
p4 <- draw(best_model, select="s(doy)")

# Print individual plots
print(p1)
print(p2)
print(p3)
print(p4)
```


```{r}
# ============================================================================
# 7. PREDICTIONS AND SCENARIOS
# ============================================================================

# Predict fluorescence under different wind scenarios
wind_scenarios <- expand.grid(
  ws = seq(min(b22$ws, na.rm=T), max(b22$ws, na.rm=T), length.out=20),
  t = mean(b22$t, na.rm=T),
  s = mean(b22$s, na.rm=T),
  doy = 180  # mid-year
)

# Add predictions
wind_scenarios$predicted_f <- predict(best_model, newdata=wind_scenarios, type="response")

# Plot wind effect
ggplot(wind_scenarios, aes(x=ws, y=predicted_f)) +
  geom_line(color="blue", size=1.2) +
  labs(title="Predicted Fluorescence Response to Wind Speed",
       x="Wind Speed", y="Predicted Fluorescence") +
  theme_minimal()
```


```{r}
# ============================================================================
# 8. SUMMARY STATISTICS
# ============================================================================

# Model summary
summary(best_model)

# Variable importance (approximate)
smooth_terms <- best_model$smooth
if(length(smooth_terms) > 0) {
  var_importance <- data.frame(
    Variable = sapply(smooth_terms, function(x) x$label),
    F_statistic = sapply(smooth_terms, function(x) x$F.stat),
    p_value = sapply(smooth_terms, function(x) x$p.value),
    EDF = sapply(smooth_terms, function(x) x$edf)
  )
  
  print("Variable Importance (F-statistics):")
  print(var_importance[order(var_importance$F_statistic, decreasing=T),])
}
```
```{r}
# Model summary
summary(best_model)

# Extract variable importance from summary
gam_summary <- summary(best_model)

# Get smooth terms table
smooth_table <- gam_summary$s.table

# Create variable importance data frame
if(nrow(smooth_table) > 0) {
  var_importance <- data.frame(
    Variable = rownames(smooth_table),
    F_statistic = smooth_table[, "F"],
    p_value = smooth_table[, "p-value"],
    EDF = smooth_table[, "edf"]
  )
  
  print("Variable Importance (F-statistics):")
  print(var_importance[order(var_importance$F_statistic, decreasing = TRUE), ])
}

# Alternative: Use anova() for a cleaner output
print("ANOVA table for smooth terms:")
anova(best_model)
# The key difference is that you need to extract the information from summary(best_model)$s.table rather than trying to access it directly from the smooth objects. The anova() function also provides a clean way to see the significance tests for all smooth terms.
# This will properly show you the F-statistics, p-values, and effective degrees of freedom for ranking variable importance in your GAM.RetryClaude does not have the ability to run the code it generates yet.Claude can make mistakes. Please double-check responses.
```


```{r}
# ============================================================================
# 9. ADDITIONAL ANALYSIS OPTIONS
# ============================================================================

# If you want to account for temporal autocorrelation more explicitly
# m_gamm <- gamm(f ~ 
#                s(ws, k=10) + 
#                s(t, k=10) + 
#                s(s, k=10) +
#                s(doy, bs="cc", k=6),
#              correlation = corAR1(form = ~ time_index),
#              data = b22,
#              family = Gamma(link="log"))

# If you want to use a different distribution
# m_tw <- gam(f ~ 
#             s(ws, k=10) + 
#             s(t, k=10) + 
#             s(s, k=10) +
#             s(doy, bs="cc", k=6),
#           data = b22,
#           family = tw(link="log"))  # Tweedie distribution
```

```{r}
# Plot the temperature smooth to see the relationship
plot(best_model, select = 2)  # Assuming s(t) is the second smooth term

# Or use ggplot with gratia package for better plots
library(gratia)
draw(best_model, select = "s(s)")

# Or plot all smooths at once
plot(best_model, pages = 1)
```

```{r}
draw(best_model) + 
  theme_minimal() +
  labs(title = "Environmental drivers of phytoplankton response")
```
```{r}
gam.check(best_model)
```

```{r}
improved_model <- gam(f ~ s(ws, k = 20) + s(t, k = 20) + s(s, k = 20) + 
                     te(doy, ws, k = c(20, 20)) + 
                     te(doy, t, k = c(20, 20)),
                     family = Gamma(link = "log"),
                     data = b22)

gam.check(improved_model)
```



```{r}
# Create individual smooth plots with ggplot styling
p1 <- draw(improved_model, select = "s(ws)") + 
  labs(x = "Wind Speed (m/s)", 
       y = "Partial Effect",
       title = "(a) Wind Speed") +
  theme_classic() +
  theme(text = element_text(size = 12),
        plot.title = element_text(size = 14, face = "bold"))

p2 <- draw(improved_model, select = "s(t)") + 
  labs(x = "Temperature (°C)", 
       y = "Partial Effect",
       title = "(b) Temperature") +
  theme_classic() +
  theme(text = element_text(size = 12),
        plot.title = element_text(size = 14, face = "bold"))

p3 <- draw(improved_model, select = "s(s)") + 
  labs(x = "Salinity", 
       y = "Partial Effect",
       title = "(c) Salinity") +
  theme_classic() +
  theme(text = element_text(size = 12),
        plot.title = element_text(size = 14, face = "bold"))

# For tensor products, we'll create a separate interaction plot
p4 <- draw(improved_model, select = "te(doy,ws)") + 
  labs(x = "Day of Year", 
       y = "Wind Speed (m/s)",
       title = "(d) Day × Wind Speed Interaction") +
  theme_classic() +
  theme(text = element_text(size = 12),
        plot.title = element_text(size = 14, face = "bold"))

# Combine into 2x2 panel
smooth_panel <- grid.arrange(p1, p2, p3, p4, ncol = 2)

```
```{r}
# Create data for prediction grid
doy_seq <- seq(1, 365, length = 50)
temp_seq <- seq(min(b22$t), max(b22$t), length = 50)  # Replace with actual temp range
pred_grid <- expand.grid(doy = doy_seq, t = temp_seq)
pred_grid$ws <- mean(b22$ws, na.rm = TRUE)  # Fix other variables at mean
pred_grid$s <- mean(b22$s, na.rm = TRUE)

# Get predictions
pred_grid$fit <- predict(improved_model, newdata = pred_grid, type = "response")

# Create contour plot
ggplot(pred_grid, aes(x = doy, y = t, z = fit)) +
  geom_contour_filled(bins = 15) +
  scale_fill_viridis_d(name = "Predicted\nResponse") +
  labs(x = "Day of Year", 
       y = "Temperature (°C)",
       title = "Seasonal-Temperature Interaction") +
  theme_classic() +
  theme(text = element_text(size = 12),
        plot.title = element_text(size = 14, face = "bold"),
        legend.position = "right")
```

```{r}
# Check your actual data ranges
summary(b22$doy)
summary(b22$t)
range(b22$f, na.rm = TRUE)  # Your response variable

# Check for extreme predictions
summary(fitted(improved_model))
max(predict(improved_model, type = "response"))

# Plot with actual data range only
plot(improved_model, select = "te(doy,t)", scheme = 2)
```


