---
title: "R Notebook"
output: html_notebook
---

Some new interpolation tutorials to consider:
https://search.r-project.org/CRAN/refmans/rioja/html/interp.dataset.html
https://github.com/hdugan/NTLlakeloads

```{r}
#Upload packages
library(tidyverse)
library(here)
library(readxl)
library(patchwork)
library(lubridate)
library(MBA)
library(mgcv)
library(FNN)
library(zoo)
library(reshape2)
library(rioja)
library(egg)
library(palr)
library(ggsci)

```

```{r}
# 2024 corrected buoy data
b22 <- read.csv(here("outputs", "buoy_corr_dm_2022.csv"))
b24 <- read.csv(here("outputs", "buoy_corr_dm_2024.csv"))

bsal <- read.csv(here("files", "buoy_ts_all.csv"))

#Corrected CTD data
f <- read_csv(here("outputs", "corrected_flu_2025-05-09.csv"))

fm <- read_csv(here("files", "flu_2022-03-09.csv"))


#Downloading discrete chlorophyll samples
cd <- read_csv(here("files", "2024-12-05_HakaiData_chlorophyll.csv"))

cm <- read_csv(here("files", "chl_2022-03-09.csv")) 
cs <- read_csv(here("files", "chl_2022-09-09.csv")) 
  
wind <- read_csv(here("files", "wind_all.csv"))

wind_hour <- read_csv(here("files", "2025-06-09.1hourSamples.all.csv"))

wind_anom <- read.csv(here("outputs", "wind_anom_day_2025-04-25.csv"))

#CHEMTAX
chem <- read_csv(here("files", "chemtax_kc10_2024.csv"))

weath <- read_csv(here("outputs", "enviro_weather_2025-04-14.csv"))

par <- read_csv(here("files", "2025-06-06.1hourSamples.2022.csv"))

ctd <- read_csv(here("outputs", "enviro_ctd_nut_2025-04-14.csv"))
```



```{r}
q <- weath %>% 
  select(date, Q_GM, Q_SM, Q_RA) %>% 
  pivot_longer(c(Q_GM:Q_RA), names_to = "Watershed_group", values_to = "Q") %>% 
  drop_na() %>% 
  group_by(date) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  mutate(year = year(date))
```

```{r}
p <- par %>% 
  mutate(date = mdy_hm(measurementTime))

wh <- wind_hour %>% 
  mutate(date = mdy_hm(measurementTime))
```


```{r}
b22 <- b22 %>% 
  select(date_corr, fl_med_day) %>% 
  distinct()

bsal2 <- bsal %>% 
  mutate(measurementTime = mdy_hm(measurementTime),
         date = date(measurementTime)) %>% 
  filter(WaterSalinity_UQL == 2 & (year == 2022 | year == 2024)) %>% 
  group_by(date) %>% 
  summarise(mean_sal = mean(WaterSalinity)) %>% 
  ungroup()

btemp <- bsal %>% 
  mutate(measurementTime = mdy_hm(measurementTime),
         date = date(measurementTime)) %>% 
  filter(WaterTemp_UQL == 2 & (year == 2022 | year == 2024)) %>% 
  group_by(date) %>% 
  summarise(mean_temp = mean(WaterTemp)) %>% 
  ungroup()

bsal2 <- bsal2 %>% 
  left_join(btemp)

f22 <- f %>% 
  mutate(year = year(date)) %>% 
  filter(year == 2022)

wind <- wind %>% 
  mutate(date = mdy(date))

wind22 <- wind %>% 
  filter(year == 2022)

wind24 <- wind %>% 
  filter(year == 2024)
```

```{r}
cd <- cd %>% 
  filter(filter_type == "Bulk GF/F" & line_out_depth == 0) %>% 
  select(date, chla) %>% 
  mutate(chla = case_when(date == "2022-05-05" ~ 1.41,
                          TRUE ~ as.numeric(chla)))

cm <- cm %>% 
  filter(filter_type == "Bulk GF/F") %>% 
  select(date, pres = line_out_depth, chla) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))

cs <- cs %>% 
  filter(filter_type == "Bulk GF/F") %>% 
  select(date, pres = line_out_depth, chla) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))

c2 <- rbind(cm, cs)

c2_wide <- c2 %>% 
  pivot_wider(names_from = "date", values_from = "chla")
```

```{r}
# fm <- fm %>% 
#   select(pres = `Pressure (dbar)`, flu = `Fluorometry Chlorophyll (ug/L)`)
# 
# fmc <- fm %>% 
#   left_join(cm) 
```
```{r}
#lets just interpolate the chlorophyll bottle data rather than "fix" the fluorometer
spec <- c2_wide %>% 
  select(2:3)

# spec <- as.data.frame(chl_mm_wide$chl_dm)
depth <- c2_wide$pres

# interpolate new dataset to every 0.5 cm
# using default method (linear)
x.new <- seq(1, 101, by = 1)
sp.interp <- interp.dataset(y = spec, x = depth, xout = x.new,
                               method = "loess", span = 0.5)

interp <- as.data.frame(sp.interp)

interp <- interp %>% 
  mutate(pres = x.new) %>% 
  pivot_longer(cols = (1:2), names_to = "date", values_to = "f_npq") %>% 
  # mutate(date = date(date)) %>% 
  mutate_at(vars(f_npq), funs(round(., 2))) %>% 
  # mutate(date = as.Date("2022-03-09")) %>% 
  select(date, pres, f_npq) %>% 
  mutate(date = date(date))
```



```{r}
b22 <- b22 %>% 
  mutate(date = lubridate::ymd(date_corr),
         year = lubridate::year(date),
         yday = lubridate::yday(date)) 

b22 <- b22 %>% 
  left_join(cd) %>% 
  left_join(bsal2)

b24 <- b24 %>% 
  mutate(date = lubridate::ymd(date_corr),
         year = lubridate::year(date),
         yday = lubridate::yday(date)) 

b24 <- b24 %>% 
  left_join(cd) %>% 
  left_join(bsal2)
```



```{r}
#Working with chemtax data to make it easy to plot

#Making the date column a date format
chem <- chem %>% 
  mutate(date2 = lubridate::mdy(Date)) 

#Selecting appropriate columns and renaming to easy to work with names
chem <- chem %>%
  select(date = date2, cyan = Cyanobacteria, hapt = Hapto, 
         GA = `Prasinophytes-3`, cryp = Cryptophytes,
         dino = `Dinoflagellates-1`, raph = Raphido,
         dict = Dictyo, diat = `Diatoms-1`)

#Pivoting to long/tidy for plotting in ggplot
chem <- chem %>% 
  pivot_longer(c(cyan:diat), names_to = "group", values_to = "contribution")

#Calculating TChla for each sample
chem_tchla <- chem %>% 
  group_by(date, group) %>% 
  summarise(contribution = mean(contribution)) %>% 
  ungroup() %>% 
  group_by(date) %>% 
  mutate(tchla = sum(contribution)) %>% 
  ungroup()


#checking to see if there are any duplicates - there were replicates taken for DFO comparisons. None found because I already averaged these for the manuscript.
chem_dup <- chem_tchla %>%
  distinct(date, tchla) %>% 
  group_by(date) %>% 
  mutate(dup = n()) %>% 
  ungroup() %>% 
  filter(dup > 1)

#Good to move forward
```



```{r}
# f1 <- wind24 %>% 
#   ggplot(aes(x = date, y = WindSpd_Med^3, color = as.factor(year))) +
#   geom_line(size = 2) +
#   ggsci::scale_color_futurama() +
#   scale_x_date(limits = as_date(c("2024-01-01", "2024-12-31")),
#                expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
#   labs(y = bquote(Wind~"("*m^-3*")")) +
#   theme_bw() +
#   theme(legend.position = "none",
#         text = element_text(size = 35), #35
#         axis.text = element_text(color = "black"),
#         axis.title.x = element_blank(),
#         axis.text.x = element_blank())
```


```{r}
# f1 <- 
  
f1_22 <-   ggplot() + 
  geom_line(data = wind22, aes(x = date, y = WindSpd_Med),
            size = 2) +
  ylim(0, 12) +
  labs(y = bquote(Wind~"("*m*s^-1*")")) +
  scale_x_date(limits = as_date(c("2022-08-01", "2022-09-01")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```

```{r}
# f1 <- 
  
f1_24 <-   ggplot() + 
  geom_line(data = wind24, aes(x = date, y = WindSpd_Med),
            size = 2) +
  ylim(0, 12) +
  labs(y = bquote(Wind~"("*m*s^-1*")")) +
  labs(y = bquote(Wind~"("*m^-3*s^-3*")")) +
  scale_x_date(limits = as_date(c("2024-08-01", "2024-09-01")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank())
```

```{r}
# Order locations from fjord to shelf
riv_loc <- c("Q_GM",
             "Q_SM",
             "Q_RA",
             "Q_tot")

q <- arrange(mutate(q, 
                      Watershed_group = factor(Watershed_group,
                                               levels = riv_loc)))
```

```{r}
fd_22 <- q %>% 
  filter(year == 2022) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_uchicago() +
  scale_x_date(limits = as.Date(c("2022-08-01", "2022-09-01")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "none",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
        # axis.text.y = element_blank())
```

```{r}
fd_24 <- q %>% 
  filter(year == 2024) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_uchicago() +
  scale_x_date(limits = as.Date(c("2024-08-01", "2024-09-01")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank())
        # axis.text.y = element_blank())
```

```{r}
b22_long <- b22 %>%
  select(date_corr, chla, fl_med_day, mean_sal, mean_temp) %>% 
  pivot_longer(c(chla, fl_med_day, mean_sal, mean_temp),
              names_to = "par", values_to = "val") %>% 
  mutate(date = date(date_corr))
```

```{r}

b24_long <- b24 %>%
  select(date_corr, chla, fl_med_day, mean_sal, mean_temp) %>% 
  pivot_longer(c(chla, fl_med_day, mean_sal, mean_temp),
              names_to = "par", values_to = "val") %>% 
  mutate(date = date(date_corr))

```

```{r}
f2_22 <-
  b22_long %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  annotate("rect", xmin = date("2024-03-05"), xmax = date("2024-04-30"),
           ymin = 0, ymax = Inf, fill = 'darkgreen', alpha = 0.2) +
  geom_line(data = filter(b22_long,
                          par == "fl_med_day"),
            size = 2) +
  geom_line(data = filter(b22_long,
                          par == "mean_sal"),
            size = 2) +
  geom_line(data = filter(b22_long,
                          par == "mean_temp"),
            size = 2) +
  geom_point(data = filter(b22_long,
                          par == "chla"),
            size = 4, pch = 8, stroke = 2) +
  ggsci::scale_color_jama(labels = c(expression(Chl[Discrete]),
                                         expression(Chl[BUOY]),
                                         expression(Salinity[BUOY]),
                                     expression(Temp[BUOY]))) +
  scale_x_date(limits = as_date(c("2022-08-01", "2022-09-01")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
                       paste("Salinity,"~"Temp")))) +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
```

```{r}
b22_long %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  annotate("rect", xmin = date("2024-03-05"), xmax = date("2024-04-30"),
           ymin = 0, ymax = Inf, fill = 'darkgreen', alpha = 0.2) +
  geom_line(data = filter(b22_long,
                          par == "fl_med_day"),
            size = 2) +
  geom_line(data = filter(b22_long,
                          par == "mean_sal"),
            size = 2) +
  geom_line(data = filter(b22_long,
                          par == "mean_temp"),
            size = 2) +
  geom_point(data = filter(b22_long,
                          par == "chla"),
            size = 4, pch = 8, stroke = 2) +
  ggsci::scale_color_jama(labels = c(expression(Chl[Discrete]),
                                         expression(Chl[BUOY]),
                                         expression(Salinity[BUOY]),
                                     expression(Temp[BUOY]))) +
  scale_x_date(limits = as_date(c("2022-08-01", "2022-09-01")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
                       paste("Salinity,"~"Temp")))) +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
```



```{r}
f2_24 <-
  b24_long %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  annotate("rect", xmin = date("2024-03-05"), xmax = date("2024-04-30"),
           ymin = 0, ymax = Inf, fill = 'darkgreen', alpha = 0.2) +
  geom_line(data = filter(b24_long,
                          par == "fl_med_day"),
            size = 2) +
  geom_line(data = filter(b24_long,
                          par == "mean_sal"),
            size = 2) +
  geom_line(data = filter(b24_long,
                          par == "mean_temp"),
            size = 2) +
  geom_point(data = filter(b24_long,
                          par == "chla"),
            size = 4, pch = 8, stroke = 2) +
  ggsci::scale_color_jama(labels = c(expression(Chl[Discrete]),
                                         expression(Chl[BUOY]),
                                         expression(Salinity[BUOY]),
                                     expression(Temp[BUOY]))) +
  scale_x_date(limits = as_date(c("2024-08-01", "2024-09-01")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
                       paste("Salinity,"~"Temp")))) +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "right",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank())
```

```{r}
wfb <- ggarrange(f1_22, f1_24, fd_22, fd_24, f2_22, f2_24, ncol = 2)

  

ggsave(here("figures", "panel_kc10_w_f_b_Aug.png"), wfb,
        width = 24, height = 12, dpi = 300)
```



```{r}

#Setting plotting order phytoplankton groups

#Order phytoplankton groups roughly from smallest to largest - create order list
order_chem <- c("cyan", "hapt", "GA", "cryp",
                   "dino", "raph", "dict", "diat")

#Chemtax full data - Specify order of phyto groups for figures
chem_tchla <- arrange(mutate(chem_tchla,
                                group = factor(group,
                                levels = order_chem)))


```

```{r}
# f5 <- 
  
chem_tchla %>%
  ggplot() +
  geom_bar(aes(date, contribution, fill = fct_rev(group)),
           position = "stack", stat = "identity",
           alpha = 1, color = "black", size = 1) +
  ggsci::scale_fill_npg() +
  scale_x_date(limits = as.Date(c("2019-01-01", "2024-12-31")),
               expand = c(0, 0),
               date_breaks = "years", date_labels = "%Y") +
  theme_bw() +
  labs(y = bquote("Phyto. (mg" ~ m^-3*")"),
       fill = "Group") +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
        # axis.text.y = element_blank())

ggsave(here("figures", "chemtax_19-24.png"),
        width = 16, height = 6, dpi = 300)
```
```{r}
test <- weath %>% 
  select(date, Q_Total) %>% 
  filter(!is.na(Q_Total)) %>% 
  mutate(yday = yday(date),
         year = year(date)) %>% 
  group_by(yday) %>% 
  mutate(mean = mean(Q_Total)) %>% 
  ungroup()

test %>% 
  filter(year == 2020) %>% 
  ggplot() +
  geom_line(aes(x = yday, y = mean)) +
  geom_line(aes(x = yday, y = Q_Total, color = as.factor(year)))

```




```{r}
#Now plot 2024 CTD profiles
# f2 <- 
  
# f4 <- 
  
# f3 <-  
# https://cran.r-project.org/web/packages/palr/vignettes/nasa_chla.html
maxrange <- c(0.01, 35)
pal <- chl_pal(palette = TRUE)
sb <- which(pal$breaks >= maxrange[1] & pal$breaks <= maxrange[2])


f22_plot <- f22 %>% 
  select(date, pres, f_npq)

f22_plot <- rbind(f22_plot, interp)

  
f3 <-
  f22_plot %>% 
  filter(pres < 51) %>% 
  mutate(day = 15,
         year = year(date),
         month = month(date)) %>% 
  unite(date_2, c(year, month, day), sep = "-", remove = F) %>% 
  mutate(date_2 = date(date_2)) %>% 
  ggplot(aes(x = date)) +
  geom_tile(aes(y = pres, fill = f_npq)) +
  # geom_vline(xintercept = as_date("2024-03-18"),
  #            linetype = "solid", size = 1, color = "white") +
  geom_hline(yintercept = 5,
             linetype = "dashed", size = 1, color = "white") +
  # annotate("text", x = as.Date("2024-01-15"), y = 5,
  #          label = "c)",
  #          size = 10) +
  # annotate("text", x = as.Date("2024-11-19"), y = 9,
  #          label = "5m",
  #          size = 10,
  #          color = "white") +
  scale_y_reverse(breaks = seq(0, 50, by = 10)) +
  # cmocean::scale_fill_cmocean(name = "delta",
  #                             limits = c(0, 20),
  #                             oob = scales::squish) +
  scale_fill_viridis_c(limits = c(0, 30),
                       oob = scales::squish) +
  #   scale_fill_gradientn(
  #   colours = oce::oceColors9A(120),
  #   breaks = c(0, 10, 20, 30),
  #   limits = c(0, 35),
  # ) +
  # scale_fill_gradient2(low = "blue",
  #                      mid = "green",
  #                      high = "red",
  #                      midpoint = 5) +
  labs(fill = bquote(CTD[FLU]~"(mg" ~ m^-3*")"),
       y = "Depth") +
  scale_x_date(limits = as_date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        legend.position = "right",
        legend.key.height = unit(1.8, "cm"),
        legend.title = element_text(size = 30, angle = 270),
        legend.title.align = 0.5,
        legend.direction = "vertical",
        axis.text.x = element_blank()
        ) +
    guides(fill = guide_colourbar(title.position = "right"))

  # theme(text = element_text(size = 35), #35
  #       axis.text = element_text(color = "black"),
  #       axis.title.x = element_blank(),
  #       legend.position = "top",
  #       legend.box = "horizontal") +
  # guides(fill = guide_colourbar(title.position = "top", title.hjust = 0.5,
  #                               barwidth = 50, barheight = 1,
  #                               frame.colour = "black", ticks.colour = "black"))
```


```{r}

#Setting plotting order phytoplankton groups

#Order phytoplankton groups roughly from smallest to largest - create order list
order_chem <- c("cyan", "hapt", "GA", "cryp",
                   "dino", "raph", "dict", "diat")

#Chemtax full data - Specify order of phyto groups for figures
chem_tchla <- arrange(mutate(chem_tchla,
                                group = factor(group,
                                levels = order_chem)))


```

```{r}
# f5 <- 
  
f4 <- chem_tchla %>%
  ggplot() +
  # annotate("rect", xmin = date("2024-03-05"), xmax = date("2024-04-30"),
  #          ymin = 0, ymax = Inf, fill = 'darkgreen', alpha = 0.2) +
  geom_bar(aes(date, contribution, fill = fct_rev(group)),
           position = "stack", stat = "identity",
           alpha = 1, color = "black", size = 1) +
  # geom_vline(xintercept = as_date("2024-03-18"),
  #            linetype = "solid", size = 1, color = "black") +
  # annotate("text", x = as.Date("2024-01-15"), y = 5.4,
  #          label = "d)",
  #          size = 10) +
  # annotate("text", x = as.Date("2024-12-15"), y = 5.4,
  #          label = "5m",
  #          size = 10) +
  ggsci::scale_fill_npg() +
  # lims(y = c(0, 5)) +
  scale_x_date(limits = as.Date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Phyto. (mg" ~ m^-3*")"),
       fill = "Group") +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
        # axis.text.y = element_blank())
```

```{r}
# test2 <- ggarrange(f1, f2, f3, f4, ncol = 1)
# 
#   
# 
# ggsave(here("figures", "panel_kc10_2022_CHEMTAX_2.png"), test2,
#         width = 16, height = 16, dpi = 300)
```
```{r}
wind_22_24 <- wind %>% 
  filter(year == 2022 | year == 2024) %>% 
  mutate(yday = yday(date))

  ggplot() + 
  geom_line(data = wind_22_24, aes(x = yday, y = WindSpd_Med^3,
                               color = as.factor(year)),
            size = 2) +
  ggsci::scale_color_aaas() +
  labs(y = bquote(Wind~"("*m^-3*s^-3*")"),
       color = NULL) +
  facet_grid(year~.) +
  # scale_x_date(limits = as_date(c("2022-01-01", "2022-12-31")),
  #              expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  theme(text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        legend.position = "none")

ggsave(here("figures", "panel_kc10_2022_2024_wind.png"), 
        width = 16, height = 10, dpi = 300)  
```
```{r}
# Order locations from fjord to shelf
riv_loc <- c("Q_GM",
             "Q_SM",
             "Q_RA",
             "Q_tot")

q <- arrange(mutate(q, 
                      Watershed_group = factor(Watershed_group,
                                               levels = riv_loc)))
```

```{r}
f5 <- q %>% 
  filter(year == 2022) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_uchicago() +
  scale_x_date(limits = as.Date(c("2022-01-01", "2022-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
        # axis.text.y = element_blank())
```

```{r}
# test3 <- ggarrange(f1, f2, f5, ncol = 1)
# 
#   
# 
# ggsave(here("figures", "panel_kc10_2022_CHEMTAX_2_FW.png"), test3,
#         width = 16, height = 12, dpi = 300)
```
```{r}

f6 <- q %>% 
  filter(year == 2024) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_uchicago() +
  scale_x_date(limits = as.Date(c("2024-01-01", "2024-12-31")),
               expand = c(0, 0),
               date_breaks = "months", date_labels = "%b") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "right",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
        # axis.text.y = element_blank())

```
```{r}
test4 <- ggarrange(f5, f6, ncol = 1)

  

ggsave(here("figures", "panel_kc10_2022_2024_Q.png"), test4,
        width = 16, height = 8, dpi = 300)
```

```{r}
b22 %>% 
  left_join(wind22) %>% 
  mutate(month = month(date)) %>% 
  filter(month == 8) %>% 
  ggplot(aes(x = mean_sal, y = fl_med_day)) +
  geom_point() +
  scale_color_viridis_b()
```

```{r}
b22_long %>% 
  filter(par == "fl_med_day") %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  geom_point() +
  geom_line(size = 2) +
  ylim(0, 10) +
  # geom_line(data = filter(b22_long,
  #                         par == "fl_med_day"),
  #           size = 2) +
  # geom_line(data = filter(b22_long,
  #                         par == "mean_sal"),
  #           size = 2) +
  # geom_line(data = filter(b22_long,
  #                         par == "mean_temp"),
  #           size = 2) +
  # geom_point(data = filter(b22_long,
  #                         par == "chla"),
  #           size = 4, pch = 8, stroke = 2) +
  scale_x_date(limits = as_date(c("2022-07-01", "2022-07-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  # ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
  #                      paste("Salinity,"~"Temp")))) +
  # facet_wrap(~par, ncol = 1, scales = "free") +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())

ggsave(here("figures", "test.png"),
        width = 24, height = 16, dpi = 300)
```
```{r}
b22_long %>% 
  filter(par == "mean_temp") %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  geom_point() +
  geom_line(size = 2) +
  ylim(8, 18) +
  # geom_line(data = filter(b22_long,
  #                         par == "fl_med_day"),
  #           size = 2) +
  # geom_line(data = filter(b22_long,
  #                         par == "mean_sal"),
  #           size = 2) +
  # geom_line(data = filter(b22_long,
  #                         par == "mean_temp"),
  #           size = 2) +
  # geom_point(data = filter(b22_long,
  #                         par == "chla"),
  #           size = 4, pch = 8, stroke = 2) +
  scale_x_date(limits = as_date(c("2022-07-01", "2022-07-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  # ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
  #                      paste("Salinity,"~"Temp")))) +
  # facet_wrap(~par, ncol = 1, scales = "free") +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
```
```{r}
b22_long %>% 
  filter(par == "mean_sal") %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val, color = par)) +
  geom_point() +
  geom_line(size = 2) +
  ylim(16, 28) +
  # geom_line(data = filter(b22_long,
  #                         par == "fl_med_day"),
  #           size = 2) +
  # geom_line(data = filter(b22_long,
  #                         par == "mean_sal"),
  #           size = 2) +
  # geom_line(data = filter(b22_long,
  #                         par == "mean_temp"),
  #           size = 2) +
  # geom_point(data = filter(b22_long,
  #                         par == "chla"),
  #           size = 4, pch = 8, stroke = 2) +
  scale_x_date(limits = as_date(c("2022-07-01", "2022-07-31")),
               expand = c(0, 0),date_breaks = "months", date_labels = "%b") +
  # ylab(expression(atop(Chl~"(mg" ~ m^-3*")",
  #                      paste("Salinity,"~"Temp")))) +
  # facet_wrap(~par, ncol = 1, scales = "free") +
  labs(color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())
```

```{r}
s1 <- b22_long %>% 
  filter(par == "fl_med_day") %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val)) +
  geom_point() +
  geom_line(size = 3) +
  geom_vline(xintercept = as.Date("2022-07-03")) +
  geom_vline(xintercept = as.Date("2022-07-28")) +
  ylim(0, 10) +
  scale_x_date(limits = as_date(c("2022-07-01", "2022-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
  labs(y = bquote(Chl[BUOY]~"(mg" ~ m^-3*")"),
                  color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```

```{r}
s2 <- b22_long %>% 
  filter(par == "mean_temp") %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val)) +
  geom_point() +
  geom_line(size = 3) +
  geom_vline(xintercept = as.Date("2022-07-03")) +
  geom_vline(xintercept = as.Date("2022-07-28")) +
  ylim(11, 18) +
  scale_x_date(limits = as_date(c("2022-07-01", "2022-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
  labs(y = "Temp",
       color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```
```{r}
s3 <- b22_long %>% 
  filter(par == "mean_sal") %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val)) +
  geom_point() +
  geom_line(size = 3) +
  geom_vline(xintercept = as.Date("2022-07-03")) +
  geom_vline(xintercept = as.Date("2022-07-28")) +
  ylim(16, 28) +
  scale_x_date(limits = as_date(c("2022-07-01", "2022-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
    labs(y = "Salinity",
       color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```
```{r}
s4 <- wh %>%
  ggplot() + 
  geom_point(aes(x = date, y = WindSpd_Avg, fill = WindDir_Avg),
            pch = 21, size = 6, color = "transparent") +
  scale_fill_viridis_b() +
  geom_vline(xintercept = as_datetime("2022-07-03")) +
  geom_vline(xintercept = as_datetime("2022-07-28")) +
  ylim(0, 12) +
  labs(y = bquote(Wind~"("*m*s^-1*")"),
       fill = "Dir.") +
  scale_x_datetime(limits = as_datetime(c("2022-07-01", "2022-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
  theme_bw() +
  theme(legend.position = c(0.95, 0.75),
        legend.background = element_blank(),
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```
```{r}
s5 <- q %>% 
  filter(year == 2022) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  geom_vline(xintercept = as.Date("2022-07-03")) +
  geom_vline(xintercept = as.Date("2022-07-28")) +
  scale_fill_uchicago() +
  scale_x_date(limits = as_date(c("2022-07-01", "2022-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "none",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```
```{r}

s6 <- p %>% 
  ggplot(aes(x = date, y = `1hourPAR`)) +
  geom_point() +
  geom_line(size = 3) +
  geom_vline(xintercept = as_datetime("2022-07-03")) +
  geom_vline(xintercept = as_datetime("2022-07-28")) +
  scale_x_datetime(limits = as_datetime(c("2022-07-01", "2022-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
    labs(y = bquote("PAR" ~ "("*mol~m^2*")"),
       color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())

```
```{r}
s_fig <- s1 / s2 / s3 / s4 / s5 / s6

ggsave(here("figures", "panel_kc10_2022_July.png"), s_fig,
        width = 16, height = 24, dpi = 300)
```

```{r}
f <- f %>% 
  mutate(year = year(date),
         month = month(date))

p1 <- f %>% 
  filter(year == 2022 & month == 7 & station == "KC10") %>% 
  ggplot(aes(x = f_npq, y = pres, color = as.factor(date))) +
  geom_line(size = 3, orientation = "y") +
      labs(x = bquote("FL" ~ "("*mg~m^3*")"),
           y = "Depth (m)",
           color = NULL) +
  scale_y_reverse() +
  ylim(30, 0) +
  scale_color_npg() +
  theme_bw() +
  theme(legend.position = c(0.7, 0.2),
        text = element_text(size = 40), #35
        axis.text = element_text(color = "black"))
  
```
```{r}
ctd2 <- ctd %>% 
  mutate(date = mdy(date),
         year = year(date),
         month = month(date))

p2 <- ctd2 %>% 
  filter(year == 2022 & month == 7) %>% 
  ggplot(aes(x = temp, y = pres, color = as.factor(date))) +
  geom_line(size = 3, orientation = "y") +
      labs(x = "Temp",
           y = "Depth (m)",
       color = NULL) +
  scale_y_reverse() +
  ylim(30, 0) +
  scale_color_npg() +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 40), #35
        axis.text = element_text(color = "black"))
  
```
```{r}
p3 <- ctd2 %>% 
  filter(year == 2022 & month == 7) %>% 
  ggplot(aes(x = sal, y = pres, color = as.factor(date))) +
  geom_line(size = 3, orientation = "y") +
      labs(x = "Salinity",
           y = "Depth (m)",
       color = NULL) +
  scale_y_reverse() +
  ylim(30, 0) +
  scale_color_npg() +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 40), #35
        axis.text = element_text(color = "black"))
```
```{r}
p4 <- ctd2 %>% 
  filter(year == 2022 & month == 7) %>% 
  ggplot(aes(x = N2, y = pres, color = as.factor(date))) +
  geom_line(size = 3, orientation = "y") +
      labs(x = "N2",
           y = "Depth (m)",
       color = NULL) +
  scale_y_reverse() +
  ylim(30, 0) +
  scale_color_npg() +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 40), #35
        axis.text = element_text(color = "black"))
```
```{r}
fig_prof <- p1 + p2 + p3 + p4

ggsave(here("figures", "panel_profiles_July_2022.png"), fig_prof,
        width = 16, height = 22, dpi = 300)
```



```{r}
sal_max <- b22_long %>%
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(year == 2022 & month == 7) %>% 
  filter(par == "mean_sal") 
```

```{r}
# Calculate halocline depth based on maximum salinity gradient
# Assumes data frame with columns: cast_id, depth, salinity

library(tidyverse)

# Function to calculate halocline depth for a single cast
calculate_halocline <- function(df, max_depth = 20, min_gradient = -0.1) {
  # Sort by depth and limit search to upper water column
  df <- df %>% 
    arrange(depth) %>%
    filter(depth <= max_depth)
  
  # Need at least 3 points to calculate meaningful gradients
  if(nrow(df) < 3) {
    return(tibble(halocline_depth = NA_real_, max_sal_gradient = NA_real_))
  }
  
  # Calculate salinity gradient (dS/dz)
  df <- df %>%
    mutate(
      depth_diff = lead(depth) - depth,
      salinity_diff = lead(salinity) - salinity,
      sal_gradient = salinity_diff / depth_diff
    ) %>%
    # Remove last row (NA from lead()) and any infinite values
    filter(!is.na(sal_gradient), is.finite(sal_gradient))
  
  # Check if we have any data left
  if(nrow(df) == 0) {
    return(tibble(halocline_depth = NA_real_, max_sal_gradient = NA_real_))
  }
  
  # Find depths with significant negative gradients (halocline indicators)
  strong_gradients <- df %>%
    filter(sal_gradient <= min_gradient)
  
  if(nrow(strong_gradients) > 0) {
    # Take the strongest gradient among the significant ones
    halocline_idx <- which.min(strong_gradients$sal_gradient)
    halocline_depth <- strong_gradients$depth[halocline_idx]
    gradient_strength <- strong_gradients$sal_gradient[halocline_idx]
  } else {
    # No strong halocline found - return the strongest available gradient
    max_grad_idx <- which.min(df$sal_gradient)
    halocline_depth <- df$depth[max_grad_idx]
    gradient_strength <- df$sal_gradient[max_grad_idx]
  }
  
  return(tibble(
    halocline_depth = halocline_depth,
    max_sal_gradient = gradient_strength
  ))
}

# Apply to multiple casts (searching top 20m)
ctd_haloclines <- ctd2 %>%
  select(date, depth = pres, salinity = sal) %>% 
  group_by(date) %>%
  do(calculate_halocline(., max_depth = 20, min_gradient = -0.1)) %>%
  ungroup()


# If you want to add halocline info back to original data
# ctd_with_halocline <- ctd_data %>%
#   left_join(ctd_haloclines, by = "cast_id")

# Quality control: flag weak haloclines or missing data
ctd_haloclines_qc <- ctd_haloclines %>%
  mutate(
    halocline_strength = case_when(
      is.na(max_sal_gradient) ~ "no_data",
      max_sal_gradient > -0.05 ~ "weak",    # adjusted for your salinity range
      max_sal_gradient <= -0.05 ~ "strong"
    )
  )

# Summary by halocline strength
halocline_summary <- ctd_haloclines_qc %>%
  group_by(halocline_strength) %>%
  summarise(
    n_casts = n(),
    mean_depth = mean(halocline_depth, na.rm = TRUE),
    sd_depth = sd(halocline_depth, na.rm = TRUE),
    .groups = "drop"
  )
```

```{r}
ctd_haloclines %>% 
  mutate(month  = month(date),
         year = year(date)) %>% 
  ggplot(aes(x = as.factor(month), y = halocline_depth)) +
  geom_boxplot() +
  geom_point(aes(fill = as.factor(year)), pch = 21, size = 4) +
  scale_y_reverse()
```
```{r}
# Simple BC Wind Stress Calculator - Start to Finish
# Using Smith et al. (1991) HEXOS drag coefficient

library(dplyr)

# Function to calculate wind components from speed and direction
calculate_wind_components <- function(wind_speed, wind_direction_deg) {
  wind_dir_rad <- wind_direction_deg * pi / 180
  
  u_wind <- -wind_speed * sin(wind_dir_rad)  # east-west component
  v_wind <- -wind_speed * cos(wind_dir_rad)  # north-south component
  
  return(data.frame(u_wind = u_wind, v_wind = v_wind))
}

# Function to calculate wind stress using Smith drag coefficient
calculate_wind_stress <- function(u_wind, v_wind) {
  # BC air density
  rho_air <- 1.24  # kg/m³
  
  # Wind speed
  wind_speed <- sqrt(u_wind^2 + v_wind^2)
  
  # Smith et al. (1991) drag coefficient
  CD <- (0.61 + 0.063 * wind_speed) * 1e-3
  
  # Wind stress components (N/m²)
  tau_x <- rho_air * CD * wind_speed * u_wind  # east-west stress
  tau_y <- rho_air * CD * wind_speed * v_wind  # north-south stress
  
  return(data.frame(tau_x = tau_x, tau_y = tau_y))
}

# Main processing function
process_wind_data <- function(data) {
  
  # Sort data by datetime to ensure proper time order
  data <- data %>% arrange(datetime)
  
  # Calculate wind components
  wind_components <- calculate_wind_components(data$wind_speed, data$wind_direction)
  
  # Calculate wind stress
  wind_stress <- calculate_wind_stress(wind_components$u_wind, wind_components$v_wind)
  
  # Combine everything
  results <- data %>%
    bind_cols(wind_components) %>%
    bind_cols(wind_stress) %>%
    mutate(
      # Convert to hourly wind stress (multiply by seconds per hour)
      hourly_tau_y = tau_y * 3600,
      
      # Add year for grouping
      year = format(datetime, "%Y"),
      
      # Calculate cumulative north-south wind stress (overall)
      cumulative_tau_y = cumsum(hourly_tau_y)
    ) %>%
    
    # Calculate annual cumulative wind stress (resets each year)
    group_by(year) %>%
    mutate(
      annual_cumulative_tau_y = cumsum(hourly_tau_y)
    ) %>%
    ungroup()
  
  return(results)
}

# ===== APPLY TO YOUR DATA =====

# Load your hourly data (adjust filename and column names as needed)
# your_data <- read.csv("your_hourly_wind_file.csv")
# your_data$datetime <- as.POSIXct(your_data$datetime)

# Example with multi-year hourly sample data (replace with your actual data)
# Uncomment the lines below and replace with your data loading

# Sample multi-year hourly data for demonstration
sample_data <- wh %>% 
  select(datetime = date, wind_speed = WindSpd_Avg, wind_direction = WindDir_Avg)

# Process the data
results <- process_wind_data(sample_data)


```



```{r}
results %>%
  ggplot() + 
  geom_line(aes(x = datetime, y = tau_y)) +
  # geom_vline(xintercept = as_date("2024-07-03")) +
  # geom_vline(xintercept = as_date("2024-07-28")) +
  # labs(y = bquote(Wind Stress~"("*m*s^-1*")"),
  #      fill = "Dir.") +
  scale_x_datetime(limits = as_datetime(c("2024-01-01", "2024-12-01")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
  theme_bw() +
  theme(legend.position = c(0.95, 0.75),
        legend.background = element_blank(),
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```
```{r}
ws_cs <- results %>% 
  filter(!is.na(hourly_tau_y)) %>% 
  mutate(year = year(datetime)) %>% 
  group_by(year) %>% 
  mutate(cs = cumsum(tau_y)) %>%
  ungroup()

ws_cs %>% 
  filter(year == 2022) %>% 
  mutate(yday = yday(datetime)) %>% 
  ggplot(aes(x = datetime, y = cs, color = as.factor(year))) +
  geom_line() 

```

```{r}
s24_1 <- b24_long %>% 
  filter(par == "fl_med_day") %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val)) +
  geom_point() +
  geom_line(size = 3) +
  geom_vline(xintercept = as.Date("2022-07-03")) +
  geom_vline(xintercept = as.Date("2022-07-28")) +
  ylim(0, 12) +
  scale_x_date(limits = as_date(c("2024-07-01", "2024-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
  labs(y = bquote(Chl[BUOY]~"(mg" ~ m^-3*")"),
                  color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```

```{r}
s24_2 <- b24_long %>% 
  filter(par == "mean_temp") %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val)) +
  geom_point() +
  geom_line(size = 3) +
  geom_vline(xintercept = as.Date("2022-07-03")) +
  geom_vline(xintercept = as.Date("2022-07-28")) +
  ylim(10, 18) +
  scale_x_date(limits = as_date(c("2024-07-01", "2024-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
  labs(y = "Temp",
       color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```
```{r}
s24_3 <- b24_long %>% 
  filter(par == "mean_sal") %>% 
  mutate(month = month(date)) %>% 
  ggplot(aes(x = date, y = val)) +
  geom_point() +
  geom_line(size = 3) +
  geom_vline(xintercept = as.Date("2022-07-03")) +
  geom_vline(xintercept = as.Date("2022-07-28")) +
  ylim(16, 31) +
  scale_x_date(limits = as_date(c("2024-07-01", "2024-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
    labs(y = "Salinity",
       color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```
```{r}
s24_4 <- wh %>%
  ggplot() + 
  geom_point(aes(x = date, y = WindSpd_Avg, fill = WindDir_Avg),
            pch = 21, size = 6, color = "transparent") +
  scale_fill_viridis_b() +
  geom_vline(xintercept = as_datetime("2022-07-03")) +
  geom_vline(xintercept = as_datetime("2022-07-28")) +
  ylim(0, 12) +
  labs(y = bquote(Wind~"("*m*s^-1*")"),
       fill = "Dir.") +
  scale_x_datetime(limits = as_datetime(c("2024-07-01", "2024-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
  theme_bw() +
  theme(legend.position = c(0.95, 0.75),
        legend.background = element_blank(),
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```
```{r}
s24_5 <- q %>% 
  filter(year == 2024) %>% 
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  geom_vline(xintercept = as.Date("2022-07-03")) +
  geom_vline(xintercept = as.Date("2022-07-28")) +
  scale_fill_uchicago() +
  scale_x_date(limits = as_date(c("2024-07-01", "2024-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
  theme_bw() +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  ylim(0, 5) +
  theme(
        legend.position = "none",
        # legend.position = c(1.02, 0.5),
        legend.key.height = unit(0.5, "cm"),
        # legend.text = element_text(size = 25),
        legend.title = element_blank(),
        text = element_text(size = 38), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```
```{r}

s24_6 <- p %>% 
  ggplot(aes(x = date, y = `1hourPAR`)) +
  geom_point() +
  geom_line(size = 3) +
  geom_vline(xintercept = as_datetime("2022-07-03")) +
  geom_vline(xintercept = as_datetime("2022-07-28")) +
  scale_x_datetime(limits = as_datetime(c("2024-07-01", "2024-08-05")),
               expand = c(0, 0), date_breaks = "1 week",
               date_labels = "%b%d") +
    labs(y = bquote("PAR" ~ "("*mol~m^2*")"),
       color = NULL) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())

```
```{r}
s24_fig <- s24_1 / s24_2 / s24_3 / s24_4 / s24_5 / s24_6

ggsave(here("figures", "panel_kc10_2024_July.png"), s24_fig,
        width = 16, height = 24, dpi = 300)
```