---
title: "R Notebook"
output: html_notebook
---

This worksheet works on created a corrected chlorophyll fluorometer time-series through comparison with discrete chlorophyll samples.

```{r}
#Upload packages
library(tidyverse) #wrangling
library(here) #file management
library(readxl) #reading excel files
library(lubridate) #working with dates and time

#Plotting
library(ggsci) #Nice color schemes
library(patchwork) #plotting panels
library(egg) #Similar to patchwork but better with right y-axis

#Interpolation
# library(rioja) # add fits to discrete data


# library(MBA)
# library(mgcv)
# library(FNN)
# library(zoo)
# library(reshape2)

# library(egg)


library(castr)
```

```{r}
c <- read_csv(here("files", "2025-06-02_HakaiData_chlorophyll.csv"))

c_join2 <- read_csv(here("outputs", "chl_combined_fzh_kc10.csv"))

#Upload data from my master data standardization sheet
micro <- read_csv(here("files", "research_kc10_2025-05-28_2.csv")) 

#POMs
pom <- read_csv(here("files", "2025-06-03_HakaiData_poms.csv")) 

#fecal
fec <- read_csv(here("files", "fecal.csv")) 

#CHEMTAX
chem <- read_csv(here("files", "chemtax_kc10_2024.csv"))

#CHEMTAX
par <- read_csv(here("outputs", "corrected_par_2025-06-03.csv"))

#CHEMTAX
ctd <- read_csv(here("outputs", "ctd_wrangle_2025-04-25_kc10.csv"))

#env
ctd2 <- read_csv(here("outputs", "enviro_ctd_nut_2025-04-15.csv"))

f <- read_csv(here("outputs", "corrected_flu_2025-05-09.csv"))

```

```{r}
int50 <- f %>% 
  filter(pres < 51) %>% 
  group_by(id, date, station) %>% 
  summarise(int_50 = sum(f_npq)) %>% 
  ungroup()

int50_dm <- int50 %>%
  mutate(month = month(date),
         year = year(date)) %>% 
  group_by(year, month) %>% 
  summarise(int_50 = mean(int_50)) %>% 
  ungroup() 

stats_month <- int50_dm %>% 
  group_by(month) %>% 
  summarise(n = n()) %>% 
  ungroup()

stats_year <- int50_dm %>% 
  group_by(year) %>% 
  summarise(n = n()) %>% 
  ungroup()

decomp <- int50_dm %>% 
  filter(year > 2015)
```




```{r}
ac <- decomp %>% 
  mutate(ltm = mean(int_50)) %>% 
  group_by(year) %>% 
  mutate(am = mean(int_50)) %>% 
  ungroup() %>% 
  select(year, am, ltm) %>% 
  distinct() %>% 
  mutate(ac = am/ltm)

sd_ac <- ac %>% 
  summarise(sd = sd(ac))

mc <- decomp %>% 
  mutate(ltm = mean(int_50)) %>% 
  group_by(year) %>% 
  mutate(am = mean(int_50)) %>% 
  mutate(month_dev = int_50/am) %>%
  ungroup() %>% 
  group_by(month) %>%
  summarise(seasonal_factor = mean(month_dev, na.rm = TRUE), .groups = 'drop')

sd_mc <- mc %>% 
  summarise(sd = sd(seasonal_factor))

ev <- decomp %>% 
  mutate(ltm = mean(int_50)) %>% 
  group_by(year) %>% 
  mutate(am = mean(int_50)) %>% 
  mutate(month_dev = int_50/am) %>%
  ungroup() %>% 
  group_by(month) %>%
  mutate(month_mean = mean(month_dev, na.rm = TRUE), .groups = 'drop') %>% 
  ungroup() %>% 
  group_by(year, month) %>% 
  summarise(resids = month_dev/month_mean)
  
```
```{r}
ac %>% 
  ggplot(aes(x = as.factor(year), y = ac)) +
  geom_col()

mc %>% 
  ggplot(aes(x = as.factor(month), y = seasonal_factor)) +
  geom_col()

ev %>% 
  ggplot(aes(x = as.factor(month), y = resids)) +
  geom_col() +
  facet_wrap(~year)
```
```{r}
c_join2 <- c_join2 %>%
  mutate(month = month(date),
         year = year(date)) %>% 
  mutate(month = case_when(date == "2022-07-28" ~ 8,
                               date == "2017-08-31" ~ 9,
                               date == "2017-04-28" ~ 5,
                               T ~ as.numeric(month)))

c_stat <- c_join2 %>%
  filter(pres < 11) %>%
  group_by(month, year, pres) %>% 
  summarise(chl_comb = mean(chl_comb)) %>% 
  ungroup() %>% 
  group_by(year, pres) %>% 
  summarise(n = n()) %>% 
  ungroup()
```

```{r}

decomp_c <- c_join2 %>% 
  filter(year > 2014)

```


```{r}
ac_c <- decomp_c %>%
  filter(pres < 11) %>% 
  group_by(pres) %>% 
  mutate(ltm = mean(chl_comb)) %>% 
  ungroup() %>% 
  group_by(year, pres) %>% 
  mutate(am = mean(chl_comb)) %>% 
  ungroup() %>% 
  select(year, pres, am, ltm) %>% 
  distinct() %>% 
  mutate(ac = am/ltm)

mc_c <- decomp_c %>%
  filter(pres < 11) %>% 
  group_by(pres) %>%
  mutate(ltm = mean(chl_comb)) %>% 
  ungroup() %>% 
  group_by(year, pres) %>% 
  mutate(am = mean(chl_comb)) %>% 
  mutate(month_dev = chl_comb/am) %>%
  ungroup() %>% 
  group_by(month, pres) %>%
  summarise(seasonal_factor = mean(month_dev, na.rm = TRUE), .groups = 'drop')

ev_c <- decomp_c %>% 
  filter(pres < 11) %>% 
  group_by(pres) %>%
  mutate(ltm = mean(chl_comb)) %>% 
  ungroup() %>%  
  group_by(year, pres) %>% 
  mutate(am = mean(chl_comb)) %>% 
  mutate(month_dev = chl_comb/am) %>%
  ungroup() %>% 
  group_by(month, pres) %>%
  mutate(month_mean = mean(month_dev, na.rm = TRUE), .groups = 'drop') %>% 
  ungroup() %>% 
  group_by(year, month, pres) %>% 
  summarise(resids = month_dev/month_mean)
  
```
```{r}
ac_c %>% 
  ggplot(aes(x = as.factor(year), y = ac, fill = as.factor(pres))) +
  geom_col() +
  facet_wrap(~pres, ncol = 1) +
  scale_fill_npg() +
  labs(y = "Annual Component",
       x = NULL,
       fill = "Depth (m)") +
  theme_light() +
  theme(
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())

ggsave(here("figures", "annual_component.png"),
        width = 16, height = 10, dpi = 300)
```


```{r}
mc_c %>% 
  ggplot(aes(x = as.factor(month), y = seasonal_factor, fill = as.factor(pres))) +
  geom_col() +
  facet_wrap(~pres, ncol = 1) +
  scale_fill_npg() +
  labs(y = "Seasonal Component",
       x = NULL,
       fill = "Depth (m)") +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank())

ggsave(here("figures", "seasonal_component.png"),
        width = 16, height = 10, dpi = 300)
```


```{r}
ev_c %>% 
  filter(pres == 5) %>% 
  ggplot(aes(x = as.factor(month), y = resids, fill = as.factor(pres))) +
  geom_col() +
  facet_wrap(~year)
```


```{r}
d_dr <- ctd2 %>% 
  select(date, dr_dm) %>% 
  distinct() %>% 
  mutate(year = year(date),
         month = month(date)) %>% 
  group_by(month, year) %>% 
  summarise(dr_dm = mean(dr_dm, na.rm = T)) %>% 
  ungroup()


ac_dr <- d_dr %>%
  mutate(ltm = mean(dr_dm, na.rm = T)) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(am = mean(dr_dm, na.rm = T)) %>% 
  ungroup() %>% 
  select(year, am, ltm) %>% 
  distinct() %>% 
  mutate(ac = am/ltm)

mc_dr <- d_dr %>%
  mutate(ltm = mean(dr_dm)) %>% 
  group_by(year) %>% 
  mutate(am = mean(dr_dm)) %>% 
  mutate(month_dev = dr_dm/am) %>%
  ungroup() %>% 
  group_by(month) %>%
  summarise(seasonal_factor = mean(month_dev, na.rm = TRUE), .groups = 'drop')

ev_dr <- d_dr %>% 
  mutate(ltm = mean(dr_dm)) %>% 
  group_by(year) %>% 
  mutate(am = mean(dr_dm)) %>% 
  mutate(month_dev = dr_dm/am) %>%
  ungroup() %>% 
  group_by(month) %>%
  mutate(month_mean = mean(month_dev, na.rm = TRUE), .groups = 'drop') %>% 
  ungroup() %>% 
  group_by(year, month) %>% 
  summarise(resids = month_dev/month_mean)
  
```

```{r}
ac_dr %>% 
  ggplot(aes(x = as.factor(year), y = ac)) +
  geom_col()

mc_dr %>% 
  ggplot(aes(x = as.factor(month), y = seasonal_factor)) +
  geom_col()

ev_dr %>% 
  ggplot(aes(x = as.factor(month), y = resids)) +
  geom_col() +
  facet_wrap(~year)
```


```{r}
d_t <- ctd2 %>% 
  select(date, pres, sal) %>% 
  filter(pres < 3) %>% 
  group_by(date) %>% 
  summarise(temp = mean(sal)) %>% 
  ungroup() %>% 
  mutate(year = year(date),
         month = month(date)) %>% 
  group_by(month, year) %>% 
  summarise(t_dm = mean(temp, na.rm = T)) %>% 
  ungroup()


ac_t <- d_t %>%
  mutate(ltm = mean(t_dm, na.rm = T)) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(am = mean(t_dm, na.rm = T)) %>% 
  ungroup() %>% 
  select(year, am, ltm) %>% 
  distinct() %>% 
  mutate(ac = am/ltm)

mc_t <- d_t %>%
  mutate(ltm = mean(t_dm)) %>% 
  group_by(year) %>% 
  mutate(am = mean(t_dm)) %>% 
  mutate(month_dev = t_dm/am) %>%
  ungroup() %>% 
  group_by(month) %>%
  summarise(seasonal_factor = mean(month_dev, na.rm = TRUE), .groups = 'drop')

ev_t <- d_t %>% 
  mutate(ltm = mean(t_dm)) %>% 
  group_by(year) %>% 
  mutate(am = mean(t_dm)) %>% 
  mutate(month_dev = t_dm/am) %>%
  ungroup() %>% 
  group_by(month) %>%
  mutate(month_mean = mean(month_dev, na.rm = TRUE), .groups = 'drop') %>% 
  ungroup() %>% 
  group_by(year, month) %>% 
  summarise(resids = month_dev/month_mean)
```
```{r}
ac_t %>% 
  ggplot(aes(x = as.factor(year), y = ac)) +
  geom_col()

mc_t %>% 
  ggplot(aes(x = as.factor(month), y = seasonal_factor)) +
  geom_col()

ev_t %>% 
  ggplot(aes(x = as.factor(month), y = resids)) +
  geom_col() +
  facet_wrap(~year)
```






```{r}
#Working with the discrete chlorophyll dataset

#Pulling out bulk data with appropriate flags and running a daily mean in case there are duplicates
c_qc <- c %>% 
  select(date, station = site_id, line_out_depth, filter_type, chla, chla_flag, phaeo) %>% 
  filter(filter_type == "Bulk GF/F") %>% 
  filter(chla_flag == "AV" | chla_flag == "SVC" | chla_flag == "ADL" | is.na(chla_flag)) 

#Calculating a daily mean value in case of duplicates and setting the 0m sampling depth to 1m to match with the closest CTD fluorometer record
c_dm <- c_qc %>% 
  group_by(date, station, line_out_depth) %>% 
  summarise(chl_dm = mean(chla),
            phaeo_dm = mean(phaeo)) %>% 
  ungroup() %>% 
  mutate(pres = round(line_out_depth)) %>%
  drop_na() %>% 
  group_by(date, station) %>% 
  mutate(n_dep = n()) %>% 
  ungroup() %>% 
  filter(n_dep >= 5) %>% 
  mutate(year = year(date)) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))
```

```{r}
#working with the size-fractionated dataset to create a size-fractionated sum value where we are missing bulk samples

#Pulling out size-fractionated data
c_sf <- c %>% 
  select(date, station = site_id, line_out_depth, filter_type, chla, chla_flag, phaeo) %>% 
  filter(!filter_type == "Bulk GF/F") %>% 
  filter(chla_flag == "AV" | chla_flag == "SVC" | chla_flag == "ADL" | is.na(chla_flag))

#Calculating a daily mean value where there are three filters available to complete the set.
c_sf_dm <- c_sf %>% 
  filter(!is.na(chla)) %>%
  filter(chla > 0) %>% 
  group_by(date, station, line_out_depth, filter_type) %>% 
  summarise(avg_chla = mean(chla),
            avg_phaeo = mean(phaeo)) %>%
  ungroup() %>% 
  group_by(date, station, line_out_depth) %>% 
  mutate(n_filt = n()) %>% 
  ungroup() %>% 
  group_by(date, station, line_out_depth, filter_type) %>% 
  mutate(n_type = n()) %>% 
  ungroup() %>% 
  filter(n_filt == 3 & n_type == 1) %>% 
  group_by(date, station, line_out_depth) %>% 
  mutate(sum = sum(avg_chla),
         sum_phaeo = sum(avg_phaeo)) %>% 
  ungroup() %>% 
  mutate(perc = avg_chla/sum,
         perc_phaeo = avg_phaeo/sum_phaeo) %>% 
  select(date, station, pres = line_out_depth, filter_type, avg_chla, sum, perc,
         avg_phaeo, sum_phaeo, perc_phaeo) %>% 
  mutate(filter_type2 = case_when(filter_type == "2um" ~ "3um",
                                  TRUE ~ as.character(filter_type))) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))

#Setting the 0m sampling depth to 1m
c_sum <- c_sf_dm %>% 
  distinct(sum, .keep_all = T) %>% 
  select(date, station, pres, sum, sum_phaeo) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))
```
```{r}
#Joining the bulk and size-fractionated sum and then creating combined column where the size-fractionated value is used where there are NA's for the bulk.
c_join <- c_dm %>% 
  full_join(c_sum) %>% 
  mutate(chl_comb = case_when(is.na(chl_dm) ~ sum,
                              !is.na(chl_dm) ~ chl_dm),
         phaeo_comb = case_when(is.na(phaeo_dm) ~ sum_phaeo,
                              !is.na(phaeo_dm) ~ phaeo_dm)) %>% 
  select(date, station, pres, chl_dm, chl_comb, phaeo_dm, phaeo_comb) %>% 
  mutate(month = month(date)) %>% 
  mutate(ph_chl = phaeo_comb/chl_comb)

c5 <- c_join %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(pres == 5) %>% 
  group_by(year, month) %>%
  summarise(chl = mean(chl_comb)) %>% 
  ungroup()
    
c5 <- c5 %>% 
  group_by(year) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n >= 8)

#A comparison of the bulk and SF sum should be plotted and offset applied if needed.
```

```{r}
ac <- c5 %>% 
  mutate(ltm = mean(chl)) %>% 
  group_by(year) %>% 
  mutate(am = mean(chl)) %>% 
  ungroup() %>% 
  select(year, am, ltm) %>% 
  distinct() %>% 
  mutate(ac = am/ltm)

mc <- c5 %>% 
  mutate(ltm = mean(chl)) %>% 
  group_by(year) %>% 
  mutate(am = mean(chl)) %>% 
  mutate(month_dev = chl/am) %>%
  ungroup() %>% 
  group_by(month) %>%
  summarise(seasonal_factor = mean(month_dev, na.rm = TRUE), .groups = 'drop')

ev <- c5 %>% 
  mutate(ltm = mean(chl)) %>% 
  group_by(year) %>% 
  mutate(am = mean(chl)) %>% 
  mutate(month_dev = chl/am) %>%
  ungroup() %>% 
  group_by(month) %>%
  mutate(month_mean = mean(month_dev, na.rm = TRUE), .groups = 'drop') %>% 
  ungroup() %>% 
  group_by(year, month) %>% 
  summarise(resids = month_dev/month_mean)
  
```

```{r}
ac %>% 
  ggplot(aes(x = as.factor(year), y = ac)) +
  geom_col()

mc %>% 
  ggplot(aes(x = as.factor(month), y = seasonal_factor)) +
  geom_col()

ev %>% 
  ggplot(aes(x = as.factor(month), y = resids)) +
  geom_col() +
  facet_wrap(~year)
```



```{r}


decomp.mult=function(x, startyr=NULL, endyr=NULL, event=T){ 
#R2.8.0 3/2/09 4:48 PM
  if(class(x)[1]!="mts")dim(x)=c(length(x),1)
  if(is.null(startyr)) startyr=start(x)[1]
  if(is.null(endyr)) endyr=end(x)[1]
  d=window(x, start=c(startyr,1), end=c(endyr,12), extend=T)
  results=vector("list",dim(d)[2]) 
  names(results)=colnames(d) 
  for(site in colnames(d)){
    d1=d[,site]
#long-term mean 
  grandmean=mean(d1,na.rm=T) 
#annual component
  annualmean=aggregate(d1,1,mean,na.rm=T)
  annualmeanreps=as.vector(t(matrix(rep(annualmean,12), ncol=12)))
  interann=ts(annualmeanreps,s=c(startyr,1),f=12)/grandmean
  #remaining components
  if(event) {
    #monthly component
    d2=matrix(d1,nrow=12)
    monthdev=sweep(d2,2,annualmean,"/")
    monthmean=apply(monthdev,1,mean,na.rm=T) 
    season=ts(rep(monthmean,endyr-startyr+1), s=c(startyr, 1),f=12) 
    #events component
    resids=sweep(monthdev, 1, monthmean, "/")
    events=ts(as.vector(resids),s=c(startyr,1),f=12)
  } 
  else { 
    #monthly component
    season=d1/(grandmean*interann) 
  } 
  #prepare output
  if(event) dcomp=ts.union(d1,grandmean,interann,season, events) else dcomp=ts.union(d1,grandmean,interann, season)
  colnames(dcomp)[1]="original"
  results[[site]]=dcomp 
  } 
  if(class(x)[1]!="mts") results[[1]] else results
}
```

```{r}
decomp.mult(c5$chl_comb)
```



```{r}
c_join %>% 
  filter(pres == 10 | pres == 5) %>% 
  ggplot(aes(x = date, y = chl_comb, color = as.factor(pres))) +
  geom_line()

test <- c_join %>% 
  filter(pres == 10)

test %>% 
  ggplot(aes(x = chl_comb, y = temp)) +
  geom_point()
```


```{r}
c_3d <- c_join %>% 
  filter(pres < 31) %>%
  group_by(date) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n == 5)

c_sf_3d <- c_sf_dm %>% 
  filter(pres < 31) %>%
  group_by(date) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n == 15) %>% 
  mutate(month = month(date))

c_d_mm <- c_3d %>% 
  group_by(month, pres) %>% 
  summarise(chl_mm = mean(chl_comb),
            sd_mm = sd(chl_comb),
            phaeo_mm = mean(phaeo_comb),
            phaeo_sd_mm = sd(phaeo_comb),
            ph_chl_mm = mean(ph_chl),
            ph_chl_sd_mm = sd(ph_chl)) %>% 
  ungroup()


c_sf_mm <- c_sf_3d %>% 
  group_by(month, pres, filter_type2) %>% 
  summarise(perc_mm = mean(perc),
            perc_sd_mm = sd(perc),
            chl_mm = mean(avg_chla),
            chl_sd_mm = sd(avg_chla)) %>% 
  ungroup()

pom_mm <- pom_dm %>% 
  mutate(month = month(date)) %>% 
  group_by(month, pres) %>% 
  summarise(pom_mm = mean(pom_dm),
            pom_sd = sd(pom_dm)) %>% 
  ungroup()

fec_mm <- fec %>% 
  group_by(month) %>% 
  summarise(fec_mm = mean(fecal),
            fec_sd = sd(fecal)) %>% 
  ungroup()

chem_mm <- chem %>% 
  mutate(month = month(date)) %>% 
  group_by(month, group) %>% 
  summarise(chem_mm = mean(contribution),
            chem_sd = sd(contribution)) %>% 
  ungroup()

zeu_mm <- zeu %>% 
  mutate(month = month(date)) %>% 
    mutate(year = year(date)) %>% 
  filter(year > 2016) %>% 
  group_by(month) %>% 
  summarise(zeu_mm = mean(zeu),
            zeu_sd = sd(zeu),
            n = n(),
            min = min(zeu),
            max = max(zeu)) %>% 
  ungroup()

ts_mm <- ctd %>% 
  filter(pres == 1 | pres == 5 | pres == 10 | pres == 30) %>% 
  select(date, pres, temp, sal, delta_rho) %>% 
  pivot_longer(c(temp:delta_rho), values_to = "val", names_to = "par") %>% 
  group_by(date, pres, par) %>% 
  summarise(val = mean(val)) %>% 
  ungroup() %>% 
  mutate(month = month(date)) %>% 
  group_by(month, pres, par) %>% 
  summarise(val_mm = mean(val),
            val_sd = sd(val)) %>% 
  ungroup()

# dr <- ctd2 %>% 
#   select(date, dr_dm) %>% 
#   distinct()

n2_mm <- ctd %>% 
  filter(pres < 31) %>% 
  select(date, N2) %>% 
  group_by(date) %>% 
  summarise(val = mean(N2, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(month = month(date)) %>% 
  group_by(month) %>% 
  summarise(val_mm = mean(val, na.rm = T),
            val_sd = sd(val, na.rm = T)) %>% 
  ungroup()

r21_mm <- ctd2 %>% 
  select(date, r24_dep_dm) %>%
  distinct() %>% 
  mutate(month = month(date)) %>% 
  group_by(month) %>% 
  summarise(val_mm = mean(r24_dep_dm, na.rm = T),
            val_sd = sd(r24_dep_dm, na.rm = T)) %>% 
  ungroup()

n_mm <- ctd2 %>% 
  select(date, pres, no2_dm, sio2_dm, po4_dm) %>%
  mutate(s_star = sio2_dm - no2_dm) %>% 
  filter(pres < 31) %>% 
  drop_na() %>% 
  group_by(date) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n >= 4) %>% 
  filter(pres == 1 | pres == 5 | pres == 10 | pres == 30) %>% 
  pivot_longer(c(no2_dm, sio2_dm, po4_dm, s_star), values_to = "val", names_to = "par") %>%
  mutate(month = month(date)) %>% 
  group_by(month, pres, par) %>% 
  summarise(val_mm = mean(val, na.rm = T),
            val_sd = sd(val, na.rm = T)) %>% 
  ungroup()
```

```{r}
# test <- ctd2 %>%
#   mutate(sigma = rho-1000) %>% 
#   select(date, depth = pres, temp, sal, sigma)
# 
# rho <- ctd2 %>% 
#   select(date, pres, rho)
# 
# ctd_clean <- test %>%
#   group_by(date) %>%
#   mutate(temp = despike(temp, mult = 3),
#     sal = despike(sal, mult = 3),
#     sigma = despike(sigma, mult = 3))
# 
# 
# 
# ggplot(ctd_clean) + geom_path(aes(x=sal, y=-depth, group=date), alpha=0.6)
# 
# f2 <- f %>% 
#   left_join(rho) %>% 
#   mutate(sigma = rho-1000) %>% 
#   select(date, depth = pres, sigma, chla = f_npq)
# 
# fl_clean <- f2 %>% 
#   mutate(chla=despike(chla, k=2, mult=4))
# 
# stats2 <- fl_clean %>%
#   group_by(date) %>%
#   summarise(DCM = maxd(chla, depth, n.smooth = 2, k = 3),
#             chla_dcm_stock = integrate(chla, depth, from = DCM-5, to=DCM+5))
# 
# # https://github.com/jiho/castr
# stats <- ctd_clean %>%  
#   group_by(date) %>% 
#   summarise(thermocline = clined(temp, depth, n.smooth = 2, k = 2),
#             pycnocline = clined(sigma, depth),
#             strat_index = stratif(sigma, depth, min.depths=0:5, max.depth = 60:65),
#             MLD = mld(sigma, depth, ref.depths = 10, default.depth=80))

```
```{r}
# stats2 %>% 
#   mutate(month = month(date)) %>% 
#   group_by(month) %>% 
#   summarise(dcm = mean(DCM),
#             css = mean(chla_dcm_stock)) %>%
#   ungroup() %>% 
#   ggplot(aes(month, y = css)) +
#   geom_line()
# 
# stats %>% 
#   ggplot(aes(x = date, y = thermocline)) +
#   geom_line()
# 
# stats %>% 
#   mutate(month = month(date)) %>%
#   ggplot(aes(x = as.factor(month), y = MLD)) +
#   geom_boxplot()
```



```{r}
group_mm <- micro %>% 
  group_by(date, group) %>% 
  summarise(count = sum(count)) %>% 
  ungroup() %>% 
  mutate(month = month(date)) %>%
  group_by(month, group) %>% 
  summarise(mean_count = mean(count),
            sd_count = sd(count)) %>% 
  ungroup() %>% 
  filter(group == "Bacillariophyta") 

ds_mm <- micro %>% 
  mutate(month = month(date)) %>%
  filter(scientificName == "Chaetoceros radicans" | 
           scientificName == "Rhizosolenia setigera" |
           scientificName == "Skeletonema marinoi" |
           scientificName == "Pyramimonas grossii") %>% 
  group_by(month, scientificName) %>% 
  summarise(mean_count = mean(count),
            sd_count = sd(count)) %>% 
  ungroup() %>% 
  rename(group = scientificName)

d_abund <- rbind(group_mm, ds_mm)

gz <- micro %>% 
  group_by(date, group) %>% 
  summarise(count = sum(count)) %>% 
  ungroup() %>% 
  mutate(month = month(date)) %>%
  group_by(month, group) %>% 
  summarise(mean_count = mean(count),
            sd_count = sd(count)) %>% 
  ungroup() %>% 
  filter(group == "Ciliophora")
```

```{r}
f1 <- c_d_mm %>%
  filter(pres < 11 | pres == 30) %>%
  ggplot(aes(x = month, y = chl_mm, color = as.factor(pres))) +
  geom_ribbon(aes( y = chl_mm, ymin = chl_mm + sd_mm, ymax = chl_mm - sd_mm,
                  fill = as.factor(pres)), alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(fill = "Depth (m)",
       color = "Depth (m)",
       y = bquote(Chl~"(mg" ~ m^-3*")"),
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  # facet_wrap(~as.factor(pres), ncol = 1) +
  theme_bw() +
  theme(legend.position = c(0.8, 0.8),
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))
  
```

```{r}
f2 <- c_sf_mm %>%
  filter(pres < 11 | pres == 30) %>%
  filter(filter_type2 == "20um") %>% 
  ggplot(aes(x = month, y = perc_mm, color = as.factor(pres))) +
  geom_ribbon(aes(y = perc_mm, ymin = perc_mm + perc_sd_mm,
                  ymax = perc_mm - perc_sd_mm,
                  fill = as.factor(pres)),
              alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(y = bquote(Chl[MICRO]~"(%)"),
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))
```

```{r}
f3 <- pom_mm %>%
  ggplot(aes(x = month, y = pom_mm, color = as.factor(pres))) +
  geom_ribbon(aes( y = pom_mm, ymin = pom_mm + pom_sd, ymax = pom_mm - pom_sd,
                  fill = as.factor(pres)), alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(fill = "Depth (m)",
       color = "Depth (m)",
       y = bquote(POC~"(mg" ~ m^-3*")"),
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  # facet_wrap(~as.factor(pres), ncol = 1) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))
  

```

```{r}
f4 <- c_d_mm %>%
  filter(pres < 11 | pres == 30) %>%
  ggplot(aes(x = month, y = ph_chl_mm, color = as.factor(pres))) +
  geom_ribbon(aes( y = ph_chl_mm, ymin = ph_chl_mm + ph_chl_sd_mm,
                   ymax = ph_chl_mm - ph_chl_sd_mm,
                  fill = as.factor(pres)), alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(y = "Phaeo:Chl (%)",
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))
```









```{r}
fig <- f1 + f2 + f3 + f4

ggsave(here("figures", "clim_phyto.png"), fig,
        width = 24, height = 14, dpi = 300)
```
```{r}
f5 <- gz %>%
  ggplot(aes(x = month, y = mean_count)) +
  geom_ribbon(aes(y = mean_count,
                  ymin = mean_count + sd_count,
                  ymax = mean_count - sd_count,
                  fill = as.factor(group)),
              alpha = 0.2, color = "transparent", fill = "#56B4E9") +
  geom_line(size = 3, color = "#56B4E9") +
  scale_color_tron() +
  labs(y = bquote("Ciliates"~"(cells"~L^-1*")"),
       x = NULL,
       color = NULL,
       fill = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))
```
```{r}
f6 <- fec_mm %>%
  ggplot(aes(x = month, y = fec_mm)) +
  geom_ribbon(aes(y = fec_mm,
                  ymin = fec_mm + fec_sd,
                  ymax = fec_mm - fec_sd),
              alpha = 0.2, color = "transparent", fill = "#56B4E9") +
  geom_line(size = 3, color = "#56B4E9") +
  labs(y = bquote("Fecal"~"(pellets"~L^-1*")"),
       x = NULL,
       color = NULL,
       fill = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))
```

```{r}
fig_graz <- f1 + f2 + f3 + f4 + f5 + f6 + plot_layout(ncol = 2)

ggsave(here("figures", "clim_phyto_graz.png"), fig_graz,
        width = 24, height = 18, dpi = 300)
```













```{r}
# f4 <- 

d_abund %>%
  # filter(group == "Bacillariophyta" | group == "Skeletonema marinoi") %>% 
  ggplot(aes(x = month, y = log1p(mean_count), color = as.factor(group))) +
  # geom_ribbon(aes(y = log1p(mean_count), 
  #                 ymin = log1p(mean_count) + log1p(sd_count),
  #                 ymax = log1p(mean_count) - log1p(sd_count),
  #                 fill = as.factor(group)),
  #             alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_tron() +
  labs(y = bquote("Abundance"~"(Log cells"~L^1*")"),
       x = NULL,
       color = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  scale_color_discrete(labels = c("Diatoms",
                                 "C.rad",
                                 "P.gross",
                                 "R.set",
                                 "S.mar")) +
  theme_bw() +
  theme(legend.position = c(0.098, 0.83),
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black")) 

ggsave(here("figures", "clim_ind_species.png"), 
        width = 12, height = 8, dpi = 300)
```

```{r}
d_abund %>%
  filter(group == "Bacillariophyta" | group == "Skeletonema marinoi") %>%
  ggplot(aes(x = month, y = mean_count/10^5, color = as.factor(group))) +
  geom_ribbon(aes(y = mean_count/10^5,
                  ymin = mean_count/10^5 + sd_count/10^5,
                  ymax = mean_count/10^5 - sd_count/10^5,
                  fill = as.factor(group)),
              alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_tron() +
  labs(y = bquote("Abundance"~"(cells"~L^1*")"),
       x = NULL,
       color = NULL,
       fill = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  # scale_color_discrete(labels = c("Diatoms",
  #                                "C.rad",
  #                                "P.gross",
  #                                "R.set",
  #                                "S.mar")) +
  theme_bw() +
  theme(legend.position = c(0.75, 0.9),
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black")) 

ggsave(here("figures", "clim_diatoms_sm.png"), 
        width = 12, height = 8, dpi = 300)
```


```{r}
p1 <- ts_mm %>%
  filter(par == "temp") %>% 
  ggplot(aes(x = month, y = val_mm, color = as.factor(pres))) +
  geom_ribbon(aes( y = val_mm, ymin = val_mm + val_sd,
                   ymax = val_mm - val_sd,
                  fill = as.factor(pres)), alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(fill = "Depth (m)",
       color = "Depth (m)",
       y = "Temp (°C)",
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = c(0.13, 0.8),
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))
```

```{r}
p2 <- ts_mm %>%
  filter(par == "sal") %>% 
  ggplot(aes(x = month, y = val_mm, color = as.factor(pres))) +
  geom_ribbon(aes( y = val_mm, ymin = val_mm + val_sd,
                   ymax = val_mm - val_sd,
                  fill = as.factor(pres)), alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(y = "Salinity",
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))

```
```{r}
p3 <- n_mm %>%
  filter(par == "no2_dm") %>% 
  ggplot(aes(x = month, y = val_mm, color = as.factor(pres))) +
  geom_ribbon(aes( y = val_mm, ymin = val_mm + val_sd,
                   ymax = val_mm - val_sd,
                  fill = as.factor(pres)), alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(y = bquote("DIN\u0020\u0028\u00B5mol\u0020L"^-1*")"),
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))

```
```{r}
p4 <- n_mm %>%
  filter(par == "sio2_dm") %>% 
  ggplot(aes(x = month, y = val_mm, color = as.factor(pres))) +
  geom_ribbon(aes( y = val_mm, ymin = val_mm + val_sd,
                   ymax = val_mm - val_sd,
                  fill = as.factor(pres)), alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(y = bquote("DSi\u0020\u0028\u00B5mol\u0020L"^-1*")"),
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))

```
```{r}
n_mm %>%
  filter(par == "po4_dm") %>% 
  ggplot(aes(x = month, y = val_mm, color = as.factor(pres))) +
  geom_ribbon(aes( y = val_mm, ymin = val_mm + val_sd,
                   ymax = val_mm - val_sd,
                  fill = as.factor(pres)), alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(y = bquote("DIP\u0020\u0028\u00B5mol\u0020L"^-1*")"),
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))

```


```{r}
ts_mm %>%
  filter(par == "delta_rho" & pres == 5) %>% 
  ggplot(aes(x = month, y = val_mm)) +
  geom_ribbon(aes( y = val_mm, ymin = val_mm + val_sd,
                   ymax = val_mm - val_sd), alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(y = "DR",
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))
```

```{r}
p5 <- n2_mm %>%
  ggplot(aes(x = month, y = val_mm*10^3)) +
  geom_ribbon(aes( y = val_mm*10^3, ymin = val_mm*10^3 + val_sd*10^3,
                   ymax = val_mm*10^3 - val_sd*10^3), alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(y = bquote(N^2~"("*10^3~"AVG 1-30m)"),
       x = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black"))
```
```{r}
p6 <- zeu_mm %>%
  ggplot(aes(x = month, y = zeu_mm)) +
  geom_ribbon(aes(y = zeu_mm,
                  ymin = zeu_mm + zeu_sd,
                  ymax = zeu_mm - zeu_sd),
              alpha = 0.2, color = "transparent") +
  geom_line(size = 3) +
  scale_color_tron() +
  labs(y = bquote("Z"[eu]~"("*depth~m^-1*")"),
       x = NULL,
       color = NULL,
       fill = NULL) +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                     limits = c(1,12),
                     labels = c("J", "F", "M", "A", "M", "J",
                                "J", "A", "S", "O", "N", "D")) +
  theme_bw() +
  theme(legend.position = c(0.9, 0.83),
        text = element_text(size = 35), #35
        axis.text = element_text(color = "black")) 
```

```{r}
fig_drive <- p1 + p2 + p3 + p4 + p5 + p6 + plot_layout(ncol = 2)

ggsave(here("figures", "clim_driver.png"), fig_drive,
        width = 24, height = 18, dpi = 300)
```


```{r}
#add nutrients, stratification, temperature, salinity.

#Can I standardize into a single plot?
#1) Chlorophyll by depth
#2) Micro-contribution by depth
#3) Diatom abundance and Chemtax diatom by depth - maybe contribution? 5m
#Or Skeletonema and diatom - need to assess variability
#4) Nutrients by depth
#5) Temp/Sal by depth?
#6) Stratification?
```

