---
title: "R Notebook"
output: html_notebook
---



```{r}
#Upload packages
library(tidyverse)
library(here)
library(readxl)
library(patchwork)
library(lubridate)
library(MBA)
library(mgcv)
library(FNN)
library(zoo)
library(reshape2)
library(rioja)
library(egg)
library(mapdata)

# library(raster)
# library(maps) 
# library(maptools)
# library(rgeos)
# library(rgdal)

# library(oce)
# library(ocedata)

library(gsw)
```

```{r}
# https://semba-blog.netlify.app/12/01/2019/plotting-the-spatial-distribution-of-chlorophyll-from-modis/
```

```{r}
ctd <- read.csv(here("files", "ctd_2024-07_Calvert.csv"))
```





```{r}
#Wrangling the CTD data - renaming some of the key columns/variables that I will be working with

ctd <- ctd %>% 
  rename(cast_pk = Cast.PK,
         date_time = Measurement.time,
         station = Station,
         lat = Station.Latitude,
         long = Station.Longitude,
         pres = Pressure..dbar.,
         sal = Salinity..PSU.,
         temp = Temperature..deg.C.,
         f = Fluorometry.Chlorophyll..ug.L.)

#Adding a date column
ctd <- ctd %>% 
  mutate(date = lubridate::date(date_time)) %>% 
  relocate(date, .after = date_time) %>% 
  group_by(station) %>% 
  mutate(dep_max = max(pres)) %>% 
  ungroup() %>% 
  filter(dep_max > 100) %>% 
  filter(!station == "QSD01") %>%  
  filter(!station == "BUR1") %>% 
  filter(!station == "PRUTH") 
# %>% 
#   filter(!station == "FC1")

#Looking at coordinates for the CTD dataset - are there any missing? Mssing values need to be filled for later calculations
ctd_coord <- ctd %>% 
  distinct(station, lat, long) %>% 
  mutate(lat = as.double(lat),
         long = as.double(long))


#Performing GSW calculations to derive density 

#Calculating absolute salinity
SA <- gsw_SA_from_SP(ctd$sal, ctd$pres, ctd$long, ctd$lat)

#Converting absolute salinity output to a dataframe
SA <- as.data.frame(SA)

#Calculating conservative temperature
CT <- gsw_CT_from_t(SA$SA, ctd$temp, ctd$pres)

#Converting conservative temperature output to a dataframe
CT <- as.data.frame(CT)

#Calculating Density
rho = gsw_rho(SA$SA, CT$CT, ctd$pres)

#Converting Density to a dataframe
rho <- as.data.frame(rho)

#Calculating Brunt-Vaisala frequency
bv <- gsw_Nsquared(SA$SA, CT$CT, ctd$pres)

#Converting Brunt-Vaisala frequency to a dataframe
bv <- bind_rows(bv)

#Adding a row at the bottom of the Brunt-Vaisala dataframe to make the vector length equal to the other calculations -  not sure why this does this, but I think the calculation takes two consequative depths into consideration and throws an NA at the last cell because there - does this mess up calculations between profiles then? Maybe - not using this for now.
bv <- bv %>% 
  add_row(N2 = NA, p_mid = NA)

#Binding calculations to ctd dataframe
ctd <- cbind(ctd, SA, CT, rho, bv)
```

```{r}
flu_max <- ctd %>% 
  group_by(cast_pk) %>% 
  slice_max(f) %>% 
  ungroup() %>% 
  select(station, lat, long, f, rho)

rho24 <- ctd %>% 
  group_by(cast_pk) %>% 
  mutate(diff = abs(rho - 1024)) %>% 
  slice_min(diff, with_ties = F) %>% 
  ungroup() %>%
  select(cast_pk, station, rho1021_dep = pres)

ctd <- ctd %>% 
  left_join(rho24)

flu_sum <- ctd %>% 
  group_by(station) %>% 
  summarise(sum = sum(f)) %>% 
  ungroup() %>% 
  left_join(flu_max) %>% 
  mutate(f/sum)
```



```{r}
ctd %>% 
  filter(pres < 31) %>% 
  ggplot() +
  geom_line(aes(x = f*1.50, y = pres, color = station), orientation = "y", size = 4) +
  # geom_line(aes(x = 40, y = rho1021_dep), size = 2) +
  # geom_hline(aes(yintercept = rho1021_dep)) +
  scale_y_reverse() +
  ggsci::scale_color_npg() +
  facet_wrap(~factor(station, levels = c("FC1",
                "FZH04",
                "FZH08",
                "KC10",
                "FZH01",
                "FZH13",
                "UBC7",
                "RVRS01",
                "QCS07"))) +
  labs(x = bquote(CTD[FLU]~"(mg" ~ m^-3*")"),
       y = "Depth") +
  theme_bw() +
  theme(legend.position = "none") +
  theme(strip.background = element_blank(),
        text = element_text(size = 45),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        # legend.position = c(0.07, 0.95),
        panel.spacing.x = unit(2, "lines"))

ggsave(here("figures", "map_test_single_ctd_fc1.png"),
        width = 16, height = 16, dpi = 300)
```

```{r}
ctd %>% 
  filter(pres < 31) %>% 
  ggplot(aes(x = f, y = rho)) +
  geom_point()
```
```{r}
ctd_num <- ctd %>% 
  distinct(CTD.serial.number)
```

```{r}
ctd %>% 
  filter(pres < 31) %>% 
  ggplot() +
  geom_line(aes(x = sal, y = pres, color = station), orientation = "y", size = 4) +
  # geom_line(aes(x = 40, y = rho1021_dep), size = 2) +
  # geom_hline(aes(yintercept = rho1021_dep)) +
  scale_y_reverse() +
  ggsci::scale_color_npg() +
  facet_wrap(~factor(station, levels = c("FC1",
                "FZH04",
                "FZH08",
                "KC10",
                "FZH01",
                "FZH13",
                "UBC7",
                "RVRS01",
                "QCS07"))) +
  labs(x = "BV",
       y = "Depth") +
  theme_bw() +
  theme(legend.position = "none") +
  theme(strip.background = element_blank(),
        text = element_text(size = 45),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        # legend.position = c(0.07, 0.95),
        panel.spacing.x = unit(2, "lines"))

ggsave(here("figures", "map_test_single_ctd_fc1_sal.png"),
        width = 16, height = 16, dpi = 300)
```











