---
title: "R Notebook"
output: html_notebook
---

Some new interpolation tutorials to consider:
https://search.r-project.org/CRAN/refmans/rioja/html/interp.dataset.html
https://github.com/hdugan/NTLlakeloads

```{r}
#Upload packages
library(tidyverse)
library(here)
library(readxl)
library(patchwork)
library(lubridate)
library(MBA)
library(mgcv)
library(FNN)
library(zoo)
library(reshape2)
library(rioja)
library(egg)

```

```{r}
#Corrected CTD data
f <- read_csv(here("outputs", "kc10_npq_test.csv"))

env <- read_csv(here("outputs", "enviro_5m_2025-04-25_kc10.csv"))

env_anom <- read_csv(here("outputs", "ctd_anom_week_2025-04-25_kc10.csv"))

wind <- read_csv(here("files", "wind_all.csv"))

wind_anom <- read.csv(here("outputs", "wind_anom_day_2025-04-25.csv"))

#CHEMTAX
chem <- read_csv(here("files", "chemtax_kc10_2024.csv"))

#Downloading chlorophyll data
chl <- read_csv(here("files_big", "2025-02-13_HakaiData_chlorophyll.csv"))

```

```{r}
#Working with chemtax data to make it easy to plot

#Making the date column a date format
chem <- chem %>% 
  mutate(date2 = lubridate::mdy(Date)) 

#Selecting appropriate columns and renaming to easy to work with names
chem <- chem %>%
  select(date = date2, cyan = Cyanobacteria, hapt = Hapto, 
         GA = `Prasinophytes-3`, cryp = Cryptophytes,
         dino = `Dinoflagellates-1`, raph = Raphido,
         dict = Dictyo, diat = `Diatoms-1`)

#Pivoting to long/tidy for plotting in ggplot
chem <- chem %>% 
  pivot_longer(c(cyan:diat), names_to = "group", values_to = "contribution")

#Calculating TChla for each sample
chem_tchla <- chem %>% 
  group_by(date, group) %>% 
  summarise(contribution = mean(contribution)) %>% 
  ungroup() %>% 
  group_by(date) %>% 
  mutate(tchla = sum(contribution)) %>% 
  ungroup()


#checking to see if there are any duplicates - there were replicates taken for DFO comparisons. None found because I already averaged these for the manuscript.
chem_dup <- chem_tchla %>%
  distinct(date, tchla) %>% 
  group_by(date) %>% 
  mutate(dup = n()) %>% 
  ungroup() %>% 
  filter(dup > 1)

#Good to move forward
```
```{r}
#Pulling out bulk data with appropriate flags and running a daily mean in case there are duplicates

chl_qc <- chl %>% 
  select(date, line_out_depth, filter_type, chla, chla_flag) %>% 
  filter(filter_type == "Bulk GF/F") %>% 
  filter(chla_flag == "AV" | chla_flag == "SVC" | chla_flag == "ADL" | is.na(chla_flag)) 

chl_dm <- chl_qc %>% 
  group_by(date, line_out_depth) %>% 
  summarise(chl_dm = mean(chla)) %>% 
  ungroup() %>% 
  mutate(pres = round(line_out_depth)) %>%
  drop_na() %>% 
  group_by(date) %>% 
  mutate(n_dep = n()) %>% 
  ungroup() %>% 
  filter(n_dep >= 5) %>% 
  mutate(year = year(date)) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))
```
```{r}
chl_sf <- chl %>% 
  select(date, line_out_depth, filter_type, chla, chla_flag) %>% 
  filter(!filter_type == "Bulk GF/F") %>% 
  filter(chla_flag == "AV" | chla_flag == "SVC" | chla_flag == "ADL" | is.na(chla_flag))

chl_sf_dm <- chl_sf %>% 
  filter(!is.na(chla)) %>%
  filter(chla > 0) %>% 
  group_by(date, line_out_depth, filter_type) %>% 
  summarise(avg_chla = mean(chla)) %>%
  ungroup() %>% 
  group_by(date, line_out_depth) %>% 
  mutate(n_filt = n()) %>% 
  ungroup() %>% 
  group_by(date, line_out_depth, filter_type) %>% 
  mutate(n_type = n()) %>% 
  ungroup() %>% 
  filter(n_filt == 3 & n_type == 1) %>% 
  group_by(date, line_out_depth) %>% 
  mutate(sum = sum(avg_chla)) %>% 
  ungroup() %>% 
  mutate(perc = avg_chla/sum) %>% 
  select(date, pres = line_out_depth, filter_type, avg_chla, sum, perc) %>% 
  mutate(filter_type2 = case_when(filter_type == "2um" ~ "3um",
                                  TRUE ~ as.character(filter_type)))

chl_sum <- chl_sf_dm %>% 
  distinct(sum, .keep_all = T) %>% 
  select(date, pres, sum) %>% 
  mutate(pres = case_when(pres == 0 ~ 1,
                          TRUE ~ as.numeric(pres)))
```

```{r}
chl_join <- chl_dm %>% 
  full_join(chl_sum) %>% 
  mutate(chl_comb = case_when(is.na(chl_dm) ~ sum,
                              !is.na(chl_dm) ~ chl_dm)) %>% 
  select(date, pres, chl_comb)
```



```{r}
#Creating a daily mean corrected chlorophyll fluorescence sheet - the fact that it is not already daily mean is concerning though, as I should have done this in the correction phase. It might mean that my corrections have some issues and I need to review them.
f_dm <- f %>% 
  group_by(date, pres) %>% 
  summarise(f_dm = mean(f_npq)) %>% 
  ungroup() %>% 
  mutate(year = year(date),
         month = month(date))

f_dm <- f_dm %>% 
  left_join(chl_dm)
```

```{r}
#Here, I can go through each year and plot profiles by month so that I can look for quality issues. I want to add chlorophyll bottle concentrations as well.
f_dm %>% 
  filter(year == 2024) %>% 
  ggplot(aes(x = f_dm, y = pres, color = as.factor(date))) +
  geom_line(orientation = "y") +
  geom_point(aes(x = chl_dm, y = pres),
             size = 6, 
             pch = 8,
             color = "black", 
             stroke = 2) +
  scale_y_reverse() +
  facet_wrap(~date, scales = "free_x") +
  theme_article() +
  theme(legend.position = "none")

#2023-05-14 appears to of had issues with my corrections - they likely were not extended deep enough.
```
```{r}
f_dm %>% 
  ggplot(aes(x = chl_dm, y = f_dm)) +
  geom_point()
```



```{r}
#I need to:

# extend the record back to 2013-2014 and maybe gap fill with FZH01 - I think I've done this somewhere already
# Try to improve corrections prior to 2017
#Define SCM detection and quantification metrics
#Correlate metrics over the TS with environmental variables.

```









