---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(here)
library(readxl)
library(patchwork)
library(lubridate)
library(MBA)
library(mgcv)
library(FNN)
library(zoo)
library(reshape2)
library(rioja)
library(egg)
library(ggcorrplot)
library(ggsci)
library(vegan)
library(ggrepel)
library(ggforce)
library(factoextra)
library(cluster)
library(ggdendro)
library(cmocean)
```

```{r}
#Slope and NPQ Corrected CTD data
f <- read_csv(here("outputs", "corrected_flu_2025-04-10.csv"))
env <- read_csv(here("outputs", "enviro_ctd_nut_2025-04-15.csv"))
weath <- read_csv(here("outputs", "enviro_weather_2025-04-14.csv"))
mei <- read_csv(here("files_big", "mei_2025-04-24.csv")) 
npgo <- read_csv(here("files_big", "npgo_2025-04-24.csv"))
up <- read_csv(here("files_big", "up_2025-04-24.csv"))
```
```{r}
mei <- mei %>% 
  rename(mei = `Multivariate ENSO Index Version 2 (MEI.v2)  missing value -999 https://psl.noaa.gov/data/timeseries/month/`) %>% 
  mutate(date = mdy(Date)) %>% 
  select(-Date) %>% 
  filter(date > "2016-01-01" & !mei == -9999.00)

npgo <- npgo %>% 
  rename(npgo = `North Pacific Gyre Oscillation: NPGO Monthly  missing value -99 https://psl.noaa.gov/data/timeseries/month/`) %>% 
  mutate(date = mdy(Date)) %>% 
  select(-Date) %>% 
  filter(date > "2016-01-01" & !npgo == -9999.00)

up <- up %>% 
  select(time, ui = upwelling_index) %>% 
  mutate(date = date(time),
         ui = as.numeric(ui)) %>% 
  filter(!is.nan(ui)) %>% 
  group_by(date) %>% 
  summarise(ui = mean(ui)) %>% 
  ungroup() %>% 
  mutate(year = year(date)) %>% 
  group_by(year) %>% 
  mutate(cu_sum = cumsum(ui)) %>% 
  ungroup()
```

```{r}
f1 <- mei %>%
  filter(date > "2016-01-01" & date < "2025-01-01") %>%
  ggplot(aes(x = date, y = mei, fill = mei)) +
  geom_bar(stat = "identity") +
  # scale_fill_cmocean(name = "balance") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  ylim(-2.5, 2.5) +
  # scale_fill_distiller(palette = 'RdBu') +
  theme_bw() +
  labs(y = "MEI",
       fill = "MEI") +
  theme(text = element_text(size = 30),
        legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```

```{r}
f2 <- npgo %>% 
  ggplot(aes(x = date, y = npgo, fill = npgo)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  labs(y = "NPGO") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```
```{r}
coeff = 10

f3 <- up %>%
  filter(date > "2016-01-01" & date < "2025-01-01") %>%
  mutate(color = ifelse(ui < 0, "blue","red")) %>%
  ggplot(aes(x = date, ))+
  geom_col(aes(y = ui, fill = color)) +
  geom_line(aes(y = cu_sum/coeff, color = as.factor(year)),
            size = 2) +
  scale_y_continuous(name = "UI",
                     sec.axis = sec_axis(~.*coeff, name = "Cumulative UI")) +
  scale_fill_identity(guide = FALSE) +
  scale_color_viridis_d(option = "turbo") +
  labs(color = NULL) +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```

```{r}
fig_clim <- f1 / f2 / f3


ggsave(here("figures", "panel_clim.jpg"), fig_clim,
       width = 16, height = 14, dpi = 300)
```
```{r}
q <- weath %>% 
  select(date, Q_GM, Q_SM, Q_RA) %>% 
  pivot_longer(c(Q_GM:Q_RA), names_to = "Watershed_group", values_to = "Q") %>% 
  drop_na() %>% 
  group_by(date) %>% 
  mutate(n = n()) %>% 
  ungroup()
```

```{r}
# Order locations from fjord to shelf
riv_loc <- c("Q_GM",
             "Q_SM",
             "Q_RA",
             "Q_tot")

q <- arrange(mutate(q, 
                      Watershed_group = factor(Watershed_group,
                                               levels = riv_loc)))
```


```{r}
f4 <- q %>% 
  filter(date > "2016-01-01" & date < "2025-01-01") %>%
  ggplot(aes(x = date, y = Q/10^3, fill = Watershed_group)) +
  geom_area() +
  scale_fill_manual(values = c("#6699CE", "#C96999", "#00AB82")) +
  labs(y = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       fill = NULL) +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = c(0.8, 0.8),
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```
```{r}
fig_clim <- f1 / f2 / f3 /f4


ggsave(here("figures", "panel_clim_fW.jpg"), fig_clim,
       width = 16, height = 16, dpi = 300)
```




```{r}
#Determining profile maximum concentration
f_max <- f %>% 
  group_by(date, station) %>% 
  slice_max(f_npq, with_ties = F) %>% 
  ungroup() %>% 
  select(id, date, station, pres_max = pres, f_max = f_npq)

#Joining the profile maximum to the ctd data
fl2 <- f %>% 
  select(id, date, station, pres, f_npq) %>% 
  left_join(f_max) 

#Determining the full width half maximum of the fluorescence peaks.
fwhm <- fl2 %>% 
  select(id, date, station, pres, f_npq, f_max, pres_max) %>% 
  mutate(half_max = f_max/2) %>% #half max concentration
  mutate(position = case_when(pres < pres_max ~ "above", #above or below max depth
                              pres > pres_max ~ "below")) %>% 
  group_by(date, station, position) %>% 
  slice(which.min(abs(f_npq - half_max))) %>% #find closest value above/below to HM
  ungroup() %>% 
  select(id, fwhm_pres = pres, position, pres_max) %>% 
  filter(!is.na(position)) %>% 
  group_by(id) %>% 
  mutate(n = n()) %>% #Should be 2 values (above/below), single means not met at surf
  ungroup()

#Joining fwhm to ctd profile data
fl3 <- fl2 %>% 
  left_join(fwhm) 

#Making FWHM depth above and below max separate columns and calculating diff
fl4 <- fl3 %>% 
  pivot_wider(names_from = "position", values_from = "fwhm_pres") %>%
  mutate(scm_width = below - above)

#Calculating 50m integrated chlorophyll
int50 <- fl4 %>% 
  filter(pres < 51) %>% 
  group_by(id, date, station) %>% 
  summarise(int_50 = sum(f_npq)) %>% 
  ungroup()

f20p <- fl4 %>% 
  filter(pres < 51) %>% 
  mutate(f20p = f_max*0.2) %>% 
  filter(f_npq > f20p) %>% 
  group_by(date, station) %>% 
  summarise(n_f20p = n()) %>% 
  ungroup()

#Joing integrated chlorophyll back in to cTD profile data
fl5 <- fl4 %>% 
  left_join(int50) %>% 
  left_join(f20p)

#Pulling out different profile metrics.
scm_metrics <- fl5 %>% 
  select(id, date, station,
         f_max,
          pres_max,
         fwhm_shallow = above,
         fwhm_deep = below,
         scm_width,
         scm_width,
         int_50,
         n_f20p) %>% 
  distinct() %>% 
  mutate(max_int = (f_max/int_50)*100) 
```


```{r}
#Should look at where and when FZH01 and KC10 correlate.
```

```{r}
#These are meant to be daily means and they are not - go back to enviro and fix.
env_2 <- env %>% 
  select(date, dr_dm, r24_dep_dm) %>% 
  distinct()

n <- env %>% 
  select(date, pres, no2_dm) %>% 
  drop_na() %>% 
  filter(pres == 1 | pres == 10) %>% 
  pivot_wider(names_from = pres, values_from = no2_dm) %>% 
  rename(din_1 = `1`, din_10 = `10`)

s <- env %>% 
  select(date, pres, dsi = sio2_dm) %>% 
  drop_na() %>% 
  filter(pres == 1 | pres == 10) %>% 
  pivot_wider(names_from = pres, values_from = dsi) %>% 
  rename(dsi_1 = `1`, dsi_10 = `10`)

#These are daily means.
ctd_surf <- env %>% 
  select(date, pres, 
         n2_surf = N2, 
         rho_surf = rho, 
         sal_surf = sal, 
         temp_surf = temp) %>% 
  filter(pres < 2) %>% 
  select(-pres)

ctd_fmax <- env %>%    
  select(date, 
         pres_max = pres, 
         n2_fmax = N2, 
         rho_fmax = rho, 
         sal_fmax = sal, 
         temp_fmax = temp) 

scm_kc10 <- scm_metrics %>% 
  filter(station == "KC10")


```


```{r}
scm_correlate <- scm_kc10 %>% 
  filter(station == "KC10") %>% 
  left_join(weath) %>% 
  left_join(env_2) %>% 
  left_join(ctd_surf) %>% 
  left_join(ctd_fmax) %>% 
  left_join(n) %>% 
  left_join(s) %>% 
  distinct() %>% 
  mutate(s_n = dsi_1/din_1)
```
```{r}
scm_correlate %>% 
  mutate(month = month(date)) %>% 
  filter(station == "KC10") %>%
  ggplot(aes(x = as.factor(month), y = dsi_1/din_1, fill = station)) +
  geom_boxplot() +
  ggsci::scale_fill_npg() +
  ylim(0, 20)
```

```{r}
cor2 <- scm_correlate %>% 
  mutate(s_n = dsi_1/din_1) %>% 
  select(f_max, pres_max, int_50, max_int, n_f20p, w_b1_3 = wind_b1_3,
         wd_b1_3, qt_b1_10:temp_surf, din_1, din_10, s_n) %>% 
  drop_na()

corr <- round(cor(cor2, method = "spearman"), 1)
p.mat <- cor_pmat(corr)
```

```{r}
ggcorrplot(corr, p.mat = p.mat, hc.order = TRUE,
    type = "lower", insig = "blank", lab = T, lab_size = 10) +
  theme_bw() +
  theme(text = element_text(size = 30),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

ggsave(here("figures", "corello_s_n.png"), 
        width = 20, height = 20, dpi = 300)
```

```{r}
scm_correlate %>%
  mutate(month = month(date),
         year = year(date)) %>% 
  ggplot(aes(x = din_1, y = dsi_1, color = as.factor(year))) +
  geom_point() +
  scale_color_viridis_d(option = "turbo") 

scm_correlate %>%
  mutate(month = month(date)) %>% 
  ggplot(aes(x = din_1, y = dsi_1, color = Q_Total)) +
  geom_point() +
  scale_color_viridis_c(option = "turbo")  
```




```{r}
scm_correlate <- scm_correlate %>% 
  mutate(month = month(date),
         year = year(date))
```

```{r}
#Physics Fig
f1 <- scm_correlate %>% 
  ggplot(aes(x = din_1, y = sal_surf, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote("DIN"[SURF]~"\u0020\u0028\u00B5mol\u0020L"^-1*")"),
       y = bquote("Salinity"[SURF])) +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f2 <- scm_correlate %>% 
  ggplot(aes(x = dr_dm, y = sal_surf, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote(Delta*rho~"("~kg~m^-3*")"),
       y = bquote("Salinity"[SURF]), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f3 <- scm_correlate %>% 
  ggplot(aes(x = din_1, y = temp_surf, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote("DIN"[SURF]~"\u0020\u0028\u00B5mol\u0020L"^-1*")"),
       y = bquote("Temp"[SURF]~"(°C)")) +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "none",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f4 <- scm_correlate %>% 
  ggplot(aes(x = dr_dm, y = temp_surf, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote(Delta*rho["30-2m"]~"("*kg~m^-3*")"),
       y = bquote("Salinity"[SURF]), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

fig_phys <- f1 + f2 + f3 + f4 + plot_layout(guides = "collect")

ggsave(here("figures", "panel_physical.jpg"), fig_phys,
       width = 16, height = 14, dpi = 300)
```

```{r}
scm_correlate %>% 
  ggplot(aes(x = sal_surf, y = temp_surf, color = as.factor(year))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(y = bquote("Temp"[SURF]~"(°C)"),
       x = bquote("Salinity"[SURF]), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

ggsave(here("figures", "surf_t_s.jpg"),
       width = 10, height = 6, dpi = 300)
```
```{r}

#Physics Fig
f1 <- scm_correlate %>% 
  ggplot(aes(x = qt_b1_10/10^3, y = sal_surf, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote("Dis." ~ "("*10^4~m^3*~s^-1*")"),
       y = bquote("Salinity"[SURF])) +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

# bquote("DIN"[SURF]~"\u0020\u0028\u00B5mol\u0020L"^-1*")"

f2 <- scm_correlate %>% 
  ggplot(aes(x = qt_b1_10/10^3, y = temp_surf, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote(Delta*rho~"("~kg~m^-3*")"),
       y = bquote("Temp"[SURF]~"(°C)"), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f3 <- scm_correlate %>% 
  ggplot(aes(x = qt_b1_10/10^3, y = dr_dm, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote("Dis." ~ "(Q"[TOTAL]*10^3~m^3*~s^-1*")"),
       y = bquote(Delta*rho["30-2m"]~"("*kg~m^-3*")")) +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "none",
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f4 <- scm_correlate %>% 
  ggplot(aes(x = qt_b1_10/10^3, y = din_1, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote("Dis." ~ "(Q"[TOTAL]*10^3~m^3*~s^-1*")"),
       y = bquote("DIN"[SURF]~"\u0020\u0028\u00B5mol\u0020L"^-1*")"), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

fig_dis <- f1 + f2 + f3 + f4 + plot_layout(guides = "collect")

ggsave(here("figures", "panel_dis.jpg"), fig_dis,
       width = 16, height = 12, dpi = 300)
```

```{r}
scm_correlate %>% 
  ggplot(aes(x = qt_b1_10/10^3, y = dr_dm, color = as.factor(year))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote("Dis." ~ "("*10^3~m^3*~s^-1*")"),
       y = bquote(Delta*rho["30-2m"]~"("*kg~m^-3*")"),
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        strip.background = element_blank(),
        strip.text.x = element_blank())

ggsave(here("figures", "surf_discharge.jpg"),
       width = 10, height = 6, dpi = 300)
```
```{r}

#Physics Fig
f1 <- scm_correlate %>% 
  ggplot(aes(x = int_50, y = qt_b1_10/10^3, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(y = bquote("Dis." ~ "(Q"[TOTAL]*10^3~m^3*~s^-1*")"),
       x = bquote("Flu"[0-50*"m"]~ "("*mg~m^-2*")")) +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

# bquote("DIN"[SURF]~"\u0020\u0028\u00B5mol\u0020L"^-1*")"

f2 <- scm_correlate %>% 
  ggplot(aes(x = int_50, y = dr_dm, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(y = bquote(Delta*rho["30-2m"]~"("*kg~m^-3*")"),
       x = bquote("Flu"[0-50*"m"]~ "("*mg~m^-2*")"), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f3 <- scm_correlate %>% 
  ggplot(aes(x = int_50, y = temp_surf, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(y = bquote("Temp"[SURF]~"(°C)"),
       x = bquote("Flu"[0-50*"m"]~ "("*mg~m^-2*")"), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f4 <- scm_correlate %>% 
  ggplot(aes(x = int_50, y = wind_b1_3, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(y = bquote("Wind"[LOOKOUT]~"("*m~s^-1*")"),
       x = bquote("Flu"[0-50*"m"]~"("*mg~m^-2*")"), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f5 <- scm_correlate %>% 
  ggplot(aes(x = int_50, y = din_1, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(y = bquote("DIN"[SURF]~"\u0020\u0028\u00B5mol\u0020L"^-1*")"),
       x = bquote("Flu"[0-50*"m"]~"("*mg~m^-2*")"), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f6 <- scm_correlate %>% 
  ggplot(aes(x = int_50, y = dsi_1, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(y = bquote("DSi"[SURF]~"\u0020\u0028\u00B5mol\u0020L"^-1*")"),
       x = bquote("Flu"[0-50*"m"]~"("*mg~m^-2*")"), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

fig_int <- f1 + f2 + f3 + f4 + f5 + f6 + plot_layout(guides = "collect")

ggsave(here("figures", "panel_int.jpg"), fig_int,
       width = 20, height = 10, dpi = 300)
```



```{r}
f1 <- scm_correlate %>% 
  ggplot(aes(x = int_50, y = pres_max, color = as.factor(month))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(y = bquote("Flu"[MAX]~"Depth"~"(m)"),
       x = bquote("Flu"[0-50*"m"]~"("*mg~m^-2*")"), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())


f2 <- scm_correlate %>% 
  ggplot(aes(x = int_50, y = rho_fmax, color = as.factor(month))) +
  geom_point(size = 6) +
  geom_hline(yintercept = 1024) +
  scale_color_viridis_d(option = "turbo") +
  labs(y = bquote("Flu"[MAX]~sigma*tau~"("*kg~m^-3*")"),
       x = bquote("Flu"[0-50*"m"]~"("*mg~m^-2*")"), 
       color = "Month") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

fig_int2 <- f1 + f2 + plot_layout(guides = "collect")

ggsave(here("figures", "panel_int_pres_rho.jpg"), fig_int2,
       width = 14, height = 6, dpi = 300)
```
```{r}
fl5 %>% 
  left_join(env) %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(pres < 51) %>% 
  ggplot(aes(x = f_npq, y = rho, color = as.factor(year))) +
  geom_point(orientation = "y", size = 6) +
  geom_hline(yintercept = 1024) +
  scale_color_viridis_d(option = "turbo") +
  labs(y = bquote(sigma*tau~"("*kg~m^-3*")"),
       x = bquote("Flu"~"("*mg~m^-3*")"), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

ggsave(here("figures", "profile_Density_flu.jpg"), 
       width = 9, height = 14, dpi = 300)
```

```{r}
fl5 %>% 
  left_join(env) %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(pres < 51) %>%
  ggplot(aes(x = date, y = pres, color = f_npq)) +
  geom_point(orientation = "y", size = 3) +
  # geom_hline(yintercept = 1024) +
  scale_color_viridis_c(option = "turbo") +
  labs(y = bquote(sigma*tau~"("*kg~m^-3*")"),
       color = bquote("Flu"~"("*mg~m^-3*")"), 
       x = "Date") +
  theme_bw() +
  scale_y_reverse() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

ggsave(here("figures", "section_test.jpg"), 
       width = 20, height = 7, dpi = 300)
```


```{r}
test <- fl5 %>%
  left_join(env) %>% 
  filter(station == "KC10") %>% 
  mutate(date_dec = decimal_date(date)) %>% 
  select(date_dec, pres, rho, f_npq) %>% 
  drop_na()

ctd_mba <- mba.surf(test[c("date_dec", "pres", "f_npq")], no.X = 600, no.Y = 600, extend = T)
dimnames(ctd_mba$xyz.est$z) <- list(ctd_mba$xyz.est$x, ctd_mba$xyz.est$y)
ctd_mba_plot <- melt(ctd_mba$xyz.est$z, varnames = c('date_dec', 'pres'), value.name = 'f_npq') %>%
  filter(pres < 51) %>%
  mutate(date_h = lubridate::date_decimal(date_dec),
         date = lubridate::date(date_h),
         year = lubridate::year(date)) 


test2 <- env %>% 
  mutate(date_dec = decimal_date(date),
         date_h = lubridate::date_decimal(date_dec)) %>% 
  select(date_h, r24_dep_dm) %>%
  distinct() 
  

ctd_mba_plot %>% 
  ggplot(aes(x = date_h, y = pres)) +
  geom_raster(aes(fill = f_npq)) +
  geom_line(data = test2, aes(x = date_h, y = r24_dep_dm), color = "white",
            size = 1.25) +
  # geom_line(data = test, aes(x = ))
  # cmocean::scale_fill_cmocean(name = "delta",
  #                             limits = c(0, 10),
  #                             oob = scales::squish) +
  scale_fill_viridis_c(
                       limits = c(0, 10),
                       oob = scales::squish) +
  # geom_contour(aes(z = f), bins = 6, colour = "black", alpha = 0.5) +
  # geom_contour(aes(z = f), binwidth = 5, colour = "black", alpha = 1) +
  # geom_contour(aes(z = f), breaks = 5, colour = "black") +
### Activate to see which pixels are real and not interpolated
  # geom_point(data = ctd_qc, aes(x = date, y = pres),
  #            colour = 'black', size = 0.2, alpha = 0.4, shape = 8) +
###
  labs(y = "depth (m)", x = NULL, fill = "Fluorescence") +
  # coord_cartesian(expand = 0) +
  scale_y_reverse() +
  labs(fill = bquote(CTD[FLU]~"(mg" ~ m^-3*")"),
       y = "Depth") +
  scale_x_datetime(limits = as_datetime(c("2016-01-01", "2024-12-31")),
               expand = c(0, 0), date_breaks = "years", date_labels = "%Y") +
  theme_bw() +
  theme(text = element_text(size = 35), #35
        axis.text = element_text(color = "black"),
        axis.title.x = element_blank(),
        legend.position = "top",
        legend.box = "horizontal") +
  guides(fill = guide_colourbar(title.position = "top", title.hjust = 0.5,
                                barwidth = 50, barheight = 1,
                                frame.colour = "black", ticks.colour = "black"))

ggsave(here("figures", "section_test2_pres.jpg"), 
       width = 20, height = 7, dpi = 300)
```
```{r}
f_export <- test %>% 
  select(date, station, pres, rho, f_npq)

write.csv()
```




```{r}
f1 <- fl5 %>% 
  filter(station == "KC10") %>% 
  left_join(env) %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(pres < 51) %>% 
  filter(year == 2015 | year == 2017 | year == 2018 | year == 2020 | year == 2024) %>% 
  # filter(year == 2023 | year == 2020 | year == 2024 | year == 2019) %>% 
  filter(month == 7) %>% 
  ggplot(aes(x = f_npq, y = pres, color = as.factor(year))) +
  geom_point(orientation = "y", size = 4) +
  geom_line(orientation = "y", size = 2) +
  scale_color_viridis_d(option = "turbo") +
  scale_y_reverse() +
  labs(y = bquote("Depth (m)"),
       x = bquote("Flu"~"("*mg~m^-3*")"), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f2 <- fl5 %>% 
  filter(station == "KC10") %>% 
  left_join(env) %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(pres < 51) %>% 
  filter(year == 2015 | year == 2017 | year == 2018 | year == 2020 | year == 2024) %>%
  # filter(year == 2023 | year == 2020 | year == 2024 | year == 2019) %>% 
  filter(month == 7) %>% 
  ggplot(aes(x = temp, y = pres, color = as.factor(year))) +
  geom_point(orientation = "y", size = 4) +
  geom_line(orientation = "y", size = 2) +
  scale_color_viridis_d(option = "turbo") +
  scale_y_reverse() +
  labs(y = bquote("Depth (m)"),
       x = bquote("Temp"), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f3 <- fl5 %>% 
  filter(station == "KC10") %>% 
  left_join(env) %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(pres < 51) %>% 
  filter(year == 2015 | year == 2017 | year == 2018 | year == 2020 | year == 2024) %>% 
  # filter(year == 2023 | year == 2020 | year == 2024 | year == 2019) %>% 
  filter(month == 7) %>% 
  ggplot(aes(x = sal, y = pres, color = as.factor(year))) +
  geom_point(orientation = "y", size = 4) +
  geom_line(orientation = "y", size = 2) +
  scale_color_viridis_d(option = "turbo") +
  scale_y_reverse() +
  labs(y = bquote("Depth (m)"),
       x = bquote("Salinity"), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())


f4 <- fl5 %>% 
  filter(station == "KC10") %>% 
  left_join(env) %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(pres < 51) %>% 
  filter(year == 2015 | year == 2017 | year == 2018 | year == 2020 | year == 2024) %>%
  # filter(year == 2023 | year == 2020 | year == 2024 | year == 2019) %>% 
  filter(month == 7) %>% 
  ggplot(aes(x = no2_dm, y = pres, color = as.factor(year))) +
  geom_point(orientation = "y", size = 4) +
  geom_line(orientation = "y", size = 2) +
  scale_color_viridis_d(option = "turbo") +
  scale_y_reverse() +
  labs(y = bquote("Depth (m)"),
       x = bquote("DIN"), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

fig_july <- f1 + f2 + f3 + f4 + plot_layout(guides = "collect", nrow = 1)

ggsave(here("figures", "profile_july_prof_2015.jpg"), fig_july,
       width = 20, height = 12, dpi = 300)
```
```{r}

```



```{r}
fl5 %>% 
  filter(station == "KC10") %>% 
  left_join(env) %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(pres < 51) %>% 
  filter(dr_dm > 2) %>% 
  # filter(year == 2023 | year == 2020 | year == 2024 | year == 2019) %>% 
  ggplot(aes(x = f_npq, y = pres, color = as.factor(year))) +
  geom_point(orientation = "y", size = 4) +
  geom_line(orientation = "y", size = 2) +
  scale_color_viridis_d(option = "turbo") +
  scale_y_reverse() +
  labs(y = bquote("Depth (m)"),
       x = bquote("DIN"), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```



```{r}
f1 <- scm_correlate %>% 
  ggplot(aes(x = max_int, y = int_50, color = as.factor(year))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote("Flu"[MAX]:"Flu"[0-50*"m"]~"(%)"),
       y = bquote("Flu"[0-50*"m"]~"("*mg~m^-2*")"), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f2 <- scm_correlate %>% 
  ggplot(aes(x = max_int, y = temp_surf, color = as.factor(year))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote("Flu"[MAX]:"Flu"[0-50*"m"]~"(%)"),
       y = bquote("Temp"[SURF]~"(°C)"), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

f3 <- scm_correlate %>% 
  ggplot(aes(x = max_int, y = wind_b1_3, color = as.factor(year))) +
  geom_point(size = 6) +
  scale_color_viridis_d(option = "turbo") +
  labs(x = bquote("Flu"[MAX]:"Flu"[0-50*"m"]~"(%)"),
       y = bquote("Wind"[LOOKOUT]~"("*m~s^-1*")"), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

fig_mf <- f1 + f2 + f3 + plot_layout(guides = "collect")

ggsave(here("figures", "panel_max_int_rat.jpg"), fig_mf,
       width = 20, height = 6, dpi = 300)
```





```{r}
scm_correlate %>% 
  mutate(month = month(date),
         year = year(date)) %>%
  # filter(month == 7) %>% 
  ggplot(aes(x = max_int, y = rho_fmax, color = as.factor(month))) +
  geom_point() +
  scale_color_ucscgb()
```
```{r}
scm_correlate %>% 
  mutate(month = month(date),
         year = year(date)) %>%
  # filter(month == 7) %>% 
  ggplot(aes(x = dsi_1, y = qt_b1_10, color = as.factor(year))) +
  geom_point() +
  scale_color_ucscgb()
```



```{r}
scm_correlate %>% 
  mutate(year = year(date)) %>% 
  filter(year > 2016) %>% 
  ggplot(aes(x = date, y = qt_b1_10, color = station)) +
  geom_point() +
  geom_line()
```



```{r}
f6 <- f5 %>% 
  left_join(env)

f6 %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  filter(pres < 51) %>% 
  ggplot(aes(x = f_npq, y = rho, color = as.factor(year))) +
  geom_point(orientation = "y") +
  ggsci::scale_color_d3()
```
```{r}
f6 %>% 
  mutate(month = month(date)) %>% 
  filter(pres < 51) %>% 
  filter(month > 2 & month < 11) %>% 
  ggplot(aes(x = f_npq, y = rho, color = int_50)) +
  geom_point(orientation = "y") +
  geom_line(aes(group = date), orientation = "y")
  scale_color_viridis_b()
```







```{r}

f6 <- f6 %>% 
  mutate(f10p = f_max*0.20)

f5 %>% 
  mutate(year = year(date)) %>% 
  filter(year == 2021 & station == "KC10") %>% 
  ggplot(aes(x = f_npq, y = pres, color = as.factor(date))) +
  geom_line(orientation = "y") +
  scale_y_reverse() +
  scale_color_viridis_d() +
  ylim(50, 0)

#2023-03-18-KC10 - needs to be fixed


#Issue where my algorithm is calculating finding the closest FWHM at the surface, but it's much higher at the surface.

#2018-04-29-FZH01 Is a SCM (I think), but I don't have it classed as such.

#For now I am going to ignore trying to figure out profile shape - just focus on the few metrics and try mashing with environmental variables
```

```{r}
scm_metrics %>% 
  mutate(month = month(date)) %>%
  ggplot(aes(x = int_50, y = pres_max, color = as.factor(month))) +
  geom_point() 
```

```{r}
data_pca <- scm_correlate %>%
  mutate(year = year(date),
         month = month(date)) %>% 
  select(date, year, month, temp_surf, sal_surf, dr_dm,
         qt_b1_10, wd_b1_3, wind_b1_3, din_1, dsi_1, s_n) %>% 
  drop_na() %>% 
  filter(!s_n == Inf)

# r24_dep_dm
```

```{r}
#Pulling out explanatory variables for PCA analysis
expl <- data_pca[, 4:12]
```

```{r}
#Scaling data being used for PCA (Should look into whether I should also center as I did with the mantel tests)
expl <- scale(expl)

#Converting to a data frame for subsequent analysis.
expl <- as.data.frame(expl)

```


```{r}
#Running PCA using vegan - when RDA is run without response variables, then it is a PCA
pca <- rda(expl)

#Looking at results - for interpretation of following look at.
head(summary(pca))

#Looking at scores
loadings <- scores(pca, display = 'species', scaling = 0)
loadings
```


```{r}
#Looking at the variables with highest correlation with axis 1
sort (abs (loadings[,1]), decreasing = TRUE)
```
```{r}
#Looking at the variables with highest correlation with axis 2
sort (abs (loadings[,2]), decreasing = TRUE)
```


```{r}
biplot (pca, display = 'species', scaling = 'species')
```

```{r}
#Looking at different scalings
source ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/scripts/NumEcolR2/cleanplot.pca.R')
par (mfrow = c(1,2))
cleanplot.pca (pca, scaling = 1)
cleanplot.pca (pca, scaling = 2)
```
```{r}

#Looking into importance of each axis

# define "evplot" function first:
source ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/scripts/NumEcolR1/evplot.R')

# Finally, in the PCA object select the component $eig with the vector of eigenvalues:
ev <- pca$CA$eig

evplot (ev)

```
```{r}
library (BiodiversityR)
sig <- PCAsignificance (pca, axes = 14)
sig

barplot(sig[c('percentage of variance', 'broken-stick percentage'), ], beside = T, 
  xlab = 'PCA axis', ylab = 'explained variation [%]', col = c('grey', 'black'), 
  legend = TRUE)
```

```{r}

p_pca <- biplot(pca, scaling = 2, type = "none", xlab = c("PCA1"),
               ylab = c("PCA2"), xlim = c(-0.01, 0.1), ylim = c(-1.1, 1.1))

points(scores(pca, display = 'sites', choices = c(1, 2), scaling = 1),
       pch = 21, cex = 2.0)
       # bg = c("blue", "springgreen4", "black", "magenta")[as.factor(data_pca$site_id)])

# legend("topright", legend = c(levels(as.factor(data_pca$site_id))),
#        pch = 21,
#        pt.bg = c("blue", "springgreen4", "black", "magenta"),
#        bty = "n", cex = 1.5)

```

```{r}
data_pca <- data_pca %>%
  mutate(season = case_when(month == 12 | month == 1 | month == 2 ~ "winter",
                            month >= 3 & month <= 5 ~ "spring",
                            month >= 6 & month <= 8 ~ "summer",
                            month >= 9 & month <= 12 ~ "autumn",)) %>%
  relocate(season, .after = month)    
  
#I want to push December from each year to winter of the next year
data_pca <- data_pca %>%
  mutate(year = case_when(season == "winter" & month == 12 ~ year+1,
                           TRUE ~ as.numeric(year)))
```

```{r}

#Setting up parameters for plotting PCA

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc_pca <- sites.long(p_pca, env.data = expl)
meta_pca <- data_pca %>% 
  select(date:season)
sites_loc_pca <- cbind(meta_pca, sites_loc_pca)
head(sites_loc_pca)

# sites_loc_pca <- sites_loc_pca %>% 
#   mutate(year = lubridate::year(date))

#Species location in ordination
species_loc_pca <- species.long(p_pca)
species_loc_pca

axis.long_pca <- axis.long(pca, choices = c(1, 2))
axis.long_pca

#these are both throwing zeros - One I won't need because I'm not plotting species vectors.
#trying something from here. https://tem11010.github.io/Plotting-PCAs/
# env_loc_pca <- as.data.frame(pca$biplot[,1:2])
vscores <- as.data.frame(pca$CA$v)

```

```{r}
int50 <- scm_correlate %>% 
  select(date, station, int_50, max_int)

sites_loc_pca <- sites_loc_pca %>% 
  left_join(int50)
```



```{r}
#Order locations from fjord to shelf
order_loc_seas <- c("winter", "spring", "summer", "autumn")

#Chemtax - Specify order of phyto groups for figures
sites_loc_pca <- arrange(mutate(sites_loc_pca,
                         season = factor(season, levels = order_loc_seas)))
```

```{r}
ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca, aes(x = axis1, y = axis2, 
                                       color = as.factor(month), 
                                       stroke = 1), 
             size = 12) +
  scale_color_viridis_d(option = "turbo") +
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'black', size = 1.5) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                           label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 12,
                  color = "black") +
  labs(x = "PCA1 (55%)",
       y = "PCA2 (14%)", 
       color = NULL) +
  
  # xlim(-1.0, 1.3) +
  # labs(x = paste("PCA 1 (", format(100 *pca$cont[[1]][2,1],
  #                                  digits = 3), "%)", sep = ""),
  #      y = paste("PCA 2 (", format(100 *pca$cont[[1]][2,2], 
  #                                  digits = 2), "%)", sep = "")) +
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.text = element_text(face = "bold", colour = "black"),
        # panel.background = element_blank(),
        # panel.border = element_rect(fill = NA, colour = "black"), 
        # legend.title = element_text(face = "bold", colour = "black"), 
        # legend.text = element_text(colour = "black"),
        # legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 35))
        # 
        # ,
        # legend.direction = "horizontal",
        # legend.position = "top",
        # legend.box = "vertical")

ggsave(here("figures", "PCA_s_n.png"), 
       width = 15, height = 12, dpi = 300)
```
```{r}
pca_phyto <- sites_loc_pca %>% 
  select(date:season, axis1, axis2) %>% 
  left_join(scm_correlate)
```
```{r}
pca_phyto %>% 
  ggplot(aes(x = int_50, axis1, color = as.factor(year))) +
  geom_point()
```
```{r}
hc <- expl

# hc <- scale(hc)

metadata <- data_pca %>%
  select(date) 

#Creating a list of rownames
# labs_list <- labs$sample_name
labs_list <- metadata$date


#Making the rownames of the clustering matrix the ones specified in the above list.
rownames(hc) <- labs_list
```

```{r}

#Performing hierarchical clustering

#Calculating Bray-Curtis Distances
dis <- dist(hc, method = "euclidean")

#Applying average linkage hierarchical clustering
cluster.average <- hclust(dis, "ward.D2")

```

```{r}
coph <- cophenetic(cluster.average)
cor(dis, coph) 
```
```{r}
# Enhanced hierarchical clustering, cut in 3 groups
fviz_dend(cluster.average, cex = 0.5, k = 6, color_labels_by_k = TRUE)
```


```{r}
#Looking at tests to derive cluster number - turning off for now because adds time.
fviz_nbclust(hc, FUN = hcut, method = "wss")
fviz_nbclust(hc, FUN = hcut, method = "silhouette")
gap_stat <- clusGap(hc, FUN = hcut, nstart = 25, K.max = 10, B = 50)
fviz_gap_stat(gap_stat)
```


```{r}
#This step sets clusters. Currently, set to three. Not fully supported by silhouette plot, but does make sense considering the data.

k <- 6
clust <- cutree(cluster.average, k = k)

clust.df <- data.frame(label = rownames(hc),
                                   cluster = factor(clust))

# write_csv(clust.df, here("outputs", "pca_clusters_2023-08-2.csv"))
```

```{r}
# extract dendrogram segment data for plotting

dend <- as.dendrogram(cluster.average)
dendrogram_data <- dendro_data(dend)
dendrogram_segments <- dendrogram_data$segments 
```

```{r}
#Creating metadata sheet with 
# metadata <- micro_piv %>% 
#   select(site_id, date)

# metadata <- micro_piv %>% 
#    select(sample_name, site_id, date)

#Making unique labels by combining site and date into single string
# metadata <- metadata %>% 
#   unite(sample_name, c(site_id, date), sep = "_", remove = FALSE)

# get terminal dendrogram segments and join with names.
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data$labels, by = "x") %>%
 rename(sample_name = label)
  
#   %>% 
# #  left_join(metadata, by = "sample_name") 

```

```{r}
#This is used to draw cluster boxes around the dendrogram clusters in the plot. Not currently using clusters so have turned off, but necessary if using clusters.

dendrogram_data[["labels"]] <- merge(dendrogram_data[["labels"]], clust.df, by = "label")
rect <- aggregate(x~cluster, label(dendrogram_data), range)
rect <- data.frame(rect$cluster, rect$x)
ymax <- mean(cluster.average$height[length(cluster.average$height) - ((k-2):(k-1))])
```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars <- levels(factor(dendrogram_ends$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count <- length(unique(unique_vars$.))

# # get RColorBrewer palette
# get_palette <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))
# 
# # produce RColorBrewer palette based on number of unique variables in metadata:
# palette <- get_palette(color_count) %>% 
#  as.data.frame() %>%
#  rename("color" = ".") %>%
#  rownames_to_column(var = "row_id")
# 
# color_list <- left_join(unique_vars, palette, by = "row_id") %>%
#  select(-row_id)
# 
# site_color <- as.character(color_list$color)
# names(site_color) <- color_list$.
```
```{r}

cluster_df <- clust.df %>% 
  rename(sample_name = label)

dendrogram_ends <- dendrogram_ends %>% 
  left_join(cluster_df)

```

```{r}
#Plotting dendrogram - saving for incorporation later.
ggplot() +
  geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = as.factor(cluster),
              size = 3)) +
  geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name,
                                       color = as.factor(cluster),
           hjust = 1, angle = 90, size = 4)) +
 # geom_hline(yintercept = 0.67, size = 1) +
 # geom_rect(data = rect_abund, aes(xmin = X1 - .3, xmax = X2 + .3, ymin = 0,
 #                                  ymax = ymax_abund),
 #            color = "black", fill = NA, size = 0.8) +
 # scale_color_manual(values = site_color) +
 # scale_y_reverse(limits = c(1, -0.5)) +
 scale_color_npg() +
 ylim(-8, 25) +
  # coord_flip() +
 ylab("Wards Distance") +
 theme_bw() +
 theme(axis.text = element_text(colour = "black"),
       legend.position = "none",
       axis.title.x = element_blank(),
       # axis.title.y = element_blank(),
       axis.text.x = element_blank(),
       text = element_text(size = 25))

# x and y coordinates for aesthetic reasons

 
ggsave(here("figures", "dendrogram_sn.png"),
       width = 18, height = 10, dpi = 300)
```

```{r}

cluster_df <- cluster_df %>% 
  rename(date = sample_name) %>% 
  mutate(date = date(date))
  
pca_phyto <- pca_phyto %>% 
  left_join(cluster_df)

sites_loc_pca <- sites_loc_pca %>% 
  left_join(cluster_df)
  
  
```
```{r}

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca, aes(x = axis1, y = axis2, 
                                       color = cluster, 
                                       stroke = 1), 
             size = 12) +
  scale_color_npg() +
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'black', size = 1.5) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                           label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 12,
                  color = "black") +
  labs(x = "PCA1 (59%)",
       y = "PCA2 (14%)", 
       color = NULL) +
  
  # xlim(-1.0, 1.3) +
  # labs(x = paste("PCA 1 (", format(100 *pca$cont[[1]][2,1],
  #                                  digits = 3), "%)", sep = ""),
  #      y = paste("PCA 2 (", format(100 *pca$cont[[1]][2,2], 
  #                                  digits = 2), "%)", sep = "")) +
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.text = element_text(face = "bold", colour = "black"),
        # panel.background = element_blank(),
        # panel.border = element_rect(fill = NA, colour = "black"), 
        # legend.title = element_text(face = "bold", colour = "black"), 
        # legend.text = element_text(colour = "black"),
        # legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 35))
        # 
        # ,
        # legend.direction = "horizontal",
        # legend.position = "top",
        # legend.box = "vertical")

ggsave(here("figures", "PCA_test_cluster_s_n.png"), 
       width = 15, height = 12, dpi = 300)

```




```{r}
pca_phyto %>% 
  ggplot(aes(x = cluster, y = sal_surf)) +
  geom_boxplot() 

```

```{r}
scm_correlate %>% 
  filter(s_n < 100) %>% 
  ggplot(aes(x = sal_surf, s_n, color = as.factor(year))) +
  geom_point()
```


```{r}
fl6 <- fl5 %>% 
  left_join(cluster_df)

fl6 %>% 
  filter(station == "KC10") %>% 
  filter(date == "2023-05-14") %>% 
  filter(pres < 51) %>% 
  # filter(year == 2023 | year == 2020 | year == 2024 | year == 2019) %>% 
  ggplot(aes(x = f_npq, y = pres, color = as.factor(date))) +
  geom_point(orientation = "y", size = 4) +
  geom_line(orientation = "y", size = 2) +
  scale_color_viridis_d(option = "turbo") +
  scale_y_reverse() +
  labs(y = bquote("Depth (m)"),
       x = bquote("DIN"), 
       color = "Year") +
  theme_bw() +
  theme(text = element_text(size = 30),
        # legend.position = "none",
        axis.text = element_text(color = 'black'),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```

